(()=>{
state.version=13;
state.g30Onboarding=state.g30Onboarding||{physicalComplete:false,trainingStatus:'pending',dietStatus:'pending'};
state.assessmentWorkContext=state.assessmentWorkContext||{};
state.assessmentLifestyle=state.assessmentLifestyle||{};
try{localStorage.setItem(storeKey,JSON.stringify(state))}catch(e){}
if(page!=='assessment')return;

const V13_TARGET=30;
const V13_SECTIONS=[
 {key:'context',name:'Contexto y vida actual',total:6,n:'01',text:'Primero entendemos tu realidad sin asumir que todos trabajan, estudian o viven de la misma manera.'},
 {key:'physical',name:'Físico y hábitos',total:6,n:'02',text:'Movimiento, descanso, alimentación y recuperación: el contexto que rodea a tu cuerpo.'},
 {key:'intellect',name:'Intelecto',total:6,n:'03',text:'Criterio, lógica, aprendizaje, creatividad y resolución de problemas.'},
 {key:'charisma',name:'Carisma',total:6,n:'04',text:'Comunicación, vínculos, liderazgo, integridad y regulación emocional.'},
 {key:'performance',name:'Rendimiento',total:6,n:'05',text:'Disciplina, constancia, organización, productividad y decisiones financieras.'}
];
const cap=(label,field,value,target='work')=>({...choice(label,0),capture:{field,value,target}});
const q=o=>prepareQuestion(o);
const slot=track=>({kind:'v13-adaptive-slot',track});

const contextQ=[
 q({id:'g30-context-main',cat:'Contexto',title:'Tu realidad principal',skill:null,kind:'context',text:'¿Qué ocupa la mayor parte de tu semana actualmente?',options:[cap('Trabajo en relación de dependencia','workType','employee'),cap('Trabajo por mi cuenta / freelance','workType','independent'),cap('Tengo o gestiono un negocio / proyecto propio','workType','owner'),cap('Estudio principalmente','workType','student'),cap('Trabajo y estudio','workType','mixed'),cap('Hogar, cuidados o responsabilidades familiares','workType','caregiver'),cap('Estoy buscando trabajo o en transición','workType','search'),cap('Mi actividad es principalmente física / manual','workType','manual'),cap('Otra realidad o combinación','workType','other')]}),
 q({id:'g30-context-area',cat:'Contexto',title:'Tipo de actividad',skill:null,kind:'context',text:'¿Cuál se parece más a tu actividad principal?',options:[cap('Administración, oficina o gestión','area','admin'),cap('Ventas, comercio o atención al público','area','sales'),cap('Tecnología, técnica o sistemas','area','tech'),cap('Educación o estudio','area','education'),cap('Salud, cuidado o servicio personal','area','health'),cap('Creatividad, contenido o comunicación','area','creative'),cap('Construcción, obra u oficio','area','construction'),cap('Fábrica, producción o industria','area','industrial'),cap('Depósito, carga o logística','area','warehouse'),cap('Transporte o conducción','area','transport'),cap('Gastronomía','area','gastronomy'),cap('Campo o actividad rural','area','fieldwork'),cap('Limpieza, reparación o mantenimiento','area','maintenance'),cap('Otra / combinación','area','other')]}),
 q({id:'g30-context-role',cat:'Contexto',title:'Cómo funciona tu día',skill:null,kind:'context',text:'¿Cómo se organiza normalmente lo que hacés?',options:[cap('Trabajo o avanzo principalmente por mi cuenta','role','individual'),cap('Formo parte de un equipo','role','team'),cap('Coordino tareas o personas','role','coordinator'),cap('Tomo decisiones sobre un equipo o proyecto','role','manager'),cap('Recibo tareas concretas y las ejecuto','role','operator'),cap('Mi día cambia mucho y resuelvo lo que aparece','role','variable'),cap('Combino trabajo mental y físico','role','mixed')]}),
 q({id:'g30-context-resp',cat:'Contexto',title:'Responsabilidad frecuente',skill:null,kind:'context',text:'¿Qué tipo de responsabilidad aparece con más frecuencia en tu semana?',options:[cap('Organizar procesos, tareas o entregas','responsibility','operations'),cap('Administración, registros o documentación','responsibility','admin'),cap('Ventas, negociación o seguimiento comercial','responsibility','sales'),cap('Dinero, costos, caja o presupuestos','responsibility','finance'),cap('Atender personas, clientes o usuarios','responsibility','clients'),cap('Coordinar o acompañar personas','responsibility','people'),cap('Proyectos, seguimiento o planificación','responsibility','projects'),cap('Analizar información y decidir','responsibility','analysis'),cap('Resolver tareas técnicas o manuales','responsibility','technical'),cap('Trabajo físico, carga, obra o producción','responsibility','physical'),cap('Estudiar, practicar o rendir','responsibility','study'),cap('Crear, diseñar o comunicar','responsibility','creative')]}),
 q({id:'g30-context-days',cat:'Contexto',title:'Frecuencia semanal',skill:null,kind:'context',text:'¿Cuántos días por semana suele ocupar tu actividad principal?',options:[cap('1–2 días','workdays',[2,4]),cap('3 días','workdays',[1,3,5]),cap('4 días','workdays',[1,2,4,5]),cap('5 días','workdays',[1,2,3,4,5]),cap('6 días','workdays',[1,2,3,4,5,6]),cap('7 días o responsabilidades todos los días','workdays',[0,1,2,3,4,5,6]),cap('Cambia mucho de una semana a otra','workdays',[1,2,3,4,5])]}),
 q({id:'g30-context-bottleneck',cat:'Contexto',title:'Lo que más querés mejorar',skill:null,kind:'context',text:'Si durante los próximos 30 días pudieras mejorar una sola de estas cosas, ¿cuál tendría más impacto?',options:[cap('Organizarme mejor','bottleneck','organization'),cap('Concentrarme y producir más','bottleneck','focus'),cap('Sostener hábitos y no abandonar','bottleneck','consistency'),cap('Comunicarme mejor','bottleneck','communication'),cap('Coordinar, delegar o liderar mejor','bottleneck','leadership'),cap('Resolver problemas con más claridad','bottleneck','problem'),cap('Aprender más rápido y aplicar lo aprendido','bottleneck','learning'),cap('Ordenar mis finanzas','bottleneck','finance'),cap('Manejar mejor presión, frustración o emociones','bottleneck','emotion')]}),
];

const physicalQ=[
 q({id:'g30-physical-type',cat:'Físico',title:'Actividad física actual',skill:null,kind:'context',text:'¿Qué describe mejor tu actividad física durante una semana normal?',options:[cap('No hago actividad intencional por ahora','activityType','none','life'),cap('Gimnasio o entrenamiento de fuerza','activityType','strength','life'),cap('Calistenia o peso corporal','activityType','calisthenics','life'),cap('Running, ciclismo o resistencia','activityType','endurance','life'),cap('Deporte, boxeo o actividad mixta','activityType','sport','life'),cap('Mi trabajo ya tiene una carga física importante','activityType','manual','life'),cap('Combino fuerza y resistencia/deporte','activityType','mixed','life')]}),
 q({id:'g30-physical-frequency',cat:'Físico',title:'Movimiento semanal',skill:'Salud física',kind:'habit',text:'En las últimas cuatro semanas, ¿con qué frecuencia acumulaste actividad física intencional o trabajo físicamente demandante?',options:[choice('Casi nunca',0),choice('1–2 días por semana',1),choice('3–4 días por semana',2),choice('5 o más días por semana',3)]}),
 q({id:'g30-physical-sleep',cat:'Físico',title:'Sueño',skill:'Salud física',kind:'habit',text:'En una semana normal, ¿cuánto dormís por noche en promedio?',options:[choice('Menos de 5 horas',0),choice('5–6 horas',1),choice('6–7 horas',2),choice('7–9 horas',3),choice('Más de 9 horas la mayoría de los días',2)]}),
 q({id:'g30-physical-food',cat:'Físico',title:'Estructura de alimentación',skill:'Salud física',kind:'habit',text:'¿Qué tan previsible suele ser tu alimentación durante una semana normal?',options:[choice('Casi siempre improviso y salto o cambio comidas sin una estructura',0),choice('Tengo algunas comidas repetidas, pero depende mucho del día',1),choice('La mayoría de los días tengo una estructura bastante estable',2),choice('Planifico con anticipación y puedo ajustar sin perder el objetivo general',3)]}),
 q({id:'g30-physical-recovery',cat:'Físico',title:'Recuperación',skill:'Salud física',kind:'habit',text:'Después de días exigentes física o mentalmente, ¿cómo suele responder tu cuerpo?',options:[choice('La fatiga suele acumularse y me cuesta recuperarme',0),choice('Me recupero, pero muchas veces necesito varios días',1),choice('Normalmente recupero bien si vuelvo a dormir y comer de forma normal',2),choice('Suelo recuperar bien y puedo ajustar carga o descanso cuando noto señales de fatiga',3)]}),
 slot('nutricion')
];

const intellectQ=[
 slot('logica'),slot('logica'),slot('problemas'),
 q({id:'g30-int-knowledge',cat:'Intelecto',title:'Evaluar información',skill:'Conocimiento',kind:'objective-lite',text:'Encontrás una explicación convincente que asegura que un método “siempre funciona”. ¿Qué sería lo más razonable antes de adoptarlo como regla?',options:[choice('Revisar contexto, evidencia y casos donde podría no funcionar',3),choice('Usarlo si quien lo explica tiene mucha experiencia',2),choice('Aceptarlo si coincide con algo que ya pensaba',1),choice('Descartarlo porque ninguna regla puede ser útil',1)]}),
 q({id:'g30-int-learning',cat:'Intelecto',title:'Aprender de verdad',skill:'Aprendizaje',kind:'scenario',text:'Aprendiste algo nuevo y querés comprobar si realmente lo entendiste. ¿Qué prueba te daría mejor información?',options:[choice('Aplicarlo a un caso distinto y explicar por qué funciona cada paso',3),choice('Repetir el mismo ejemplo sin mirar',2),choice('Hacer un resumen y compararlo con el original',2),choice('Volver a leer hasta que resulte familiar',1)]}),
 q({id:'g30-int-creativity',cat:'Intelecto',title:'Creatividad aplicada',skill:'Creatividad',kind:'scenario',text:'Tenés que conseguir un resultado parecido con menos tiempo, dinero o recursos. ¿Cómo empezarías?',options:[choice('Defino qué parte del resultado es imprescindible y genero varias alternativas con compromisos distintos',3),choice('Busco cómo lo resolvió otra persona y adapto la opción más cercana',2),choice('Recorto primero lo más caro o lento y después veo qué se perdió',2),choice('Reduzco todo de manera pareja para asegurar el ahorro',1)]})
];

const charismaQ=[
 q({id:'g30-char-communication',cat:'Carisma',title:'Comunicación',skill:'Comunicación',kind:'scenario',text:'Necesitás que otra persona haga algo importante y querés evitar malentendidos. ¿Qué hacés?',options:[choice('Acordamos resultado esperado, restricciones y cuándo se vuelve a revisar',3),choice('Explico con detalle y dejo la información por escrito',2),choice('Pregunto si quedó claro y respondo dudas',2),choice('Confío en que, si acepta, entendió lo necesario',1)]}),
 q({id:'g30-char-social',cat:'Carisma',title:'Habilidades sociales',skill:'Habilidades sociales',kind:'scenario',text:'Llegás a un entorno donde conocés poco a la gente y necesitás integrarte o colaborar. ¿Qué se parece más a una buena estrategia para vos?',options:[choice('Observo el contexto, inicio conversaciones simples y hago preguntas genuinas',3),choice('Espero una oportunidad natural y después participo',2),choice('Me concentro en la tarea y dejo que el vínculo aparezca con el tiempo',1),choice('Evito iniciar para no resultar invasivo',0)]}),
 q({id:'g30-char-leadership',cat:'Carisma',title:'Liderazgo',skill:'Liderazgo',kind:'scenario',text:'En un grupo, proyecto o situación compartida nadie tiene claro cuál es el próximo paso. ¿Qué harías?',options:[choice('Ayudo a aclarar el resultado, el siguiente paso y quién lo toma',3),choice('Propongo una solución y empiezo yo para generar movimiento',2),choice('Pido opiniones y espero a que aparezca una dirección común',2),choice('Prefiero no intervenir si no me corresponde formalmente',1)]}),
 q({id:'g30-char-emotion',cat:'Carisma',title:'Control emocional',skill:'Control emocional',kind:'scenario',text:'Recibís una crítica que al principio te parece injusta. ¿Qué reacción te parece más útil?',options:[choice('Pido un ejemplo concreto, escucho completo y después comparo esa información con mi punto de vista',3),choice('Escucho y explico enseguida el contexto que pudo faltar',2),choice('Termino la conversación y la evalúo más tarde con calma',2),choice('Respondo en el momento para que mi versión también quede clara',1)]}),
 q({id:'g30-char-integrity',cat:'Carisma',title:'Integridad',skill:'Integridad / valores',kind:'scenario',text:'Notás un error evidente que te beneficia y que probablemente nadie detecte. ¿Qué harías?',options:[choice('Lo informo y dejo que la parte responsable decida cómo corregirlo',3),choice('Pregunto si el resultado es correcto antes de asumir que fue un error',2),choice('Reviso bien la situación y sólo aviso si confirmo que realmente hay un error',2),choice('No hago nada mientras nadie lo cuestione',0)]}),
 q({id:'g30-char-boundaries',cat:'Carisma',title:'Límites y desacuerdo',skill:'Habilidades sociales',kind:'scenario',text:'Alguien te pide algo que no podés cumplir sin perjudicar otra responsabilidad importante. ¿Qué hacés?',options:[choice('Digo claramente qué puedo y qué no puedo hacer y propongo una alternativa realista',3),choice('Acepto una parte y explico que el resto tendrá que esperar',2),choice('Intento acomodarlo aunque mi planificación se complique',1),choice('Evito responder hasta tener más margen',0)]})
];

const performanceQ=[
 q({id:'g30-perf-discipline',cat:'Rendimiento',title:'Disciplina',skill:'Disciplina',kind:'habit',text:'Una tarea importante no tiene fecha externa y nadie te va a controlar. ¿Qué suele pasar en la práctica?',options:[choice('La programo, la empiezo y la reviso aunque no haya presión externa',3),choice('Normalmente avanzo, aunque a veces la desplazo por urgencias',2),choice('La hago cuando aparece tiempo o motivación suficiente',1),choice('Suele quedar postergada hasta que aparece una consecuencia',0)]}),
 q({id:'g30-perf-constancy',cat:'Rendimiento',title:'Constancia',skill:'Constancia',kind:'habit',text:'Una rutina importante se corta durante varios días. ¿Qué suele ocurrir después?',options:[choice('Tengo una regla de reinicio o versión mínima y vuelvo sin esperar condiciones perfectas',3),choice('Suelo retomarla durante la semana siguiente',2),choice('La retomo cuando vuelve una etapa más tranquila o motivación',1),choice('Muchas veces la interrupción termina en abandono',0)]}),
 q({id:'g30-perf-organization',cat:'Rendimiento',title:'Organización',skill:'Organización',kind:'scenario',text:'Tu día ya estaba organizado y aparecen dos asuntos nuevos importantes. ¿Qué hacés?',options:[choice('Reordeno prioridades y decido explícitamente qué se mueve o se cancela',3),choice('Resuelvo primero lo nuevo y después reconstruyo el resto del día',2),choice('Mantengo el plan y trato de encajar lo nuevo donde pueda',1),choice('Voy alternando según lo que parezca más urgente en cada momento',1)]}),
 q({id:'g30-perf-productivity',cat:'Rendimiento',title:'Productividad',skill:'Productividad',kind:'scenario',text:'Tenés un bloque de tiempo limitado y varias cosas pendientes. Una puede destrabar mucho más que las otras. ¿Cómo elegís?',options:[choice('Empiezo por la que genera más impacto o desbloquea más trabajo y busco un resultado concreto',3),choice('Hago primero varias tareas cortas para liberar espacio mental',2),choice('Divido el tiempo entre las dos más urgentes',2),choice('Empiezo por la que tenga la fecha más cercana aunque tenga menos impacto',1)]}),
 q({id:'g30-perf-finance',cat:'Rendimiento',title:'Finanzas personales',skill:'Finanzas personales',kind:'habit',text:'¿Qué tan claro tenés hoy qué entra, qué sale y qué decisiones podés tomar con tu dinero?',options:[choice('Registro/reviso movimientos y conecto ahorro, gasto o inversión con objetivos',3),choice('Tengo una idea bastante clara y una planificación básica',2),choice('Reviso saldos, pero registro o planifico de forma irregular',1),choice('No tengo una visión actualizada de mis movimientos y disponibilidad',0)]}),
 q({id:'g30-perf-adapt',cat:'Rendimiento',title:'Adaptación del plan',skill:'Organización',kind:'scenario',text:'Un plan que venía funcionando deja de encajar porque cambió tu semana. ¿Qué hacés?',options:[choice('Conservo el objetivo, identifico la restricción nueva y rediseño el sistema alrededor de ella',3),choice('Reduzco el plan hasta una versión que todavía pueda cumplir',2),choice('Intento sostenerlo igual unos días para ver si el cambio es temporal',2),choice('Lo abandono y empiezo otro cuando vuelva a tener más tiempo',0)]})
];

function tag(list,idx){const s=V13_SECTIONS[idx];return list.map((x,i)=>{x.section=s.name;x.sectionKey=s.key;x.sectionNumber=idx+1;x.sectionIndex=i+1;x.sectionTotal=6;return x})}
buildAssessmentQueue=function(){return[...tag(contextQ,0),...tag(physicalQ,1),...tag(intellectQ,2),...tag(charismaQ,3),...tag(performanceQ,4)]};
scheduleAdaptive=function(){};scheduleProbe=function(){};
function materialize(raw){if(raw.kind!=='v13-adaptive-slot')return raw;const t=assessmentSession.adaptive[raw.track],diff=clamp(Math.round(t.ability),1,5),made=makeObjectiveQuestion(raw.track,diff);made.section=raw.section;made.sectionKey=raw.sectionKey;made.sectionNumber=raw.sectionNumber;made.sectionIndex=raw.sectionIndex;made.sectionTotal=raw.sectionTotal;return made}

let lastDomain=null;
renderAssessmentQuestion=function(){const question=assessmentSession.current;if(!question)return;const kind=question.kind==='adaptive-objective'?'PRUEBA ADAPTATIVA':question.kind==='context'?'CONTEXTO':'EVIDENCIA';$('#assessmentSectionTitle').textContent=question.section;$('#assessmentSectionProgress').textContent=`${question.sectionIndex}/${question.sectionTotal}`;$('#assessmentSectionStrip').dataset.section=question.sectionKey;$('#assessmentCategory').textContent=`DOMINIO ${question.sectionNumber} DE 5 · ${kind}`;$('#assessmentQuestionTitle').textContent=question.title;$('#assessmentQuestionText').textContent=question.text;$('#assessmentIndex').textContent=`${assessmentSession.answered+1}/${V13_TARGET}`;$('#assessmentProgress').style.width=`${Math.min(100,assessmentSession.answered/V13_TARGET*100)}%`;$('#assessmentOptions').innerHTML=question.options.map((o,i)=>`<button class="answer-btn" data-answer="${i}">${escapeHtml(o.label)}</button>`).join('');if(question.sectionKey!==lastDomain){lastDomain=question.sectionKey;const meta=V13_SECTIONS.find(s=>s.key===question.sectionKey);const ov=$('#domainTransition');if(meta&&ov){$('#domainTransitionNumber').textContent=meta.n;$('#domainTransitionTitle').textContent=meta.name;$('#domainTransitionText').textContent=meta.text;ov.classList.remove('hidden');window.VIDA_SOUND?.play?.('level')}}};

const recordBeforeV13=recordAssessment;
recordAssessment=function(i){const question=assessmentSession.current,opt=question?.options?.[i];if(opt?.capture){const target=opt.capture.target==='life'?state.assessmentLifestyle:state.assessmentWorkContext;target[opt.capture.field]=structuredClone(opt.capture.value);try{localStorage.setItem(storeKey,JSON.stringify(state))}catch(e){}}return recordBeforeV13(i)};

nextAssessment=function(){if(assessmentSession.answered>=V13_TARGET||!assessmentSession.queue.length)return finishAssessment();assessmentSession.current=materialize(assessmentSession.queue.shift());renderAssessmentQuestion()};

const finishBeforeV13=finishAssessment;
finishAssessment=function(){finishBeforeV13();state.version=13;state.assessmentEngineVersion=13;state.assessmentCoreComplete=true;state.assessmentComplete=false;state.assessmentReport=state.assessmentReport||{};state.assessmentReport.engine=13;state.assessmentReport.questionCount=30;state.assessmentReport.sections=V13_SECTIONS.map(s=>({name:s.name,total:6}));state.assessmentReport.completedAt=null;try{localStorage.setItem(storeKey,JSON.stringify(state))}catch(e){};$('#assessmentResultStep')?.classList.add('hidden');$('#assessmentQuestionStep')?.classList.add('hidden');transitionThen('30/30 · EVALUACIÓN COMPLETADA',()=>{$('#assessmentWrap').classList.remove('hidden');$('#assessmentPhysicalStep').classList.remove('hidden');initPhysicalBaseline()},850)};

// ------- Línea base física obligatoria -------
const w=()=>Math.max(45,Number(state.player?.weight)||70);
const METRICS={
 gym:[
  {id:'bench5',name:'Press de banca · carga para 5 reps técnicas',skill:'Fuerza',unit:'kg',ref:()=>w()*.85,dir:'high'},
  {id:'squat5',name:'Sentadilla · carga para 5 reps técnicas',skill:'Fuerza',unit:'kg',ref:()=>w()*1.15,dir:'high'},
  {id:'deadlift5',name:'Peso muerto · carga para 5 reps técnicas',skill:'Fuerza',unit:'kg',ref:()=>w()*1.35,dir:'high'},
  {id:'pullups',name:'Dominadas estrictas',skill:'Fuerza',unit:'reps',ref:()=>10,dir:'high'},
  {id:'run1k',name:'1 km a ritmo exigente controlado',skill:'Resistencia',unit:'min',ref:()=>5.0,dir:'low'},
  {id:'plank',name:'Plancha frontal técnica',skill:'Resistencia',unit:'seg',ref:()=>90,dir:'high'},
  {id:'broadjump',name:'Salto horizontal desde parado',skill:'Velocidad / Potencia',unit:'cm',ref:()=>200,dir:'high'},
  {id:'sprint20',name:'Sprint de 20 m',skill:'Velocidad / Potencia',unit:'seg',ref:()=>3.7,dir:'low'},
  {id:'deepsquat',name:'Sentadilla profunda controlada (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'}],
 calisthenics:[
  {id:'pushups',name:'Flexiones estrictas',skill:'Fuerza',unit:'reps',ref:()=>35,dir:'high'},{id:'pullups',name:'Dominadas estrictas',skill:'Fuerza',unit:'reps',ref:()=>10,dir:'high'},{id:'dips',name:'Fondos estrictos',skill:'Fuerza',unit:'reps',ref:()=>15,dir:'high'},{id:'plank',name:'Plancha frontal técnica',skill:'Resistencia',unit:'seg',ref:()=>90,dir:'high'},{id:'run1k',name:'1 km a ritmo exigente controlado',skill:'Resistencia',unit:'min',ref:()=>5,dir:'low'},{id:'broadjump',name:'Salto horizontal desde parado',skill:'Velocidad / Potencia',unit:'cm',ref:()=>200,dir:'high'},{id:'burpees1m',name:'Burpees controlados en 1 minuto',skill:'Velocidad / Potencia',unit:'reps',ref:()=>20,dir:'high'},{id:'deepsquat',name:'Sentadilla profunda controlada (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'}],
 cardio:[
  {id:'pushups',name:'Flexiones estrictas',skill:'Fuerza',unit:'reps',ref:()=>30,dir:'high'},{id:'goblet',name:'Sentadilla goblet cómoda para 8 reps',skill:'Fuerza',unit:'kg',ref:()=>w()*.35,dir:'high'},{id:'run1k',name:'1 km',skill:'Resistencia',unit:'min',ref:()=>5,dir:'low'},{id:'run5k',name:'5 km',skill:'Resistencia',unit:'min',ref:()=>30,dir:'low'},{id:'cooper',name:'Distancia en 12 minutos',skill:'Resistencia',unit:'m',ref:()=>2400,dir:'high'},{id:'broadjump',name:'Salto horizontal desde parado',skill:'Velocidad / Potencia',unit:'cm',ref:()=>190,dir:'high'},{id:'sprint20',name:'Sprint de 20 m',skill:'Velocidad / Potencia',unit:'seg',ref:()=>3.9,dir:'low'},{id:'deepsquat',name:'Sentadilla profunda controlada (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'}],
 sport:[
  {id:'pushups',name:'Flexiones estrictas',skill:'Fuerza',unit:'reps',ref:()=>35,dir:'high'},{id:'pullups',name:'Dominadas estrictas',skill:'Fuerza',unit:'reps',ref:()=>10,dir:'high'},{id:'carry',name:'Farmer carry por mano · 20 m',skill:'Fuerza',unit:'kg',ref:()=>w()*.35,dir:'high'},{id:'rounds',name:'Rounds de 3 min sostenidos con buena técnica',skill:'Resistencia',unit:'rounds',ref:()=>6,dir:'high'},{id:'run1k',name:'1 km',skill:'Resistencia',unit:'min',ref:()=>5,dir:'low'},{id:'broadjump',name:'Salto horizontal desde parado',skill:'Velocidad / Potencia',unit:'cm',ref:()=>205,dir:'high'},{id:'sprint20',name:'Sprint de 20 m',skill:'Velocidad / Potencia',unit:'seg',ref:()=>3.6,dir:'low'},{id:'deepsquat',name:'Sentadilla profunda controlada (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'}],
 physicalwork:[
  {id:'floorlift',name:'Levantamiento técnico desde el suelo',skill:'Fuerza',unit:'kg',ref:()=>w()*.9,dir:'high'},{id:'carry',name:'Transporte manual 20 m',skill:'Fuerza',unit:'kg',ref:()=>w()*.6,dir:'high'},{id:'carryhand',name:'Farmer carry por mano · 20 m',skill:'Fuerza',unit:'kg',ref:()=>w()*.3,dir:'high'},{id:'steps2m',name:'Subidas a escalón controladas en 2 min',skill:'Resistencia',unit:'reps',ref:()=>45,dir:'high'},{id:'walk1k',name:'1 km a paso rápido',skill:'Resistencia',unit:'min',ref:()=>9,dir:'low'},{id:'broadjump',name:'Salto horizontal desde parado',skill:'Velocidad / Potencia',unit:'cm',ref:()=>180,dir:'high'},{id:'safegetup',name:'Levantarse del suelo sin apoyo (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'},{id:'deepsquat',name:'Sentadilla profunda controlada (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'}],
 general:[
  {id:'pushups',name:'Flexiones estrictas',skill:'Fuerza',unit:'reps',ref:()=>30,dir:'high'},{id:'squats',name:'Sentadillas a peso corporal en 2 min',skill:'Fuerza',unit:'reps',ref:()=>55,dir:'high'},{id:'plank',name:'Plancha frontal técnica',skill:'Resistencia',unit:'seg',ref:()=>75,dir:'high'},{id:'walk1k',name:'1 km a paso rápido',skill:'Resistencia',unit:'min',ref:()=>10,dir:'low'},{id:'broadjump',name:'Salto horizontal desde parado',skill:'Velocidad / Potencia',unit:'cm',ref:()=>170,dir:'high'},{id:'sitstand',name:'Sentarse y levantarse de una silla en 30 s',skill:'Velocidad / Potencia',unit:'reps',ref:()=>16,dir:'high'},{id:'safegetup',name:'Levantarse del suelo sin apoyo (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'},{id:'deepsquat',name:'Sentadilla profunda controlada (0–3)',skill:'Movilidad',unit:'nivel',ref:()=>3,dir:'scale'}]
};
function metricGroupFromLife(){const a=state.assessmentLifestyle?.activityType;return a==='strength'?'gym':a==='calisthenics'?'calisthenics':a==='endurance'?'cardio':a==='sport'||a==='mixed'?'sport':a==='manual'?'physicalwork':'general'}
function metricScore(m,v){if(m.dir==='scale')return [25,45,65,82][Math.max(0,Math.min(3,Math.round(v)))]||25;const ref=Number(m.ref())||1,ratio=m.dir==='low'?ref/Math.max(.01,v):v/ref;return Math.round(clamp(30+50*ratio,25,90))}
function initPhysicalBaseline(){const sel=$('#baselineActivityType');if(!sel)return;sel.value=state.g30PhysicalBaseline?.activityType||metricGroupFromLife();renderMetricGrid();sel.onchange=renderMetricGrid}
function renderMetricGrid(){const type=$('#baselineActivityType').value,list=METRICS[type]||METRICS.general,prev=Object.fromEntries((state.g30PhysicalBaseline?.metrics||[]).map(x=>[x.id,x]));$('#baselineMetricGrid').innerHTML=list.map((m,i)=>{const old=prev[m.id];return `<label class="baseline-metric"><input type="checkbox" data-baseline-check="${m.id}" ${old?'checked':''}><span class="baseline-metric-main"><strong>${escapeHtml(m.name)}</strong><small>${escapeHtml(m.skill)} · referencia interna ${Number(m.ref()).toFixed(m.unit==='min'?1:0)} ${m.unit}</small></span><input class="baseline-value" type="number" step="0.1" min="0" data-baseline-value="${m.id}" value="${old?.value??''}" placeholder="${m.unit}"><b>${escapeHtml(m.unit)}</b></label>`}).join('');updateMetricStatus()}
function selectedMetrics(){const type=$('#baselineActivityType').value,list=METRICS[type]||[],out=[];list.forEach(m=>{const c=$(`[data-baseline-check="${m.id}"]`),v=Number($(`[data-baseline-value="${m.id}"]`)?.value);if(c?.checked&&Number.isFinite(v)&&v>0)out.push({...m,value:v,reference:Number(m.ref()),score:metricScore(m,v)})});return out}
function updateMetricStatus(){const ms=selectedMetrics(),skills=new Set(ms.map(x=>x.skill)),hasStrength=ms.some(x=>x.skill==='Fuerza'),el=$('#baselineMetricStatus');if(!el)return;const ok=ms.length>=4&&skills.size>=3&&hasStrength;el.className=`quiz-feedback ${ok?'good':'bad'}`;el.textContent=ok?`${ms.length} métricas listas · ${skills.size} áreas físicas. Línea base válida.`:`Elegí y cargá al menos 4 métricas válidas, de 3 áreas distintas, incluyendo una de Fuerza. Ahora: ${ms.length} métricas · ${skills.size} áreas.`}
$('#baselineMetricGrid')?.addEventListener('input',updateMetricStatus);$('#baselineMetricGrid')?.addEventListener('change',updateMetricStatus);
function applyPhysicalBaseline(){const ms=selectedMetrics(),skills=new Set(ms.map(x=>x.skill));if(ms.length<4||skills.size<3||!ms.some(x=>x.skill==='Fuerza'))return updateMetricStatus();const by={};ms.forEach(m=>(by[m.skill] ||= []).push(m.score));Object.entries(by).forEach(([skill,scores])=>{state.baseSkills[skill]=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length);state.skillConfidence[skill]='media'});const strength=ms.filter(m=>m.skill==='Fuerza');state.strength=strength.map(m=>({name:m.name,current:m.value,max:m.reference,unit:m.unit}));state.useMeasuredStrength=strength.length>0;state.g30PhysicalBaseline={activityType:$('#baselineActivityType').value,metrics:ms.map(({ref,...m})=>m),completedAt:new Date().toISOString()};state.g30Onboarding.physicalComplete=true;localStorage.setItem(storeKey,JSON.stringify(state));$('#assessmentPhysicalStep').classList.add('hidden');$('#assessmentTrainingStep').classList.remove('hidden');prefillTrainingSetup();window.VIDA_SOUND?.play?.('reward')}
$('#savePhysicalBaselineBtn')?.addEventListener('click',applyPhysicalBaseline);

// ------- Rutina opcional -------
function prefillTrainingSetup(){const p=state.trainingProfile||{},life=state.assessmentLifestyle?.activityType;$('#onTrainingGoal').value=p.goal||(life==='strength'?'strength':life==='sport'||life==='mixed'?'performance':'general');$('#onTrainingLevel').value=p.level||'intermediate';$('#onTrainingLocation').value=p.location||(life==='calisthenics'?'home':'gym');$('#onTrainingMinutes').value=String(p.minutes||60);$('#onTrainingCardio').checked=p.cardio!==false;$('#onTrainingNotes').value=p.notes||'';const days=new Set(p.weekdays||[1,3,5]);$$('#onTrainingWeekdays input').forEach(x=>x.checked=days.has(+x.value))}
$('#setupTrainingNow')?.addEventListener('click',()=>{$('#trainingChoiceButtons').classList.add('hidden');$('#assessmentTrainingForm').classList.remove('hidden')});
function advanceToDiet(status){state.g30Onboarding.trainingStatus=status;localStorage.setItem(storeKey,JSON.stringify(state));$('#assessmentTrainingStep').classList.add('hidden');$('#assessmentDietStep').classList.remove('hidden');prefillDietSetup()}
$('#setupTrainingLater')?.addEventListener('click',()=>advanceToDiet('later'));
$('#assessmentTrainingForm')?.addEventListener('submit',e=>{e.preventDefault();const weekdays=$$('#onTrainingWeekdays input:checked').map(x=>+x.value),msg=$('#onTrainingMessage');if(weekdays.length<2){msg.className='quiz-feedback bad full';msg.textContent='Elegí al menos 2 días o dejá la rutina para después.';return}if(weekdays.length>6){msg.className='quiz-feedback bad full';msg.textContent='Dejá al menos un día sin rutina estructurada.';return}const profile={...state.trainingProfile,goal:$('#onTrainingGoal').value,level:$('#onTrainingLevel').value,location:$('#onTrainingLocation').value,minutes:+$('#onTrainingMinutes').value||60,weekdays,cardio:$('#onTrainingCardio').checked,notes:$('#onTrainingNotes').value.trim(),avoidExercises:state.trainingProfile?.avoidExercises||[]};state.trainingProfile=profile;state.trainingPlan=typeof buildTrainingPlan==='function'?buildTrainingPlan(profile):state.trainingPlan;state.trainingLogs={};localStorage.setItem(storeKey,JSON.stringify(state));advanceToDiet('created');window.VIDA_SOUND?.play?.('reward')});

// ------- Dieta opcional -------
function prefillDietSetup(){const p=state.dietProfile||{};$('#onDietGoal').value=p.goal||'maintain';$('#onDietSex').value=p.sex||'male';$('#onDietActivity').value=String(p.activity||1.5);$('#onDietMeals').value=String(p.meals||4);$('#onDietStyle').value=p.style||'omnivore';$('#onDietBudget').value=p.budget||'normal';$('#onDietDislikes').value=p.dislikes||'';$('#onDietMedical').checked=!!p.medical;$('#onDietSevereAllergy').checked=!!p.severeAllergy;$$('[name=onDietExclude]').forEach(x=>x.checked=(p.exclusions||[]).includes(x.value))}
$('#setupDietNow')?.addEventListener('click',()=>{$('#dietChoiceButtons').classList.add('hidden');$('#assessmentDietForm').classList.remove('hidden')});
$('#setupDietLater')?.addEventListener('click',()=>finishOnboarding('later'));
$('#assessmentDietForm')?.addEventListener('submit',e=>{e.preventDefault();const p={goal:$('#onDietGoal').value,sex:$('#onDietSex').value,activity:$('#onDietActivity').value,meals:+$('#onDietMeals').value,style:$('#onDietStyle').value,budget:$('#onDietBudget').value,exclusions:$$('[name=onDietExclude]:checked').map(x=>x.value),dislikes:$('#onDietDislikes').value.trim(),medical:$('#onDietMedical').checked,severeAllergy:$('#onDietSevereAllergy').checked,manualCalorieAdjustment:Number(state.dietProfile?.manualCalorieAdjustment)||0};state.dietProfile=p;const plan=generateDiet(p),msg=$('#onDietMessage');if(plan?.error){state.dietPlan=null;state.g30Onboarding.dietStatus='needs_review';localStorage.setItem(storeKey,JSON.stringify(state));msg.className='quiz-feedback bad full';msg.textContent=plan.error+' Podés continuar: la configuración queda guardada y el Dietario mostrará que falta revisión.';setTimeout(()=>finishOnboarding('needs_review'),900);return}state.dietPlan=plan;localStorage.setItem(storeKey,JSON.stringify(state));finishOnboarding('created');window.VIDA_SOUND?.play?.('reward')});

function planProfileFromAssessment(){const c=state.assessmentWorkContext||{},old=state.improvementPlan?.profile||{};const workTypeMap={manual:'employee',caregiver:'other'};const resp=c.responsibility?[c.responsibility]:(old.responsibilities||[]);return{...old,workType:workTypeMap[c.workType]||c.workType||old.workType||'employee',area:c.area||old.area||'other',role:c.role||old.role||'individual',teamSize:old.teamSize||0,responsibilities:resp,workdays:Array.isArray(c.workdays)&&c.workdays.length?c.workdays:(old.workdays||[1,2,3,4,5]),bottleneck:c.bottleneck||old.bottleneck||'organization',minutes:old.minutes||30,recurringTasks:old.recurringTasks||[],goalText:old.goalText||({general:'Mejorar en general',fisico:'Mejorar físico y salud',trabajo:'Mejorar trabajo o estudio',social:'Mejorar relaciones y comunicación',finanzas:'Ordenar finanzas',nutricion:'Mejorar alimentación'})[state.player.goal]||'Mejorar en general',customContext:old.customContext||''}}
function ensureG30Plan(){const profile=planProfileFromAssessment();if(!state.improvementPlan?.questionnaireComplete&&typeof generatePlan==='function'){generatePlan(profile)}else{state.improvementPlan=state.improvementPlan||{};state.improvementPlan.profile=profile;if(typeof relevantSkills==='function')state.improvementPlan.focusSkills=relevantSkills(profile).slice(0,3);state.improvementPlan.cycleLength=30}}
function finishOnboarding(dietStatus){state.g30Onboarding.dietStatus=dietStatus;ensureG30Plan();state.assessmentDraft={active:false};state.assessmentComplete=true;state.assessmentCoreComplete=true;state.assessmentCompletedAt=new Date().toISOString();state.assessmentReport.completedAt=state.assessmentCompletedAt;state.assessmentReport.onboarding={physical:true,training:state.g30Onboarding.trainingStatus,diet:state.g30Onboarding.dietStatus};localStorage.setItem(storeKey,JSON.stringify(state));$('#assessmentDietStep').classList.add('hidden');$('#assessmentResultStep').classList.remove('hidden');const attrs=effectiveAttributes(),gl=generalLevel();$('#resultGeneral').textContent=gl;$('#resultRank').textContent=rank(gl);$('#resultNutrition').textContent=`${state.nutritionKnowledge}%`;$('#resultAttributes').innerHTML=Object.entries(attrs).map(([a,v])=>`<div class="attribute-card"><div class="small">${icons[a]} ${a}</div><div class="score">${v}</div><div class="progress"><span style="width:${v}%"></span></div></div>`).join('');$('#resultConfidence').textContent='30 preguntas · línea base física obligatoria · Plan G30 preparado';const t=state.g30Onboarding.trainingStatus==='created'?'Rutina creada':'Rutina pendiente',d=state.g30Onboarding.dietStatus==='created'?'Alimentación creada':state.g30Onboarding.dietStatus==='needs_review'?'Alimentación requiere revisión':'Alimentación pendiente';$('#onboardingSummary').innerHTML=`<div class="summary-chip good">✓ Línea base física</div><div class="summary-chip ${state.g30Onboarding.trainingStatus==='created'?'good':'pending'}">${escapeHtml(t)}</div><div class="summary-chip ${state.g30Onboarding.dietStatus==='created'?'good':'pending'}">${escapeHtml(d)}</div><div class="summary-chip good">✓ Plan G30 listo</div>`;window.VIDA_SOUND?.play?.('level')}

// Quitar listeners antiguos de los dos botones de entrada mediante clones.
function replaceButton(id,handler){const old=$(id);if(!old)return null;const neo=old.cloneNode(true);old.replaceWith(neo);neo.addEventListener('click',handler);return neo}
replaceButton('#enterAssessmentBtn',()=>{startAmbient();window.VIDA_EPIC?.gate?.();$('#assessmentIntro')?.classList.add('opening');setTimeout(()=>transitionThen('ABRIENDO LAS PUERTAS DEL COLISEO...',()=>{$('#assessmentWrap').classList.remove('hidden');$('#assessmentProfileStep').classList.remove('hidden')},1050),700)});
replaceButton('#startAssessmentBtn',()=>{const age=+$('#asAge').value,h=+$('#asHeight').value,wgt=+$('#asWeight').value;if(!age||age<13||!h||!wgt){toast('Completá edad, altura y peso para construir tu perfil base.','warn');return}state.player={...state.player,name:$('#asName').value.trim()||'Jugador',age,height:h,weight:wgt,context:$('#asContext').value,goal:$('#asGoal').value,createdAt:state.player.createdAt||new Date().toISOString()};assessmentSession=freshAssessment();assessmentSession.queue=buildAssessmentQueue();lastDomain=null;state.g30Onboarding={physicalComplete:false,trainingStatus:'pending',dietStatus:'pending'};$('#assessmentProfileStep').classList.add('hidden');transitionThen('EL COLISEO ESTÁ LEYENDO TU CONTEXTO...',()=>{$('#assessmentWrap').classList.remove('hidden');$('#assessmentQuestionStep').classList.remove('hidden');nextAssessment()},750)});

$('#finishAssessmentBtn')?.addEventListener('click',e=>{if(!state.assessmentComplete){e.preventDefault();toast('Primero completá la línea base física.','warn')}});
})();
