(()=>{
if(typeof state==='undefined')return;
state.version=Math.max(Number(state.version||0),16);
const pg=document.body?.dataset?.page||'',Q=s=>document.querySelector(s),QA=s=>[...document.querySelectorAll(s)],ROOT='assets/';
try{localStorage.setItem(typeof storeKey!=='undefined'?storeKey:'vidaRpgStateV8',JSON.stringify(state))}catch(e){}

const ICON={
'index.html':'icons/home.svg','plan.html':'icons/helmet.svg','tareas.html':'icons/check.svg','academia.html':'icons/book.svg','progreso.html':'icons/chart.svg','perfil.html':'icons/user.svg','mas.html':'icons/scroll.svg','combate.html':'icons/sword.svg','dietario.html':'icons/meal.svg','entrenamiento.html':'icons/dumbbell.svg','recetario.html':'icons/meal.svg','tienda.html':'icons/bag.svg','habilidades.html':'icons/flame.svg','historial.html':'icons/clock.svg','cuenta.html':'icons/gear.svg','misiones.html':'icons/sword.svg'};
const HERO={
home:['images/modules/home.webp','FORTALEZA DEL GLADIADOR','Tu centro de mando','Tu personaje, tu Plan G30 y el próximo paso viven en una misma fortaleza.'],
plan:['images/modules/g30.webp','PLAN G30','Tu camino de 30 días','Cuatro frentes. Un sistema. Una versión más fuerte de vos.'],tasks:['images/modules/g30.webp','HOY','El día se gana acción por acción','Priorizá lo importante, completá tus misiones y acumulá evidencia real.'],academy:['images/modules/academy.webp','ACADEMIA','Conocimiento para dominar tu vida','Aprender sirve cuando cambia una decisión, una habilidad o un resultado.'],progress:['images/modules/progress.webp','PROGRESO','Tu evolución tiene que poder verse','Rachas, tendencias, atributos y evidencia para comprobar que realmente avanzás.'],profile:['images/modules/profile.webp','PERFIL DEL GLADIADOR','Tu ficha completa','Métricas físicas, habilidades, contexto y evolución en un solo lugar.'],more:['images/modules/more.webp','CENTRO DEL SISTEMA','Todo tu mundo RPG','Accedé a cada módulo sin convertir la navegación principal en un laberinto.'],combat:['images/modules/arena.webp','ARENA','Entrá al Coliseo','Combatí contra el Sistema o en versus local.'],diet:['images/modules/recipes.webp','ALIMENTACIÓN G30','Comidas reales para una vida real','Planificá una vez, cambiá lo que no te gusta y mantené una estructura flexible.'],training:['images/modules/training.webp','ENTRENAMIENTO G30','Entrená con intención','Una rutina editable con alternativas y métricas que representan tu actividad.'],recipes:['images/modules/recipes.webp','RECETARIO','Cocina práctica G30','Recetas visuales, simples y avanzadas para convertir el plan en comida de verdad.'],store:['images/modules/store.webp','TESORERÍA','Tus monedas también cuentan una historia','Desbloqueá contenido y personalización con recompensas del juego.'],skills:['images/modules/profile.webp','HABILIDADES','Veinte skills. Evidencia real.','El XP premia la práctica; el nivel cambia cuando cambia tu capacidad.'],history:['images/modules/progress.webp','HISTORIAL','Tu camino deja huella','Revisá qué hiciste y cómo se está construyendo tu personaje.'],missions:['images/modules/g30.webp','MISIONES','El Sistema te devuelve una acción','Desafíos adaptados al contexto, al día y a lo que necesitás mejorar.'],account:['images/modules/more.webp','CUENTA','Tus datos y tu mundo','Backup, privacidad y configuración sin romper la inmersión.']};

function iconize(){
 QA('.desktop-nav a,.mobile-nav a').forEach(a=>{const href=(a.getAttribute('href')||'').split('?')[0],file=ICON[href];if(!file||a.querySelector('.v16-nav-icon'))return;const old=a.querySelector(':scope > span');if(old)old.classList.add('v16-old-nav-icon');const im=document.createElement('img');im.className='v16-nav-icon';im.src=ROOT+file;im.alt='';a.prepend(im)});
 QA('.system-module').forEach(a=>{const href=(a.getAttribute('href')||'').split('?')[0],file=ICON[href];if(!file||a.querySelector('.v16-module-icon'))return;const im=document.createElement('img');im.className='v16-module-icon';im.src=ROOT+file;im.alt='';im.loading='lazy';a.prepend(im)});
}
function addHero(){
 if(pg==='assessment')return;const main=Q('main');if(!main)return;Q('.page-scene.v14')?.remove();if(Q('.v16-module-hero'))return;const h=HERO[pg]||HERO.home;const sec=document.createElement('section');sec.className='v16-module-hero';sec.innerHTML=`<img src="${ROOT+h[0]}" alt="" loading="eager"><div class="v16-module-hero-shade"></div><div class="v16-module-hero-copy"><div class="eyebrow">${h[1]}</div><h1>${h[2]}</h1><p>${h[3]}</p></div>`;main.prepend(sec);document.body.style.setProperty('--v16-page-art',`url("${ROOT+h[0]}")`)
}
function practicalStrip(){
 const main=Q('main');if(!main)return;
 if((pg==='recipes'||pg==='diet')&&!Q('.v16-food-strip')){const target=main.querySelector('.card,section.card');if(target){const d=document.createElement('div');d.className='v16-practical-strip v16-food-strip';d.innerHTML=`<div class="v16-strip-head"><span class="eyebrow">IMÁGENES PRÁCTICAS</span><strong>Comida de verdad, no menús abstractos</strong></div><div class="v16-strip-images">${[1,2,3,4].map(i=>`<img src="${ROOT}images/food/meal-${i}.webp" alt="Ejemplo de comida G30" loading="lazy">`).join('')}</div>`;target.insertAdjacentElement('afterend',d)}}
 if(pg==='training'&&!Q('.v16-exercise-strip')){const target=main.querySelector('.card,section.card');if(target){const d=document.createElement('div');d.className='v16-practical-strip v16-exercise-strip';d.innerHTML=`<div class="v16-strip-head"><span class="eyebrow">BIBLIOTECA VISUAL</span><strong>Reconocé el ejercicio antes de editarlo</strong></div><div class="v16-strip-images">${[1,2,3,4].map(i=>`<img src="${ROOT}images/exercise/exercise-${i}.webp" alt="Ejemplo de ejercicio" loading="lazy">`).join('')}</div>`;target.insertAdjacentElement('afterend',d)}}
}
function enrichDynamic(){
 if(pg==='recipes'&&typeof renderRecipes==='function'&&!renderRecipes.__v16){const old=renderRecipes;renderRecipes=function(...a){const r=old(...a);setTimeout(()=>QA('#recipeGrid .recipe-card').forEach((c,i)=>{if(c.querySelector('.v16-card-photo'))return;const im=document.createElement('img');im.className='v16-card-photo';im.src=`${ROOT}images/food/meal-${i%4+1}.webp`;im.alt='Vista de comida';im.loading='lazy';c.prepend(im)}),0);return r};renderRecipes.__v16=1;renderRecipes()}
 if(pg==='training'&&typeof renderTrainingPage==='function'&&!renderTrainingPage.__v16){const old=renderTrainingPage;renderTrainingPage=function(...a){const r=old(...a);setTimeout(()=>QA('#trainingWeek .exercise-row').forEach((row,i)=>{if(row.querySelector('.v16-exercise-thumb'))return;const im=document.createElement('img');im.className='v16-exercise-thumb';im.src=`${ROOT}images/exercise/exercise-${i%4+1}.webp`;im.alt='Vista de ejercicio';im.loading='lazy';row.insertBefore(im,row.children[1]||null)}),0);return r};renderTrainingPage.__v16=1;renderTrainingPage()}
}
function arenaPortraits(){if(pg!=='combat')return;const f=QA('#battleOverlay .fighter');if(f.length<2)return;if(!f[0].querySelector('.v16-fighter-portrait')){const im=document.createElement('img');im.src=ROOT+'images/portraits/gladiator.webp';im.className='v16-fighter-portrait';im.alt='Gladiador';f[0].prepend(im)}if(!f[1].querySelector('.v16-fighter-portrait')){const im=document.createElement('img');im.src=ROOT+'images/portraits/system.webp';im.className='v16-fighter-portrait';im.alt='Rival';f[1].prepend(im)}}

function cinematic({id,image,kicker,title,lines,hint,onClick}){let ov=Q('#'+id);if(ov)return ov;ov=document.createElement('div');ov.id=id;ov.className='v16-cinematic-gate';ov.tabIndex=0;ov.innerHTML=`<img class="v16-cinematic-bg" src="${ROOT+image}" alt=""><div class="v16-cinematic-shade"></div><div class="v16-cinematic-copy"><div class="eyebrow">${kicker}</div><h1>${title}</h1>${lines.map(x=>`<p>${x}</p>`).join('')}<small class="v16-click-hint">${hint}</small></div>`;const go=e=>{if(e?.target?.closest?.('button,a,input,select,textarea'))return;onClick?.(ov)};ov.addEventListener('click',go);ov.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onClick?.(ov)}});document.body.appendChild(ov);return ov}
function homeGate(){if(pg!=='home'||sessionStorage.getItem('vidaRpgHomeGateV16')==='1')return;document.body.classList.add('v16-cinematic-open');const ov=cinematic({id:'homeEntryCinematicV16',image:'images/cinematic/home-entry.webp',kicker:'AVISO DEL COLISEO',title:'El Coliseo te reconoce',lines:['Tu punto de partida fue registrado. Tus fortalezas y debilidades ya tienen una referencia.','Ahora empieza la parte que ningún cuestionario puede hacer por vos: actuar.'],hint:'tocá para entrar',onClick:el=>{sessionStorage.setItem('vidaRpgHomeGateV16','1');el.classList.add('leaving');document.body.classList.remove('v16-cinematic-open');setTimeout(()=>el.remove(),380)}});setTimeout(()=>ov.focus({preventScroll:true}),50)}
function transformationGate(){if(pg!=='assessment')return;const b=Q('#finishAssessmentBtn');if(!b)return;b.addEventListener('click',e=>{if(!state.assessmentComplete)return;e.preventDefault();e.stopImmediatePropagation();document.body.classList.add('v16-cinematic-open');const ov=cinematic({id:'transformationCinematicV16',image:'images/cinematic/transformation.webp',kicker:'DÍA CERO · AVISO DEL COLISEO',title:'Tu transformación comienza ahora',lines:['Durante los próximos 30 días, cada decisión va a moldear a tu personaje.','El Coliseo no premia intención. Premia acción.'],hint:'tocá para entrar al Coliseo',onClick:el=>{el.classList.add('leaving');sessionStorage.removeItem('vidaRpgHomeGateV16');setTimeout(()=>location.href='index.html?transformacion=1',350)}});setTimeout(()=>ov.focus({preventScroll:true}),50)},true)}
function staticDomains(){if(pg!=='assessment')return;const ov=Q('#domainTransition');if(!ov)return;let waiting=false,clicked=false;const card=ov.querySelector('.domain-transition-card');if(card&&!card.querySelector('.v16-click-hint'))card.insertAdjacentHTML('beforeend','<small class="v16-click-hint">tocá para continuar</small>');ov.style.setProperty('--v16-domain-art',`url("${ROOT}images/modules/evaluation.webp")`);document.body.style.setProperty('--v16-assessment-art',`url("${ROOT}images/cinematic/home-entry.webp")`);const activate=()=>{if(!ov.classList.contains('hidden')){waiting=true;clicked=false;ov.classList.add('v16-static-domain');ov.tabIndex=0;setTimeout(()=>ov.focus({preventScroll:true}),30)}};const close=()=>{if(!waiting)return;clicked=true;waiting=false;ov.classList.add('hidden')};ov.addEventListener('click',close);ov.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();close()}});new MutationObserver(()=>{if(!ov.classList.contains('hidden'))activate();else if(waiting&&!clicked)queueMicrotask(()=>{if(waiting&&!clicked)ov.classList.remove('hidden')})}).observe(ov,{attributes:true,attributeFilter:['class']});activate()}
function badges(){QA('.card').forEach((c,i)=>{if(c.classList.contains('v16-badged')||c.closest('#battleOverlay'))return;c.classList.add('v16-badged');if(i%4===0){const s=document.createElement('span');s.className='v16-corner-mark';s.textContent='G30';c.appendChild(s)}})}
function init(){document.body.classList.add('visual-v16');iconize();addHero();practicalStrip();enrichDynamic();arenaPortraits();staticDomains();transformationGate();homeGate();badges();setTimeout(()=>{iconize();practicalStrip();arenaPortraits();badges()},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
