(()=>{
const cfg=window.VIDA_RPG_CONFIG||{};

function ensureV6State(){
  state.version=Math.max(Number(state.version)||0,7);
  state.missions=state.missions||{daily:{},weekly:{},chests:{}};
  state.missions.daily=state.missions.daily||{};state.missions.weekly=state.missions.weekly||{};state.missions.chests=state.missions.chests||{};
  state.snapshots=state.snapshots||{};state.dietLogs=state.dietLogs||{};state.evidenceLog=state.evidenceLog||[];
  state.academyCertifications=state.academyCertifications||{};
  state.rpg=state.rpg||{};state.rpg.title=state.rpg.title||'Despertado';state.rpg.frame=state.rpg.frame||'standard';state.rpg.briefingSeen=state.rpg.briefingSeen||{};
  state.rpg.sound=state.rpg.sound!==false;state.cloud=state.cloud||{email:'',userId:'',accessToken:'',refreshToken:''};
  state.monetization=state.monetization||{premium:false,bonusLessons:{}};state.monetization.bonusLessons=state.monetization.bonusLessons||{};
  state.dietProfile=state.dietProfile||{};state.dietProfile.manualCalorieAdjustment=Number(state.dietProfile.manualCalorieAdjustment)||0;
}
ensureV6State();

function attrForSkill(skill){return Object.keys(skillMap).find(a=>skillMap[a].includes(skill))||'Rendimiento'}
function allCharacterXp(){return allDoneTasks().reduce((s,t)=>s+(+t.xp||0),0)+allEvents().reduce((s,e)=>s+(+e.xp||0),0)}
function characterLevelData(){const xp=allCharacterXp(),level=Math.floor(Math.sqrt(Math.max(0,xp)/25))+1,floor=25*Math.pow(level-1,2),next=25*Math.pow(level,2),current=xp-floor,needed=Math.max(1,next-floor);return{xp,level,current,needed,pct:clamp(current/needed*100)}}
const titleDefs=[['Despertado',1],['Cazador',3],['Estratega',5],['Discípulo',8],['Maestro de hábitos',12],['Ascendente',16],['Monarca personal',20]];
function unlockedTitles(){const l=characterLevelData().level;return titleDefs.filter(x=>l>=x[1]).map(x=>x[0])}
function unlockedFrames(){const l=characterLevelData().level,out=[['standard','Estándar']];if(l>=4||Object.values(state.missions.chests).some(x=>x.claimed))out.push(['cyan','Nexo cian']);if(l>=10)out.push(['gold','Ascenso dorado']);if(l>=16)out.push(['void','Vacío arcano']);return out}
function frameClass(){return state.rpg.frame&&state.rpg.frame!=='standard'?`frame-${state.rpg.frame}`:''}
function playTone(type='click'){if(window.VIDA_SOUND?.play)return window.VIDA_SOUND.play(type);try{if(localStorage.getItem('vidaRpgSoundV7')==='off')return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);const now=ctx.currentTime;o.frequency.value=type==='reward'?620:type==='level'?420:260;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.06,now+.02);g.gain.exponentialRampToValueAtTime(.0001,now+.2);o.start();o.stop(now+.22)}catch(e){}}
function toast(msg,type=''){let stack=$('#toastStack');if(!stack){stack=document.createElement('div');stack.id='toastStack';stack.className='toast-stack';document.body.appendChild(stack)}const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;stack.appendChild(el);setTimeout(()=>el.remove(),3200)}

// -------- Evidence-based skill engine: XP no longer increases skill score directly --------
function missionEvidence(skill){let assigned=0,done=0;Object.values(state.missions.daily||{}).forEach(d=>(d.items||[]).forEach(m=>{if(m.skill===skill){assigned++;if(m.done)done++}}));if(assigned<4)return null;return{rate:done/assigned,n:assigned}}
function dietAdherenceRecent(days=21){const entries=Object.entries(state.dietLogs||{}).sort(([a],[b])=>b.localeCompare(a)).slice(0,days);const vals=entries.map(([,l])=>Number(l.adherence)).filter(Number.isFinite);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function evidenceAdjustedSkill(skill,base){let score=base;const me=missionEvidence(skill);if(me){const observed=30+50*me.rate,w=Math.min(.22,.07+(me.n-4)*.01);score=score*(1-w)+observed*w}
  if((skill==='Salud física'||skill==='Disciplina')&&Object.keys(state.dietLogs||{}).length>=7){const a=dietAdherenceRecent();if(a!=null){const observed=32+48*a, w=.10;score=score*(1-w)+observed*w}}
  if(Object.values(state.academyCertifications||{}).some(c=>c.passed&&c.skills?.includes(skill)))score+=2;
  return Math.round(clamp(score,0,100))}
function v6Confidence(skill){let c=effectiveConfidence(skill);const me=missionEvidence(skill);if(me&&me.n>=12&&me.rate>=.55)c=c==='baja'?'media':c;if(me&&me.n>=25&&me.rate>=.65)c='alta';if((skill==='Salud física'||skill==='Disciplina')&&Object.keys(state.dietLogs||{}).length>=14&&c==='baja')c='media';return c}
effectiveSkillData=function(){const xp=xpBySkill(),out={};allSkills.forEach(skill=>{const base=baseSkillScore(skill),score=evidenceAdjustedSkill(skill,base);out[skill]={score,totalXp:xp[skill],base,confidence:v6Confidence(skill)}});return out};

const renderSkillsV5=renderSkills;
renderSkills=function(){renderAttributes();const data=effectiveSkillData();const el=$('#skillsGrid');if(!el)return;el.innerHTML=Object.entries(skillMap).map(([a,n])=>`<section class="skill-group"><h3>${icons[a]} ${a}</h3>${n.map(k=>{const d=data[k],me=missionEvidence(k),evidencePct=d.confidence==='alta'?100:d.confidence==='media'?62:32;return`<div class="skill-row"><div class="skill-top"><span>${escapeHtml(k)}</span><strong>${d.score}</strong></div><div class="skill-evidence"><span class="training-xp">${d.totalXp} XP de entrenamiento</span><span class="evidence-label">confianza ${d.confidence}</span></div><div class="evidence-meter"><span style="width:${evidencePct}%"></span></div>${me?`<div class="skill-xp">Misiones del Sistema: ${Math.round(me.rate*100)}% · ${me.n} asignadas</div>`:'<div class="skill-xp">El XP no modifica automáticamente este puntaje.</div>'}</div>`}).join('')}</section>`).join('')}

// -------- Missions --------
const missionTemplates={
'Inteligencia aplicada':['Tomá una decisión usando un dato concreto y anotá qué dato cambió tu decisión.','Resolvé un cálculo práctico que necesites hoy sin delegarlo a una calculadora automática hasta plantear el problema.'],
'Conocimiento':['Aprendé 10 minutos sobre un tema útil y anotá 3 ideas que no sabías.','Contrastá una afirmación que hayas escuchado con una fuente más sólida.'],
'Aprendizaje':['Explicá sin mirar algo que aprendiste y detectá al menos un punto que todavía no podés explicar.','Aplicá hoy una idea aprendida recientemente en un caso nuevo.'],
'Resolución de problemas':['Elegí un problema real: definí el síntoma, una hipótesis y una prueba pequeña.','Antes de corregir algo que falló, anotá qué cambió desde la última vez que funcionó.'],
'Creatividad':['Generá 3 alternativas distintas para una limitación real de hoy.','Buscá una forma de lograr el mismo resultado usando menos tiempo, dinero o pasos.'],
'Comunicación':['Tené una conversación importante y cerrala confirmando próximos pasos.','Pedí una aclaración concreta en vez de asumir que entendiste.'],
'Habilidades sociales':['Iniciá una conversación que normalmente postergarías.','En un desacuerdo, hacé una pregunta para entender el criterio de la otra persona antes de responder.'],
'Liderazgo':['En una tarea compartida, dejá claro responsable, resultado y momento de revisión.','Detectá un bloqueo de otra persona y ayudá a definir el siguiente paso sin hacerle todo el trabajo.'],
'Control emocional':['Ante una molestia real, describí el hecho antes de opinar sobre la persona.','Antes de responder algo que te active, esperá unos minutos y volvé con una pregunta concreta.'],
'Integridad / valores':['Corregí o comunicá un error propio aunque nadie te lo haya señalado.','Cumplí hoy un compromiso pequeño que sería fácil dejar pasar sin consecuencias.'],
'Disciplina':['Empezá durante 15 minutos una tarea importante aunque no tengas ganas.','Hacé primero una acción importante antes de abrir una distracción habitual.'],
'Constancia':['Cumplí la versión mínima de una rutina que querés sostener.','Repetí hoy una acción útil que ya hiciste al menos dos veces esta semana.'],
'Organización':['Definí tus 3 prioridades y reservá un bloque concreto para la principal.','Cerrá el día dejando anotado el primer paso de mañana.'],
'Productividad':['Completá una tarea de alto impacto antes de dedicarte a tareas pequeñas.','Protegé un bloque de 30 minutos sin interrupciones para una sola tarea.'],
'Finanzas personales':['Registrá los movimientos de hoy y revisá uno que no reconozcas de inmediato.','Revisá un gasto reciente y decidí si está alineado con una prioridad real.'],
'Fuerza':['Si hoy entrenás fuerza, registrá al menos un ejercicio con carga y repeticiones. Si no entrenás, revisá tu último registro.','Completá tu sesión de fuerza planificada sin sacrificar técnica para mover más carga.'],
'Resistencia':['Hacé la sesión de resistencia que tengas planificada o una caminata activa razonable para tu nivel.','Registrá duración e intensidad percibida de una actividad aeróbica que ya forme parte de tu rutina.'],
'Velocidad / Potencia':['Si tu entrenamiento incluye potencia, registrá una serie de sprints, saltos o técnica explosiva sin exceder tu planificación.','Practicá calidad técnica en una acción rápida que ya entrenes habitualmente.'],
'Movilidad':['Hacé 8 minutos de movilidad sobre una zona que notes limitada, sin forzar dolor.','Repetí un movimiento de movilidad que puedas comparar con tu propio rango habitual.'],
'Salud física':['Prepará una hora objetivo para acostarte y reducÍ una barrera concreta que suele retrasarte.','Cumplí una acción básica de cuidado físico que ya esté dentro de tu rutina: sueño, actividad o comida planificada.']};
function seededIndex(text,n){let h=0;for(const c of text)h=(h*31+c.charCodeAt(0))>>>0;return n?h%n:0}
function weakestSkills(){return[...allSkills].sort((a,b)=>baseSkillScore(a)-baseSkillScore(b))}
const g30MissionParts={
'Inteligencia aplicada':{verbs:['estimá','compará','decidí','calculá'],targets:['un resultado real antes de conocerlo','dos alternativas de una decisión','un costo/beneficio concreto','una prioridad usando datos'],finishes:['y revisá el error de tu estimación','usando al menos tres criterios','anotando qué dato podría hacerte cambiar','dejando por escrito la alternativa descartada']},
'Conocimiento':{verbs:['contrastá','resumí','explicá','verificá'],targets:['una afirmación que usás seguido','un tema importante de tu actividad','un concepto que creés dominar','una fuente que parezca convincente'],finishes:['con dos fuentes o datos independientes','en menos de cinco frases y con un ejemplo','sin mirar material y luego corregite','separando evidencia de opinión']},
'Aprendizaje':{verbs:['practica','recuperá de memoria','aplicá','enseñá'],targets:['una habilidad que estás aprendiendo','un concepto reciente','un procedimiento nuevo','algo aprendido esta semana'],finishes:['en un caso distinto','antes de volver a mirar la respuesta','y registrá qué tuviste que adaptar','con un ejemplo que no hayas visto antes']},
'Resolución de problemas':{verbs:['definí','aislá','probá','descomponé'],targets:['un problema real de hoy','una causa posible','la hipótesis más informativa','un bloqueo complejo'],finishes:['en síntoma, causa posible y prueba','cambiando una sola variable','con una prueba pequeña y reversible','hasta encontrar el siguiente paso ejecutable']},
'Creatividad':{verbs:['generá','combiná','replanteá','prototipá'],targets:['tres alternativas','dos ideas que normalmente no juntarías','un problema cambiando una restricción','una solución de baja fidelidad'],finishes:['antes de elegir','y evaluá qué aporta cada una','para descubrir otra vía','y pedí feedback sobre un criterio concreto']},
'Comunicación':{verbs:['confirmá','resumí','preguntá','aclará'],targets:['un pedido importante','una conversación con varios puntos','una expectativa ambigua','un acuerdo pendiente'],finishes:['resultado, responsable y próximo paso','en una frase verificable','antes de asumir la intención','hasta que ambos puedan repetir lo acordado']},
'Habilidades sociales':{verbs:['iniciá','escuchá','hacé','pedí'],targets:['una conversación útil que venís postergando','a alguien sin preparar tu respuesta','una pregunta abierta genuina','feedback sobre una interacción'],finishes:['sin buscar una respuesta perfecta','y resumí qué entendiste','que permita conocer mejor su punto de vista','con un ejemplo concreto']},
'Liderazgo':{verbs:['delegá','destrabá','alineá','revisá'],targets:['una tarea real','un bloqueo de otra persona','una responsabilidad compartida','un resultado del equipo'],finishes:['con resultado, autonomía y revisión','sin absorber toda la ejecución','definiendo quién decide qué','dando feedback sobre hechos observables']},
'Control emocional':{verbs:['separá','demorá','reformulá','registrá'],targets:['un hecho de tu interpretación','una respuesta impulsiva','una crítica que te incomode','una situación que te activó'],finishes:['antes de reaccionar','hasta recuperar el objetivo de la conversación','pidiendo primero un ejemplo concreto','anotando qué parte controlás']},
'Integridad / valores':{verbs:['cumplí','corregí','decidí','hacete cargo de'],targets:['un compromiso sin supervisión','un error que podría beneficiarte','una situación incómoda','una consecuencia de una decisión'],finishes:['aunque nadie te controle','antes de que escale','usando una regla que defenderías públicamente','sin desplazar responsabilidad']},
'Disciplina':{verbs:['empezá','cumplí','protegé','terminá'],targets:['una tarea incómoda','una regla definida ayer','un bloque de trabajo importante','una acción sin presión externa'],finishes:['por diez minutos sin negociar','aunque hoy no tengas ganas','antes de una recompensa fácil','antes de abrir una distracción habitual']},
'Constancia':{verbs:['repetí','reiniciá','hacé','sostené'],targets:['tu hábito mínimo','una rutina interrumpida','la versión mínima de una acción','un comportamiento que querés automatizar'],finishes:['aunque el día sea imperfecto','sin intentar compensar todo de golpe','para mantener la cadena','sin subir todavía la dificultad']},
'Organización':{verbs:['priorizá','ordená','cerrá','convertí'],targets:['tres resultados del día','un pendiente repetitivo','tu jornada de hoy','una tarea frecuente'],finishes:['y definí qué queda afuera','dejando próximo paso y fecha','dejando escrito el primer paso de mañana','en una checklist de máximo cinco pasos']},
'Productividad':{verbs:['protegé','terminá','reducí','agrupá'],targets:['un bloque de foco','una parte de alto impacto','una fuente de interrupciones','tareas pequeñas similares'],finishes:['sin cambiar de contexto','hasta un resultado observable','durante al menos treinta minutos','para liberar un bloque más largo']},
'Finanzas personales':{verbs:['registrá','compará','revisá','planificá'],targets:['un movimiento relevante','dos opciones de gasto','tu saldo/flujo actual','un gasto próximo'],finishes:['y explicá su impacto','por costo total y utilidad','buscando una variación que merezca atención','antes de que llegue la decisión']},
'Fuerza':{verbs:['registrá','practicá','compará','mejorá'],targets:['un ejercicio de fuerza','una técnica de movimiento','una serie actual con una anterior','control y rango de movimiento'],finishes:['con carga, repeticiones y esfuerzo','sin perseguir un récord','usando datos y no memoria','sin agregar peso si la técnica cae']},
'Resistencia':{verbs:['completá','registrá','mantené','sumá'],targets:['un bloque aeróbico adecuado','duración y esfuerzo de una sesión','un ritmo sostenible','movimiento suave'],finishes:['sin convertirlo en una prueba máxima','para comparar la próxima vez','sin acelerar al principio','sin interferir con recuperación']},
'Velocidad / Potencia':{verbs:['practicá','priorizá','registrá','repetí'],targets:['una acción explosiva','descansos completos','una referencia de velocidad/potencia','pocas repeticiones de calidad'],finishes:['deteniéndote si cae mucho la calidad','en vez de acumular fatiga','para tener una línea base','con intención máxima y técnica controlada']},
'Movilidad':{verbs:['trabajá','evaluá','practicá','explorá'],targets:['un rango que necesitás','una limitación concreta','control activo','un movimiento cómodo'],finishes:['sin dolor','antes y después de un bloque breve','sin forzar amplitud pasiva','respirando y sin rebotes agresivos']},
'Salud física':{verbs:['protegé','registrá','ajustá','priorizá'],targets:['una decisión de recuperación','sueño y energía','la carga del día','una conducta básica de salud'],finishes:['según fatiga real','para mirar tendencia y no un día aislado','si varias señales vienen empeorando','que puedas repetir mañana']}
};
function g30MissionPick(arr,key,offset=0){return arr[(seededIndex(key+':'+offset,99991)+offset)%arr.length]}
function g30MissionText(skill,date,slot){const p=g30MissionParts[skill]||g30MissionParts.Productividad,profile=state.improvementPlan?.profile||{},real=(profile.recurringTasks||[]).filter(Boolean);if(real.length&&['Organización','Productividad','Disciplina'].includes(skill)&&seededIndex(date+skill+slot,4)===0){const t=real[seededIndex(date+skill+'real'+slot,real.length)];return`Aplicá ${skill.toLowerCase()} a una tarea real: “${t}”. Dejala con un resultado observable y próximo paso claro.`}return`${g30MissionPick(p.verbs,date+skill,slot)} ${g30MissionPick(p.targets,date+skill+'t',slot+1)} ${g30MissionPick(p.finishes,date+skill+'f',slot+2)}.`}
function recentMissionTexts(){const today=todayKey();return new Set(Object.entries(state.missions.daily||{}).filter(([k])=>k<today).sort(([a],[b])=>b.localeCompare(a)).slice(0,7).flatMap(([,d])=>(d.items||[]).map(x=>x.text)))}
function newSystemMission(skill,k,i,nonce=0){const recent=recentMissionTexts();let text='';for(let n=0;n<12;n++){text=g30MissionText(skill,k,i+nonce+n);if(!recent.has(text))break}return{id:`${k}:${i}:${skill}:${nonce}`,skill,attr:attrForSkill(skill),text,xp:i===0?6:5,done:false,variant:nonce}}
function ensureDailyMissions(){const k=todayKey();if(state.missions.daily[k])return state.missions.daily[k];const sorted=weakestSkills(),picked=[],attrs=new Set(),focus=state.improvementPlan?.focusSkills||[];for(const s of [...focus,...sorted]){if(picked.includes(s))continue;const a=attrForSkill(s);if(!attrs.has(a)||picked.length>=2){picked.push(s);attrs.add(a)}if(picked.length===3)break}while(picked.length<3)picked.push(sorted[picked.length]);const items=picked.map((skill,i)=>newSystemMission(skill,k,i,0));state.missions.daily[k]={createdAt:new Date().toISOString(),items,engine:'G30'};localStorage.setItem(storeKey,JSON.stringify(state));return state.missions.daily[k]}
function replaceSystemMission(id){const daily=ensureDailyMissions(),idx=daily.items.findIndex(x=>x.id===id);if(idx<0)return;const old=daily.items[idx];if(old.done)return toast('Una misión completada ya no se recalibra.','warn');const nonce=(old.variant||0)+1;daily.items[idx]=newSystemMission(old.skill,todayKey(),idx,nonce);localStorage.setItem(storeKey,JSON.stringify(state));renderMissionsPage();toast('Misión reemplazada por una alternativa que apunta a la misma habilidad.','good')}
function ensureWeeklyBoss(){const wk=mondayKey();if(state.missions.weekly[wk])return state.missions.weekly[wk];const attrs=effectiveAttributes(),attr=Object.entries(attrs).sort((a,b)=>a[1]-b[1])[0][0];state.missions.weekly[wk]={week:wk,attr,target:4,reward:20,claimed:false,title:`Boss de ${attr}`,description:`Completá 4 Misiones del Sistema de ${attr} durante esta semana.`};localStorage.setItem(storeKey,JSON.stringify(state));return state.missions.weekly[wk]}
function bossProgress(boss){const start=new Date(boss.week+'T12:00:00'),end=new Date(start);end.setDate(end.getDate()+6);let done=0;Object.entries(state.missions.daily).forEach(([k,d])=>{const dt=new Date(k+'T12:00:00');if(dt>=start&&dt<=end)done+=(d.items||[]).filter(m=>m.attr===boss.attr&&m.done).length});return done}
function toggleSystemMission(id,done){const daily=ensureDailyMissions(),m=daily.items.find(x=>x.id===id);if(!m||m.done===done)return;m.done=done;m.doneAt=done?new Date().toISOString():null;const day=getDay(),eventId=`system:${id}`;day.events=day.events||[];if(done){if(!day.events.some(e=>e.id===eventId))day.events.push({id:eventId,type:'system-mission',text:`Misión: ${m.text}`,skill:m.skill,xp:m.xp});state.evidenceLog.push({date:todayKey(),skill:m.skill,source:'system-mission',value:1}) ;playTone('reward');toast(`Misión completada · +${m.xp} XP`,'good')}else{day.events=day.events.filter(e=>e.id!==eventId);state.evidenceLog=state.evidenceLog.filter(e=>!(e.date===todayKey()&&e.skill===m.skill&&e.source==='system-mission'))}persist(false);snapshotToday();renderMissionsPage();if(page==='home')renderHome()}
function claimBoss(){const boss=ensureWeeklyBoss(),p=bossProgress(boss);if(boss.claimed)return toast('La recompensa semanal ya fue reclamada.');if(p<boss.target)return toast(`Faltan ${boss.target-p} misiones de ${boss.attr}.`,'warn');boss.claimed=true;const d=getDay(),id=`boss:${boss.week}`;if(!d.events.some(e=>e.id===id))d.events.push({id,type:'boss',text:`Boss semanal: ${boss.attr}`,xp:boss.reward,skill:null});persist(false);playTone('level');toast(`Boss derrotado · +${boss.reward} XP`,'good');renderMissionsPage()}
function claimChest(){const k=todayKey(),daily=ensureDailyMissions(),completed=daily.items.filter(x=>x.done).length,box=state.missions.chests[k]||(state.missions.chests[k]={claimed:false});if(box.claimed)return toast('El cofre de hoy ya está abierto.');if(completed<3)return toast('Completá las 3 misiones diarias para abrirlo.','warn');box.claimed=true;box.claimedAt=new Date().toISOString();const d=getDay(),id=`chest:${k}`;if(!d.events.some(e=>e.id===id))d.events.push({id,type:'chest',text:'Cofre diario',xp:8});persist(false);playTone('reward');toast('Cofre abierto · +8 XP · marco cian desbloqueado','good');renderMissionsPage()}
function renderMissionsPage(){if(page!=='missions')return;const daily=ensureDailyMissions(),done=daily.items.filter(x=>x.done).length,cl=characterLevelData();$('#missionCharacterLevel').textContent=cl.level;$('#missionCharacterXp').textContent=`${cl.xp} XP`;$('#dailyMissionCount').textContent=`${done}/3`;const weak=weakestSkills()[0];$('#missionIntro').textContent=`El Sistema detecta ${weak} como una de tus habilidades con menor evidencia actual. Las misiones se recalculan cada día.`;$('#systemMissions').innerHTML=daily.items.map(m=>`<label class="system-mission ${m.done?'done':''}"><input type="checkbox" data-system-mission="${escapeHtml(m.id)}" ${m.done?'checked':''}><div><h3>${escapeHtml(m.text)}</h3><div class="mission-skill">${icons[m.attr]} ${m.skill}</div></div><div class="mission-actions"><span class="xp-badge">+${m.xp} XP</span>${m.done?'':`<button type="button" class="ghost mission-replace" data-replace-system-mission="${escapeHtml(m.id)}">↻ No aplica</button>`}</div></label>`).join('');const boss=ensureWeeklyBoss(),bp=bossProgress(boss);$('#bossTitle').textContent=boss.title;$('#bossDescription').textContent=boss.description;$('#bossBar').style.width=`${clamp(bp/boss.target*100)}%`;$('#bossProgressText').textContent=`${Math.min(bp,boss.target)}/${boss.target} misiones`;$('#claimBossBtn').disabled=boss.claimed||bp<boss.target;$('#claimBossBtn').textContent=boss.claimed?'Recompensa reclamada':bp>=boss.target?'Reclamar +20 XP':'Boss en progreso';const chest=state.missions.chests[todayKey()]||{claimed:false};$('#chestStatus').innerHTML=chest.claimed?'✨ <strong>Cofre abierto</strong>':done>=3?'🔓 <strong>Cofre listo para abrir</strong>':`🔒 ${done}/3 misiones`;$('#claimChestBtn').disabled=chest.claimed||done<3;$('#claimChestBtn').textContent=chest.claimed?'Abierto':done>=3?'Abrir cofre':'Bloqueado'}

// -------- RPG home / level / snapshots --------
function snapshotToday(){state.snapshots[todayKey()]={date:todayKey(),general:generalLevel(),attrs:effectiveAttributes(),characterXp:allCharacterXp(),weight:Number(state.dietLogs[todayKey()]?.weight)||Number(state.player.weight)||null,sleep:Number(getDay().checkin.sleepHours)||null,updatedAt:new Date().toISOString()};localStorage.setItem(storeKey,JSON.stringify(state))}
function maybeLevelUp(){const d=characterLevelData();if(state.rpg.lastSeenLevel==null){state.rpg.lastSeenLevel=d.level;localStorage.setItem(storeKey,JSON.stringify(state));return}if(d.level>state.rpg.lastSeenLevel){state.rpg.lastSeenLevel=d.level;localStorage.setItem(storeKey,JSON.stringify(state));const ov=$('#levelUpOverlay');if(ov){$('#levelUpNumber').textContent=d.level;const unlocked=titleDefs.find(x=>x[1]===d.level);$('#levelUpTitleText').textContent=unlocked?`Nuevo título desbloqueado: ${unlocked[0]}`:`Tu personaje alcanzó el nivel ${d.level}.`;ov.classList.remove('hidden');playTone('level')}}}
function renderBriefing(){if(page!=='home')return;const daily=ensureDailyMissions(),weak=weakestSkills()[0];if($('#systemBriefTitle'))$('#systemBriefTitle').textContent=`Objetivo: ${weak}`;if($('#systemBriefText'))$('#systemBriefText').textContent=`Hoy el Sistema te propone acciones pequeñas para producir evidencia real en ${weak} y otras áreas rezagadas.`;if($('#systemWeakSkill'))$('#systemWeakSkill').textContent=`${icons[attrForSkill(weak)]} ${weak}`;const k=todayKey();if(!state.rpg.briefingSeen[k]){const ov=$('#briefingOverlay');if(!ov)return;$('#briefingTitle').textContent=`${state.player.name||'Jugador'}, el Sistema te asignó 3 misiones`;$('#briefingText').textContent=`Tu habilidad prioritaria hoy es ${weak}. No necesitás un día perfecto: necesitás evidencia.`;$('#briefingMissions').innerHTML=daily.items.map(m=>`<div><strong>${icons[m.attr]} ${escapeHtml(m.skill)}</strong><br><span class="note">${escapeHtml(m.text)}</span></div>`).join('');ov.classList.remove('hidden')}}
const renderHomeV5=renderHome;
renderHome=function(){renderHomeV5();const c=characterLevelData();if($('#characterLevel'))$('#characterLevel').textContent=c.level;if($('#characterXpBar'))$('#characterXpBar').style.width=`${c.pct}%`;if($('#characterXpText'))$('#characterXpText').textContent=`${c.xp} XP total · ${c.current}/${c.needed} para nivel ${c.level+1}`;if($('#homeTitle'))$('#homeTitle').textContent=state.rpg.title;if($('#homeAvatarFrame'))$('#homeAvatarFrame').className=`avatar-frame ${frameClass()}`;renderBriefing();maybeLevelUp()}
const renderAchievementsV5=renderAchievements;
renderAchievements=function(){const el=$('#achievements');if(!el)return;const actions=allDoneTasks().length+allEvents().length,st=streaks(),gl=generalLevel(),xp=allCharacterXp(),lessons=Object.values(state.academyProgress).filter(x=>x.completed).length,bosses=Object.values(state.missions.weekly).filter(x=>x.claimed).length,certs=Object.values(state.academyCertifications).filter(x=>x.passed).length,cl=characterLevelData().level;const list=[['Primer paso','Completar 1 acción',actions>=1],['Cazador','Llegar a nivel de personaje 3',cl>=3],['Racha x7','Actividad 7 días seguidos',st.best>=7],['500 XP','Acumular 500 XP',xp>=500],['Boss hunter','Derrotar un boss semanal',bosses>=1],['Certificado','Aprobar una certificación',certs>=1],['Nivel de habilidades 70','Llegar a promedio 70',gl>=70],['Académico','Completar 15 lecciones',lessons>=15]];el.innerHTML=list.map(x=>`<div class="achievement ${x[2]?'':'locked'}"><strong>${x[2]?'🏆':'🔒'} ${x[0]}</strong><span class="note">${x[1]}</span></div>`).join('')}

// -------- Academy V6: levels, shuffled quizzes, certifications --------
const lessonLevels={
'nut-energia':'Básico','nut-macros':'Básico','nut-proteina':'Intermedio','nut-etiquetas':'Intermedio','nut-adherencia':'Avanzado',
'ent-adaptaciones':'Básico','ent-sobrecarga':'Básico','ent-volumen':'Intermedio','ent-recuperacion':'Intermedio','ent-consistencia':'Avanzado',
'trab-prioridades':'Básico','trab-comunicacion':'Básico','trab-feedback':'Intermedio','trab-problemas':'Intermedio','trab-sistemas':'Avanzado'};
function categoryLessons(cat){return academyLessons.filter(l=>l.category===cat)}function categoryDone(cat){return categoryLessons(cat).filter(l=>state.academyProgress[l.id]?.completed).length}
function lessonUnlocked(l){if(state.academyProgress[l.id]?.completed)return true;const lv=lessonLevels[l.id]||'Básico',done=categoryDone(l.category);if(lv==='Básico')return true;if(lv==='Intermedio')return done>=1;return done>=3}
function academyRecommendation(){const incomplete=academyLessons.filter(l=>!state.academyProgress[l.id]?.completed&&lessonUnlocked(l));if(!incomplete.length)return null;if(state.nutritionKnowledge<55){const n=incomplete.find(l=>l.category==='Nutrición');if(n)return n}const data=effectiveSkillData();return[...incomplete].sort((a,b)=>(data[a.skill]?.score??50)-(data[b.skill]?.score??50))[0]}
const renderAcademyV5=renderAcademy;
renderAcademy=function(){if(page!=='academy')return;const progress=state.academyProgress;$('#academyCompleted').textContent=Object.values(progress).filter(x=>x.completed).length;const today=academyCompletedToday(),allow=academyAllowance();$('#academyDailyText').textContent=state.monetization.premium?'Premium · lecciones ilimitadas':`${today}/${allow===Infinity?'∞':allow} lecciones nuevas usadas hoy`;$('#academyAccessPill').textContent=state.monetization.premium?'PREMIUM':'GRATIS';const rec=academyRecommendation();$('#academyRecommendation').innerHTML=rec?`<strong>Recomendación del Sistema:</strong> ${rec.icon} ${escapeHtml(rec.title)} · ${lessonLevels[rec.id]}<br><span class="note">Se prioriza por tu evaluación y habilidades actuales.</span>`:'<strong>Ruta actual completada.</strong> Próximamente se pueden sumar nuevas ramas avanzadas.';const list=academyFilter==='all'?academyLessons:academyLessons.filter(l=>l.category===academyFilter);$('#academyGrid').innerHTML=list.map(l=>{const done=progress[l.id]?.completed,gate=!lessonUnlocked(l),locked=!done&&!canCompleteLesson();return`<article class="lesson-card ${done?'completed':''} ${locked||gate?'locked':''} ${gate?'gated':''}" data-lesson="${l.id}"><div class="lesson-icon">${l.icon}</div><div><span class="eyebrow">${l.category}</span> <span class="lesson-level">${lessonLevels[l.id]||'Básico'}</span></div><h3>${escapeHtml(l.title)}</h3><p>${escapeHtml(l.summary)}</p><footer><span>${l.minutes} min · +${l.xp} XP</span><strong class="${locked||gate?'lock-note':''}">${done?'✓ completada':gate?'🔒 completá la ruta anterior':locked?'🔒 límite diario':'Abrir →'}</strong></footer></article>`}).join('');renderCertifications()}
openLesson=function(id){const l=academyLessons.find(x=>x.id===id);if(!l)return;if(!lessonUnlocked(l))return toast('Completá primero una lección anterior de esta ruta.','warn');if(!state.academyProgress[id]?.completed&&!canCompleteLesson())return openPaywall();const shuffled=shuffle(l.answers.map((label,i)=>({label,correct:i===l.correct})));currentLesson={...l,_answers:shuffled};$('#lessonOverlay').classList.remove('hidden');$('#lessonCategory').textContent=`${l.category} · ${lessonLevels[l.id]}`;$('#lessonTitle').textContent=l.title;$('#lessonBody').innerHTML=l.body.map(p=>`<p>${escapeHtml(p)}</p>`).join('');$('#lessonQuestion').textContent=l.question;$('#lessonAnswers').innerHTML=shuffled.map((a,i)=>`<button class="answer-btn" data-lesson-answer="${i}">${escapeHtml(a.label)}</button>`).join('');$('#lessonFeedback').className='quiz-feedback';$('#lessonFeedback').textContent=''}
answerLesson=function(i){if(!currentLesson)return;const fb=$('#lessonFeedback'),answer=currentLesson._answers?.[i];if(!answer?.correct){fb.className='quiz-feedback bad';fb.textContent='No es la mejor respuesta. Revisá la idea central y probá de nuevo.';return}if(state.academyProgress[currentLesson.id]?.completed){fb.className='quiz-feedback good';fb.textContent='Correcto. Ya habías completado esta lección, por eso no vuelve a sumar XP.';return}if(!canCompleteLesson()){closeLesson();openPaywall();return}state.academyProgress[currentLesson.id]={completed:true,completedAt:new Date().toISOString(),xp:currentLesson.xp};getDay().events.push({id:`academy:${currentLesson.id}`,type:'academy',text:`Lección: ${currentLesson.title}`,skill:currentLesson.skill,xp:currentLesson.xp});persist(false);playTone('reward');fb.className='quiz-feedback good';fb.textContent=`Correcto. +${currentLesson.xp} XP de entrenamiento en ${currentLesson.skill}.`;renderAcademy();snapshotToday()}
let examSession=null;
function renderCertifications(){const el=$('#certificationsGrid');if(!el)return;const cats=['Nutrición','Entrenamiento','Trabajo'];el.innerHTML=cats.map(cat=>{const c=state.academyCertifications[cat],done=categoryDone(cat),ready=done===categoryLessons(cat).length;return`<article class="cert-card ${c?.passed?'passed':''}"><div class="cert-badge">${c?.passed?'🏅':'📜'}</div><strong>${cat}</strong><p class="note">${c?.passed?`Aprobado · ${c.score}/5`:ready?'Ruta completa · examen disponible':`${done}/5 lecciones completadas`}</p><button class="${c?.passed?'ghost':'primary'} wide small-btn" data-cert-exam="${cat}" ${!ready?'disabled':''}>${c?.passed?'Repetir examen':'Rendir examen'}</button></article>`}).join('')}
function startExam(cat){const lessons=categoryLessons(cat);if(categoryDone(cat)<lessons.length)return;examSession={cat,index:0,score:0,questions:shuffle(lessons).map(l=>{const opts=shuffle(l.answers.map((label,i)=>({label,correct:i===l.correct})));return{text:l.question,options:opts}})};$('#examOverlay').classList.remove('hidden');$('#examTitle').textContent=`Certificación · ${cat}`;renderExamQuestion()}
function renderExamQuestion(){const q=examSession.questions[examSession.index];$('#examProgressBar').style.width=`${examSession.index/examSession.questions.length*100}%`;$('#examQuestion').textContent=q.text;$('#examAnswers').innerHTML=q.options.map((o,i)=>`<button class="answer-btn" data-exam-answer="${i}">${escapeHtml(o.label)}</button>`).join('');$('#examFeedback').className='quiz-feedback';$('#examFeedback').textContent=''}
function answerExam(i){const q=examSession.questions[examSession.index];if(q.options[i]?.correct)examSession.score++;examSession.index++;if(examSession.index<examSession.questions.length)return renderExamQuestion();const passed=examSession.score>=4,cat=examSession.cat;$('#examProgressBar').style.width='100%';$('#examAnswers').innerHTML='';$('#examQuestion').textContent=passed?`Aprobaste ${examSession.score}/5.`:`Resultado ${examSession.score}/5. Necesitás 4/5 para certificar.`;if(passed){const skills=categoryLessons(cat).map(l=>l.skill);const first=!state.academyCertifications[cat]?.passed;state.academyCertifications[cat]={passed:true,score:examSession.score,passedAt:new Date().toISOString(),skills};if(first)getDay().events.push({id:`cert:${cat}`,type:'certification',text:`Certificación: ${cat}`,skill:skills[0],xp:15});persist(false);playTone('level');$('#examFeedback').className='quiz-feedback good';$('#examFeedback').textContent=first?'Certificación desbloqueada · +15 XP.':'Certificación mantenida.'}else{$('#examFeedback').className='quiz-feedback bad';$('#examFeedback').textContent='Podés revisar las lecciones y volver a intentarlo.'}renderCertifications()}

// -------- Diet V6 tracking & adaptive adjustment --------
const nutritionTargetsV5=nutritionTargets;
nutritionTargets=function(p){const t=nutritionTargetsV5(p);if(t.error)return t;const adj=Number(p.manualCalorieAdjustment)||0;if(!adj)return t;const calories=Math.max(1200,t.calories+adj),protein=t.protein,fat=t.fat,carbs=Math.max(70,Math.round((calories-protein*4-fat*9)/4));return{...t,calories,carbs,manualAdjustment:adj}}
const renderDietResultsV5=renderDietResults;
renderDietResults=function(plan){renderDietResultsV5(plan);renderDietTracker()}
const renderDietProfileV5=renderDietProfile;
renderDietProfile=function(){renderDietProfileV5();renderDietTracker();renderDietAdaptiveStatus()}
function planDayIndex(){if(!state.dietPlan?.createdAt)return 0;const start=new Date(dateKeyFromIso(state.dietPlan.createdAt)+'T12:00:00'),now=new Date(todayKey()+'T12:00:00'),diff=Math.max(0,Math.round((now-start)/86400000));return diff%7}
function recalcDayTotals(day){day.totals={kcal:day.meals.reduce((s,m)=>s+m.kcal,0),p:day.meals.reduce((s,m)=>s+m.p,0),c:day.meals.reduce((s,m)=>s+m.c,0),f:day.meals.reduce((s,m)=>s+m.f,0),fiber:day.meals.reduce((s,m)=>s+m.fiber,0)}}
function renderDietTracker(){const el=$('#dietTracker');if(!el)return;const plan=state.dietPlan;if(!plan||plan.error){el.classList.add('hidden');return}el.classList.remove('hidden');const di=planDayIndex(),day=plan.days[di],k=todayKey(),log=state.dietLogs[k]||(state.dietLogs[k]={meals:{}});log.meals=log.meals||{};const done=day.meals.filter((m,i)=>log.meals[`${di}:${i}`]).length,ad=day.meals.length?done/day.meals.length:0;log.adherence=ad;$('#dietTodayTitle').textContent=`Día ${di+1} del plan · ${done}/${day.meals.length} comidas` ;$('#dietAdherencePill').textContent=`${Math.round(ad*100)}%`;$('#dietTodayMeals').innerHTML=day.meals.map((m,i)=>{const checked=!!log.meals[`${di}:${i}`];return`<div class="meal-track ${checked?'done':''}"><input type="checkbox" data-diet-meal="${di}:${i}" ${checked?'checked':''}><div><h4>${escapeHtml(m.name)}</h4><div class="note">${m.kcal} kcal · P ${m.p} g · C ${m.c} g · G ${m.f} g</div></div><button class="ghost swap-meal" data-swap-meal="${di}:${i}">Cambiar</button></div>`}).join('');const eaten=day.meals.filter((m,i)=>log.meals[`${di}:${i}`]),tot={kcal:eaten.reduce((s,m)=>s+m.kcal,0),p:eaten.reduce((s,m)=>s+m.p,0),c:eaten.reduce((s,m)=>s+m.c,0),f:eaten.reduce((s,m)=>s+m.f,0)};$('#dietConsumedMacros').innerHTML=[['Plan marcado',`${tot.kcal}/${plan.targets.calories} kcal`],['Proteína',`${tot.p}/${plan.targets.protein} g`],['Carbos',`${tot.c}/${plan.targets.carbs} g`],['Grasas',`${tot.f}/${plan.targets.fat} g`]].map(x=>`<div class="macro-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#dietLogWeight').value=log.weight??'';$('#dietLogHunger').value=log.hunger??'';$('#dietLogEnergy').value=log.energy??'';$('#dietLogPerformance').value=log.performance??'';renderDietTrendAdvice()}
function swapMeal(di,mi){const plan=state.dietPlan,day=plan.days[di],old=day.meals[mi],cands=dietCandidates(old.type,state.dietProfile).filter(x=>x.name!==old.name);if(!cands.length)return toast('No hay otra opción compatible con tus exclusiones.','warn');const target=old.kcal,base=[...cands].sort((a,b)=>Math.abs(a.kcal-target)-Math.abs(b.kcal-target))[seededIndex(todayKey()+mi,Math.min(3,cands.length))],scale=old.scale||1,repl={...base,scale,kcal:Math.round(base.kcal*scale),p:Math.round(base.p*scale),c:Math.round(base.c*scale),f:Math.round(base.f*scale),fiber:Math.round(base.fiber*scale)};day.meals[mi]=repl;recalcDayTotals(day);persist(false);toast('Comida cambiada manteniendo una referencia similar de macros.','good');renderDietResults(state.dietPlan)}
function weightTrend(){const e=Object.entries(state.dietLogs||{}).filter(([,l])=>Number(l.weight)>0).sort(([a],[b])=>a.localeCompare(b));if(e.length<8)return null;const firstDate=new Date(e[0][0]+'T12:00:00'),lastDate=new Date(e[e.length-1][0]+'T12:00:00'),days=(lastDate-firstDate)/86400000;if(days<13)return null;const n=Math.max(3,Math.floor(e.length/3)),first=e.slice(0,n).reduce((s,[,l])=>s+Number(l.weight),0)/n,last=e.slice(-n).reduce((s,[,l])=>s+Number(l.weight),0)/n,weeks=days/7,kgWeek=(last-first)/weeks,pctWeek=kgWeek/first*100;return{first,last,kgWeek,pctWeek,days,n:e.length}}
function dietAdjustmentSuggestion(){const tr=weightTrend(),p=state.dietProfile;if(!tr)return null;let adj=0,reason='';if(p.goal==='lose'){if(tr.pctWeek>-0.12){adj=-100;reason='El peso promedio casi no bajó durante al menos dos semanas.'}else if(tr.pctWeek<-1.15){adj=100;reason='La tendencia de peso está bajando bastante rápido.'}}else if(p.goal==='gain'){if(tr.pctWeek<.05){adj=100;reason='La tendencia de peso casi no subió.'}else if(tr.pctWeek>.65){adj=-100;reason='La tendencia está subiendo más rápido de lo previsto.'}}else{if(tr.pctWeek>.45){adj=-100;reason='El promedio está subiendo en mantenimiento.'}else if(tr.pctWeek<-.45){adj=100;reason='El promedio está bajando en mantenimiento.'}}return adj?{adj,reason,tr}:null}
function renderDietTrendAdvice(){const el=$('#dietTrendAdvice');if(!el)return;const s=dietAdjustmentSuggestion();if(!s){const tr=weightTrend();el.innerHTML=tr?`<strong>Tendencia disponible</strong><br><span class="note">${tr.kgWeek>=0?'+':''}${tr.kgWeek.toFixed(2)} kg/semana aprox. No hace falta ajustar automáticamente por ahora.</span>`:`<strong>Calibración pendiente</strong><br><span class="note">Registrá peso durante al menos 2 semanas. La app usa promedios, no cambios de un solo día.</span>`;return}el.innerHTML=`<strong>Sugerencia de recalibración: ${s.adj>0?'+':''}${s.adj} kcal/día</strong><br><span class="note">${escapeHtml(s.reason)} Tendencia: ${s.tr.kgWeek>=0?'+':''}${s.tr.kgWeek.toFixed(2)} kg/semana. Revisá también hambre, energía y rendimiento.</span><br><button id="applyDietAdjustment" class="ghost small-btn section-space">Aplicar ajuste</button>`;$('#applyDietAdjustment')?.addEventListener('click',()=>{state.dietProfile.manualCalorieAdjustment=(Number(state.dietProfile.manualCalorieAdjustment)||0)+s.adj;state.dietPlan=generateDiet(state.dietProfile);persist(false);renderDietProfile();toast(`Ajuste aplicado: ${s.adj>0?'+':''}${s.adj} kcal/día`,'good')})}
function renderDietAdaptiveStatus(){const el=$('#dietAdaptiveStatus');if(!el)return;const adj=Number(state.dietProfile.manualCalorieAdjustment)||0;el.innerHTML=`<strong>Calibración del plan</strong><br><span class="note">Ajuste acumulado respecto de la estimación inicial: ${adj>0?'+':''}${adj} kcal/día. La app sólo sugiere cambios después de reunir tendencia suficiente.</span>`}

// -------- Progress dashboard --------
function lastNDates(n){const out=[],d=new Date();d.setHours(12,0,0,0);for(let i=n-1;i>=0;i--){const x=new Date(d);x.setDate(x.getDate()-i);out.push(dateKey(x))}return out}
function lineSvg(values,{min=null,max=null,suffix=''}={}){const valid=values.filter(v=>Number.isFinite(v));if(valid.length<2)return'<div class="chart-empty">Todavía no hay suficientes datos.</div>';const lo=min??Math.min(...valid),hi=max??Math.max(...valid),span=Math.max(1,hi-lo),w=520,h=190,pad=22;const pts=values.map((v,i)=>{if(!Number.isFinite(v))return null;const x=pad+i*(w-pad*2)/(values.length-1),y=h-pad-(v-lo)/span*(h-pad*2);return{x,y,v}});const chunks=[];let cur=[];pts.forEach(p=>{if(p)cur.push(p);else if(cur.length){chunks.push(cur);cur=[]}});if(cur.length)chunks.push(cur);const paths=chunks.map(c=>`<polyline class="chart-line" points="${c.map(p=>`${p.x},${p.y}`).join(' ')}"/>`).join('');const dots=pts.filter(Boolean).filter((_,i,a)=>i===a.length-1||i===0).map(p=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="4"/><text class="chart-label" x="${p.x}" y="${p.y-8}" text-anchor="middle">${Number(p.v).toFixed(p.v%1?1:0)}${suffix}</text>`).join('');return`<svg class="chart-svg" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line class="chart-axis" x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}"/>${paths}${dots}</svg>`}
function avg(a){const v=a.filter(Number.isFinite);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null}
function systemInsights(){const keys=lastNDates(14),last7=keys.slice(7),prev7=keys.slice(0,7),sleep=k=>Number(state.days[k]?.checkin?.sleepHours),completion=k=>{const t=state.days[k]?.tasks||[];return t.length?t.filter(x=>x.done).length/t.length:null};const s1=avg(last7.map(sleep)),s0=avg(prev7.map(sleep)),c1=avg(last7.map(completion)),c0=avg(prev7.map(completion)),weak=weakestSkills()[0],ins=[];ins.push({type:'',title:`Prioridad: ${weak}`,text:`Es una de las habilidades con menor evidencia actual. Las misiones diarias la priorizan sin regalar nivel por XP.`});if(s1!=null){if(s0!=null&&s1<s0-.5)ins.push({type:'warn',title:'Sueño en descenso',text:`Promedio últimos 7 días: ${s1.toFixed(1)} h, frente a ${s0.toFixed(1)} h la semana anterior.`});else if(s1>=7)ins.push({type:'good',title:'Sueño consistente',text:`Promedio de ${s1.toFixed(1)} h durante los últimos 7 días.`});else ins.push({type:'warn',title:'Sueño para observar',text:`Promedio de ${s1.toFixed(1)} h durante los últimos 7 días.`})}if(c1!=null){const d=c0!=null?(c1-c0)*100:null;ins.push({type:c1>=.7?'good':'',title:'Cumplimiento semanal',text:`${Math.round(c1*100)}% de tareas completadas${d!=null?` · ${d>=0?'+':''}${Math.round(d)} puntos vs. semana anterior`:''}.`})}const da=dietAdherenceRecent(7);if(da!=null)ins.push({type:da>=.75?'good':'',title:'Adherencia del dietario',text:`Marcaste aproximadamente ${Math.round(da*100)}% de las comidas planificadas en los registros recientes.`});return ins.slice(0,5)}
function renderProgressPage(){if(page!=='progress')return;const dates=lastNDates(30),cl=characterLevelData();$('#progressCharacterLevel').textContent=cl.level;$('#progressCharacterXp').textContent=`${cl.xp} XP`;$('#progressWeekXp').textContent=dates.slice(-7).reduce((s,k)=>s+(state.days[k]?dayXp(state.days[k]):0),0);const comp=avg(dates.slice(-7).map(k=>{const t=state.days[k]?.tasks||[];return t.length?t.filter(x=>x.done).length/t.length:null}));$('#progressCompletion').textContent=comp==null?'—':`${Math.round(comp*100)}%`;const sl=avg(dates.slice(-7).map(k=>Number(state.days[k]?.checkin?.sleepHours)||null));$('#progressSleep').textContent=sl==null?'—':`${sl.toFixed(1)} h`;const da=dietAdherenceRecent(7);$('#progressDiet').textContent=da==null?'—':`${Math.round(da*100)}%`;$('#xpChart').innerHTML=lineSvg(dates.map(k=>state.days[k]?dayXp(state.days[k]):0),{min:0});$('#sleepChart').innerHTML=lineSvg(dates.map(k=>Number(state.days[k]?.checkin?.sleepHours)||null),{min:4,max:10,suffix:'h'});$('#weightChart').innerHTML=lineSvg(dates.map(k=>Number(state.dietLogs[k]?.weight)||null),{});$('#levelChart').innerHTML=lineSvg(dates.map(k=>Number(state.snapshots[k]?.general)||null),{min:0,max:100});$('#systemInsights').innerHTML=systemInsights().map(i=>`<article class="insight ${i.type}"><strong>${escapeHtml(i.title)}</strong><p>${escapeHtml(i.text)}</p></article>`).join('')}

// -------- Profile cosmetics --------
const renderProfileV5=renderProfile;
renderProfile=function(){renderProfileV5();if($('#profileTitleSelect')){$('#profileTitleSelect').innerHTML=unlockedTitles().map(t=>`<option ${t===state.rpg.title?'selected':''}>${escapeHtml(t)}</option>`).join('');$('#profileFrameSelect').innerHTML=unlockedFrames().map(([v,l])=>`<option value="${v}" ${v===state.rpg.frame?'selected':''}>${l}</option>`).join('');$('#profileAvatarFrame').className=`avatar-frame ${frameClass()}`}}

// -------- Account / cloud / backup --------
function cloudConfigured(){return /^https:\/\//.test(cfg.supabaseUrl||'')&&String(cfg.supabaseAnonKey||'').length>20}
function cloudHeaders(token=state.cloud.accessToken){return{'Content-Type':'application/json','apikey':cfg.supabaseAnonKey,'Authorization':`Bearer ${token||cfg.supabaseAnonKey}`}}
function sanitizedState(){const c=structuredClone(state);if(c.cloud){c.cloud.accessToken='';c.cloud.refreshToken=''}return c}
async function cloudAuth(mode){if(!cloudConfigured())throw new Error('Primero configurá Supabase en config.js.');const email=$('#cloudEmail').value.trim(),password=$('#cloudPassword').value;if(!email||password.length<6)throw new Error('Ingresá email y una contraseña de al menos 6 caracteres.');const url=mode==='signup'?`${cfg.supabaseUrl}/auth/v1/signup`:`${cfg.supabaseUrl}/auth/v1/token?grant_type=password`;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.supabaseAnonKey},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||data.message||'No se pudo autenticar.');const session=data.access_token?data:data.session;if(session?.access_token){state.cloud={email,userId:(data.user||session.user)?.id||'',accessToken:session.access_token,refreshToken:session.refresh_token||''};persist(false);return true}state.cloud.email=email;persist(false);toast('Cuenta creada. Revisá tu email si Supabase requiere confirmación.','good');return false}
async function cloudPush(){if(!cloudConfigured()||!state.cloud.userId||!state.cloud.accessToken)throw new Error('Iniciá sesión antes de sincronizar.');const row={user_id:state.cloud.userId,state:sanitizedState(),updated_at:new Date().toISOString()};const r=await fetch(`${cfg.supabaseUrl}/rest/v1/vida_rpg_profiles?on_conflict=user_id`,{method:'POST',headers:{...cloudHeaders(),'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error(await r.text()||'No se pudo subir el estado.');return true}
async function cloudPull(){if(!cloudConfigured()||!state.cloud.userId||!state.cloud.accessToken)throw new Error('Iniciá sesión antes de descargar.');const r=await fetch(`${cfg.supabaseUrl}/rest/v1/vida_rpg_profiles?user_id=eq.${encodeURIComponent(state.cloud.userId)}&select=state,updated_at`,{headers:cloudHeaders()});if(!r.ok)throw new Error(await r.text()||'No se pudo descargar.');const rows=await r.json();if(!rows.length)throw new Error('Todavía no hay un backup en la nube.');const cloud=state.cloud;state=mergeState(rows[0].state||{});ensureV6State();state.cloud=cloud;persist(false);location.reload()}
function exportData(){const blob=new Blob([JSON.stringify(sanitizedState(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`vida-rpg-backup-${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function renderAccountPage(){if(page!=='account')return;const configured=cloudConfigured(),signed=!!state.cloud.userId&&!!state.cloud.accessToken;$('#cloudStatusTitle').textContent=signed?'Cuenta conectada':'Modo local';$('#cloudStatusText').textContent=signed?`${state.cloud.email||'Usuario'} · podés subir o recuperar tu estado.`:'Tus datos permanecen en este navegador hasta que conectes un proveedor de nube.';$('#cloudSetupMessage').innerHTML=configured?'<strong>Supabase configurado.</strong><br><span class="note">Podés crear cuenta o iniciar sesión.</span>':'<strong>Nube preparada, todavía sin credenciales.</strong><br><span class="note">Completá supabaseUrl y supabaseAnonKey en config.js y ejecutá SUPABASE_SETUP.sql una vez en tu proyecto.</span>';$('#cloudAuthForm').classList.toggle('hidden',signed);$('#cloudPushBtn').disabled=!signed;$('#cloudPullBtn').disabled=!signed;$('#cloudSignOutBtn').disabled=!signed;$('#premiumStatus').innerHTML=state.monetization.premium?'<strong>👑 Premium activo</strong><div class="note">Academia sin límite diario.</div>':'<strong>Plan gratuito</strong><div class="note">2 lecciones nuevas por día.</div>';const bytes=new Blob([JSON.stringify(state)]).size;$('#storageUsage').textContent=`Estado local aproximado: ${(bytes/1024).toFixed(1)} KB · dispositivo actual.`}

// -------- Monetization adapters (no fake rewards) --------
async function tryRewardedAd(){const m=$('#monetizationMessage');try{if(!window.VIDA_RPG_REWARDED_AD?.show)throw new Error('Todavía no hay un proveedor de video recompensado conectado.');const rewarded=await window.VIDA_RPG_REWARDED_AD.show();if(!rewarded)throw new Error('El proveedor no confirmó la recompensa.');state.monetization.bonusLessons[todayKey()]=(state.monetization.bonusLessons[todayKey()]||0)+1;persist(false);closePaywall();renderAcademy();toast('Video confirmado · +1 lección hoy','good')}catch(e){if(m){m.className='quiz-feedback bad';m.textContent=e.message}}}
function openPremium(){if(state.monetization.premium)return toast('Premium ya está activo.');if(cfg.premiumCheckoutUrl){location.href=cfg.premiumCheckoutUrl;return}const m=$('#monetizationMessage')||$('#cloudMessage');if(m){m.className='quiz-feedback bad';m.textContent='Falta conectar la URL/proveedor de cobro en config.js.'}else toast('Falta conectar un proveedor de cobro.','warn')}

// -------- Page lifecycle / bindings --------
const renderPageV5=renderPage;
renderPage=function(){renderPageV5();if(page==='missions')renderMissionsPage();if(page==='progress')renderProgressPage();if(page==='account')renderAccountPage();if(page!=='assessment'&&state.assessmentComplete)snapshotToday()}

function bindV6(){
  if(page==='home'){$('#acceptBriefingBtn')?.addEventListener('click',()=>{state.rpg.briefingSeen[todayKey()]=true;persist(false);$('#briefingOverlay').classList.add('hidden');playTone('click')});$('#closeLevelUpBtn')?.addEventListener('click',()=>$('#levelUpOverlay').classList.add('hidden'))}
  if(page==='missions'){$('#systemMissions')?.addEventListener('change',e=>{if(e.target.dataset.systemMission)toggleSystemMission(e.target.dataset.systemMission,e.target.checked)});$('#systemMissions')?.addEventListener('click',e=>{const b=e.target.closest('[data-replace-system-mission]');if(b){e.preventDefault();replaceSystemMission(b.dataset.replaceSystemMission)}});$('#claimBossBtn')?.addEventListener('click',claimBoss);$('#claimChestBtn')?.addEventListener('click',claimChest)}
  if(page==='academy'){$('#certificationsGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-cert-exam]');if(b)startExam(b.dataset.certExam)});$('#examAnswers')?.addEventListener('click',e=>{const b=e.target.closest('[data-exam-answer]');if(b)answerExam(+b.dataset.examAnswer)});$('#closeExamBtn')?.addEventListener('click',()=>$('#examOverlay').classList.add('hidden'));const ad=$('#adUnlockBtn');if(ad){const c=ad.cloneNode(true);ad.replaceWith(c);c.addEventListener('click',tryRewardedAd)}const pr=$('#premiumBtn');if(pr){const c=pr.cloneNode(true);pr.replaceWith(c);c.addEventListener('click',openPremium)}}
  if(page==='diet'){$('#dietTodayMeals')?.addEventListener('change',e=>{if(e.target.dataset.dietMeal){const log=state.dietLogs[todayKey()]||(state.dietLogs[todayKey()]={meals:{}});log.meals=log.meals||{};log.meals[e.target.dataset.dietMeal]=e.target.checked;persist(false);renderDietTracker();snapshotToday()}});$('#dietTodayMeals')?.addEventListener('click',e=>{const b=e.target.closest('[data-swap-meal]');if(b){const[di,mi]=b.dataset.swapMeal.split(':').map(Number);swapMeal(di,mi)}});$('#dietLogForm')?.addEventListener('submit',e=>{e.preventDefault();const log=state.dietLogs[todayKey()]||(state.dietLogs[todayKey()]={meals:{}});log.weight=+$('#dietLogWeight').value||null;log.hunger=+$('#dietLogHunger').value||null;log.energy=+$('#dietLogEnergy').value||null;log.performance=+$('#dietLogPerformance').value||null;log.savedAt=new Date().toISOString();persist(false);renderDietTracker();snapshotToday();toast('Seguimiento nutricional guardado.','good')})}
  if(page==='profile'){$('#profileTitleSelect')?.addEventListener('change',e=>{state.rpg.title=e.target.value;persist(false);renderProfile()});$('#profileFrameSelect')?.addEventListener('change',e=>{state.rpg.frame=e.target.value;persist(false);renderProfile()})}
  if(page==='account'){$('#cloudSignInBtn')?.addEventListener('click',async()=>{const m=$('#cloudMessage');try{m.textContent='Conectando...';await cloudAuth('signin');m.className='quiz-feedback good';m.textContent='Sesión iniciada.';renderAccountPage()}catch(e){m.className='quiz-feedback bad';m.textContent=e.message}});$('#cloudSignUpBtn')?.addEventListener('click',async()=>{const m=$('#cloudMessage');try{m.textContent='Creando cuenta...';await cloudAuth('signup');m.className='quiz-feedback good';m.textContent='Solicitud enviada.';renderAccountPage()}catch(e){m.className='quiz-feedback bad';m.textContent=e.message}});$('#cloudPushBtn')?.addEventListener('click',async()=>{const m=$('#cloudMessage');try{m.textContent='Subiendo...';await cloudPush();m.className='quiz-feedback good';m.textContent='Backup subido a la nube.'}catch(e){m.className='quiz-feedback bad';m.textContent=e.message}});$('#cloudPullBtn')?.addEventListener('click',async()=>{const m=$('#cloudMessage');try{m.textContent='Descargando...';await cloudPull()}catch(e){m.className='quiz-feedback bad';m.textContent=e.message}});$('#cloudSignOutBtn')?.addEventListener('click',()=>{state.cloud={email:'',userId:'',accessToken:'',refreshToken:''};persist(false);renderAccountPage()});$('#exportDataBtn')?.addEventListener('click',exportData);$('#importDataInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const parsed=JSON.parse(await f.text());if(!confirm('Esto reemplazará los datos locales actuales. ¿Continuar?'))return;state=mergeState(parsed);ensureV6State();persist(false);location.reload()}catch(err){toast('El archivo no parece ser un backup válido.','warn')}});$('#deleteDataBtn')?.addEventListener('click',()=>{if(!confirm('¿Eliminar TODOS los datos locales de Vida RPG en este navegador?'))return;[storeKey,v6Key,v5Key,v4Key,v3Key,v2Key,v1Key].forEach(k=>localStorage.removeItem(k));location.href='assessment.html'});$('#accountPremiumBtn')?.addEventListener('click',openPremium)}
}
function pageTransitions(){document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||a.target||e.ctrlKey||e.metaKey||e.shiftKey)return;const href=a.getAttribute('href');if(!href||href.startsWith('#')||href.startsWith('http')||href.startsWith('mailto:'))return;e.preventDefault();document.body.classList.add('page-exit');playTone('click');setTimeout(()=>location.href=href,140)})}

if(page!=='assessment'&&state.assessmentComplete){ensureDailyMissions();ensureWeeklyBoss();snapshotToday()}
// initial V6 lastSeenLevel avoids a fake "level up" from migrated historical XP
if(state.rpg.lastSeenLevel==null){state.rpg.lastSeenLevel=characterLevelData().level;localStorage.setItem(storeKey,JSON.stringify(state))}
renderPage();bindV6();pageTransitions();
})();
