(()=>{
const cfg7=window.VIDA_RPG_CONFIG||{};

// ---------- State ----------
function ensureV7State(){
  state.version=7;
  state.improvementPlan=state.improvementPlan||{};
  state.improvementPlan.profile=state.improvementPlan.profile||{workType:'employee',area:'operations',role:'individual',teamSize:0,responsibilities:[],workdays:[1,2,3,4,5],bottleneck:'organization',minutes:30,recurringTasks:[],goalText:''};
  state.improvementPlan.focusSkills=state.improvementPlan.focusSkills||[];
  state.improvementPlan.acceptedDays=state.improvementPlan.acceptedDays||{};
  state.improvementPlan.protectedDays=state.improvementPlan.protectedDays||{};
  state.improvementPlan.questionnaireComplete=!!state.improvementPlan.questionnaireComplete;
  state.penalties=state.penalties||{processed:{},active:{},shields:0,settings:{enabled:true,mode:'normal'},lastShown:''};
  state.penalties.processed=state.penalties.processed||{};state.penalties.active=state.penalties.active||{};state.penalties.settings=state.penalties.settings||{enabled:true,mode:'normal'};state.penalties.shields=Number(state.penalties.shields)||0;
  state.economy=state.economy||{coins:0,lifetimeEarned:0,lifetimeSpent:0,ledger:[],ownedThemes:['eclipse'],welcomeGift:false};
  state.economy.ledger=state.economy.ledger||[];state.economy.ownedThemes=state.economy.ownedThemes||['eclipse'];state.economy.coins=Number(state.economy.coins)||0;
  state.rpg=state.rpg||{};state.rpg.theme=state.rpg.theme||'eclipse';state.rpg.sound=state.rpg.sound!==false;
  state.combat=state.combat||{rating:1000,wins:0,losses:0,history:[],trainingRewards:{}};state.combat.history=state.combat.history||[];state.combat.trainingRewards=state.combat.trainingRewards||{};
  if(!state.economy.welcomeGift){state.economy.welcomeGift=true;ledgerChange(100,'Bono de despertar V7','v7-welcome',false)}
  localStorage.setItem(storeKey,JSON.stringify(state));
}
function hasLedgerKey(key){return !!state.economy?.ledger?.some(x=>x.key===key)}
function ledgerChange(delta,reason,key,save=true){ensureEconomyBare();if(key&&hasLedgerKey(key))return false;const before=state.economy.coins;const actual=delta<0?-Math.min(before,Math.abs(delta)):delta;state.economy.coins=Math.max(0,before+actual);if(actual>0)state.economy.lifetimeEarned=(state.economy.lifetimeEarned||0)+actual;if(actual<0)state.economy.lifetimeSpent=(state.economy.lifetimeSpent||0)+Math.abs(actual);state.economy.ledger.unshift({id:crypto.randomUUID(),key:key||crypto.randomUUID(),delta:actual,reason,at:new Date().toISOString()});state.economy.ledger=state.economy.ledger.slice(0,200);if(save)localStorage.setItem(storeKey,JSON.stringify(state));return actual}
function ensureEconomyBare(){state.economy=state.economy||{coins:0,lifetimeEarned:0,lifetimeSpent:0,ledger:[],ownedThemes:['eclipse'],welcomeGift:false};state.economy.ledger=state.economy.ledger||[];state.economy.ownedThemes=state.economy.ownedThemes||['eclipse'];state.economy.coins=Number(state.economy.coins)||0}
function spendCoins(cost,reason,key){ensureEconomyBare();if(state.economy.coins<cost){toast(`Necesitás ${cost-state.economy.coins} monedas más.`,'warn');return false}ledgerChange(-cost,reason,key);syncHeaderStatus();return true}

// ---------- Audio: persistent, resumable and user-controlled ----------
const soundPrefKey='vidaRpgSoundV7';
window.VIDA_SOUND=(()=>{let ctx=null,ambientGain=null,ambientNodes=[];const enabled=()=>localStorage.getItem(soundPrefKey)!=='off';async function ensure(){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;if(!ctx)ctx=new A();if(ctx.state==='suspended'){try{await ctx.resume()}catch(e){}}return ctx}function update(){const on=enabled();document.querySelectorAll('#soundToggle,#globalSoundToggle').forEach(b=>b.textContent=on?'🔊':'🔇');if(state?.rpg)state.rpg.sound=on}async function startAmbient(){if(!enabled())return;const c=await ensure();if(!c)return;if(!ambientGain){ambientGain=c.createGain();ambientGain.gain.value=.0001;ambientGain.connect(c.destination);[55,82.4,110].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type=i===1?'triangle':'sine';o.frequency.value=f;g.gain.value=i===0?.7:.24;o.connect(g).connect(ambientGain);o.start();ambientNodes.push(o)});}const now=c.currentTime;ambientGain.gain.cancelScheduledValues(now);ambientGain.gain.setValueAtTime(Math.max(.0001,ambientGain.gain.value||.0001),now);ambientGain.gain.exponentialRampToValueAtTime(.018,now+.18);update()}async function stopAmbient(){if(!ctx||!ambientGain)return;const now=ctx.currentTime;ambientGain.gain.cancelScheduledValues(now);ambientGain.gain.setValueAtTime(Math.max(.0001,ambientGain.gain.value||.0001),now);ambientGain.gain.exponentialRampToValueAtTime(.0001,now+.12)}async function set(on){localStorage.setItem(soundPrefKey,on?'on':'off');if(state?.rpg){state.rpg.sound=on;localStorage.setItem(storeKey,JSON.stringify(state))}if(on){await ensure();if(page==='assessment'||page==='combat')await startAmbient();await play('click')}else{await stopAmbient();if(ctx?.state==='running'){setTimeout(()=>ctx?.suspend().catch(()=>{}),150)}}update();return on}async function toggle(){return set(!enabled())}async function play(type='click'){if(!enabled())return;const c=await ensure();if(!c)return;const o=c.createOscillator(),g=c.createGain(),now=c.currentTime;o.connect(g);g.connect(c.destination);o.type=type==='level'?'triangle':type==='penalty'?'sawtooth':'sine';const f=type==='reward'?650:type==='level'?420:type==='penalty'?120:300;o.frequency.setValueAtTime(f,now);if(type==='level')o.frequency.exponentialRampToValueAtTime(920,now+.45);if(type==='penalty')o.frequency.exponentialRampToValueAtTime(70,now+.35);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(type==='penalty'?.045:.07,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+(type==='level'?.65:type==='penalty'?.45:.18));o.start();o.stop(now+(type==='level'?.7:type==='penalty'?.5:.2))}return{enabled,startAmbient,stopAmbient,set,toggle,play,update}})();

function injectHeaderStatus(){if(page==='assessment')return;const top=document.querySelector('.topbar');if(!top||document.querySelector('.topbar-status'))return;const box=document.createElement('div');box.className='topbar-status';box.innerHTML='<a id="headerCoins" class="coin-pill" href="tienda.html">🪙 <strong>0</strong></a><button id="globalSoundToggle" class="sound-mini" aria-label="Sonido">🔊</button>';const nav=top.querySelector('.desktop-nav');top.insertBefore(box,nav||null);box.querySelector('#globalSoundToggle').addEventListener('click',()=>window.VIDA_SOUND.toggle())}
function syncHeaderStatus(){const el=document.querySelector('#headerCoins strong');if(el)el.textContent=state.economy.coins;window.VIDA_SOUND.update();applyTheme()}

// ---------- Themes / color system ----------
const themeDefs={eclipse:{name:'Eclipse',price:0},abyss:{name:'Abismo',price:90},crimson:{name:'Carmesí',price:120},sovereign:{name:'Soberano',price:140}};
function applyTheme(){document.body.dataset.theme=state.rpg.theme||'eclipse'}
function themeOwned(id){return id==='eclipse'||state.economy.ownedThemes.includes(id)}

// ---------- Improvement plan ----------
const bottleneckSkill={organization:'Organización',focus:'Productividad',consistency:'Constancia',communication:'Comunicación',leadership:'Liderazgo',problem:'Resolución de problemas',learning:'Aprendizaje',finance:'Finanzas personales',emotion:'Control emocional'};
const responsibilitySkills={operations:['Organización','Productividad','Resolución de problemas'],admin:['Organización','Constancia','Finanzas personales'],sales:['Comunicación','Habilidades sociales','Productividad'],finance:['Finanzas personales','Inteligencia aplicada','Organización'],clients:['Comunicación','Habilidades sociales','Control emocional'],people:['Liderazgo','Comunicación','Control emocional'],projects:['Organización','Liderazgo','Productividad'],analysis:['Inteligencia aplicada','Resolución de problemas','Conocimiento'],technical:['Aprendizaje','Resolución de problemas','Conocimiento'],creative:['Creatividad','Productividad','Comunicación'],study:['Aprendizaje','Constancia','Organización'],physical:['Organización','Salud física','Resolución de problemas'],warehouse:['Organización','Productividad','Salud física'],transport:['Disciplina','Organización','Salud física'],maintenance:['Resolución de problemas','Aprendizaje','Organización']};
const responsibilityTasks={operations:['Revisá el estado de un proceso importante y dejá definido el próximo paso.','Detectá un cuello de botella operativo y registrá una acción concreta para reducirlo.'],admin:['Actualizá un registro administrativo que afecte decisiones o seguimiento.','Ordená un pendiente administrativo repetitivo y definí cómo evitar que vuelva a atrasarse.'],sales:['Hacé seguimiento a una oportunidad comercial concreta y cerrá el próximo paso.','Revisá una conversación de venta y anotá qué necesidad real apareció.'],finance:['Registrá o revisá movimientos relevantes y explicá una variación que merezca atención.','Tomá una decisión pequeña usando un dato de costos, margen, caja o presupuesto.'],clients:['Resolvé o avanzá un caso de cliente confirmando qué resultado espera y cuándo se revisa.','Elegí una conversación con un cliente y cerrala con próximos pasos explícitos.'],people:['Hacé seguimiento a una tarea compartida sin hacerla por la otra persona.','Dá una indicación o feedback concreto y comprobá que el resultado esperado quedó claro.'],projects:['Revisá un proyecto activo: próximo hito, responsable y principal bloqueo.','Cerrá un pendiente de proyecto que esté frenando a otra tarea.'],analysis:['Elegí una decisión real y anotá qué dato la sostiene y qué dato podría hacerte cambiar de opinión.','Compará dos alternativas de una decisión usando al menos dos criterios explícitos.'],technical:['Avanzá una tarea técnica real y documentá el problema encontrado y la prueba realizada.','Aprendé una pieza técnica necesaria para una tarea actual y aplicala inmediatamente.'],creative:['Generá tres alternativas antes de elegir una solución creativa para un trabajo real.','Tomá una pieza existente y mejorala con un criterio concreto, no sólo por gusto.'],study:['Completá un bloque de estudio activo y cerralo con una prueba sin mirar el material.','Avanzá un tema prioritario y anotá qué parte todavía no podrías explicar.']};
const improvementTasks={
'Organización':['Definí 3 prioridades reales antes de entrar en tareas pequeñas.','Cerrá el día dejando escrito el primer paso de mañana.'],
'Productividad':['Protegé un bloque sin interrupciones para la tarea de mayor impacto.','Elegí una tarea que mueve el resultado y terminá una parte observable antes de cambiar de contexto.'],
'Constancia':['Cumplí una versión mínima del hábito de trabajo que querés sostener.','Repetí hoy el sistema aunque el día no sea ideal.'],
'Comunicación':['En una conversación importante, confirmá resultado esperado y próximo paso.','Hacé una pregunta de aclaración antes de asumir qué quiso decir la otra persona.'],
'Liderazgo':['Definí responsable, resultado y fecha de revisión en una tarea compartida.','Detectá un bloqueo del equipo y ayudá a definir el siguiente paso sin absorber toda la tarea.'],
'Resolución de problemas':['Definí un problema real con síntoma, hipótesis y una prueba pequeña.','Antes de aplicar una solución, compará qué cambió desde la última vez que funcionó.'],
'Aprendizaje':['Aplicá algo aprendido a un caso nuevo y anotá qué no funcionó como esperabas.','Explicá sin mirar un concepto necesario para tu trabajo o estudio.'],
'Finanzas personales':['Revisá un movimiento o decisión financiera y conectalo con una prioridad.','Actualizá un registro financiero y sacá una conclusión accionable.'],
'Control emocional':['Ante una fricción real, separá el hecho observable de tu interpretación antes de responder.','Pedí un ejemplo concreto antes de defenderte frente a una crítica.'],
'Inteligencia aplicada':['Tomá una decisión usando un dato concreto y anotá la alternativa descartada.'],
'Habilidades sociales':['Iniciá una conversación útil que normalmente postergarías.'],
'Creatividad':['Generá 3 soluciones con restricciones distintas antes de elegir.']};
function relevantSkills(profile){const arr=[bottleneckSkill[profile.bottleneck]].filter(Boolean);(profile.responsibilities||[]).forEach(r=>arr.push(...(responsibilitySkills[r]||[])));const weak=[...allSkills].sort((a,b)=>effectiveSkillData()[a].score-effectiveSkillData()[b].score);arr.push(...weak);return [...new Set(arr)].filter(Boolean)}
function generatePlan(profile){const focus=relevantSkills(profile).slice(0,3);state.improvementPlan.profile=profile;state.improvementPlan.focusSkills=focus;state.improvementPlan.questionnaireComplete=true;state.improvementPlan.startedAt=todayKey();state.improvementPlan.updatedAt=new Date().toISOString();state.improvementPlan.cycleStart=todayKey();state.improvementPlan.cycleLength=30;state.improvementPlan.acceptedDays={};state.improvementPlan.protectedDays={};removeUnfinishedLegacyTasks();localStorage.setItem(storeKey,JSON.stringify(state));return focus}
function removeUnfinishedLegacyTasks(){const legacy=new Set(['Definir 3 prioridades del día','Registrar o revisar un movimiento financiero','Cumplir la actividad física planificada','Resolver o avanzar un problema importante','Aclarar o coordinar algo con un compañero','Aclarar o coordinar algo con un compañero de estudio']);const d=state.days[todayKey()];if(d)d.tasks=(d.tasks||[]).filter(t=>t.done||t.custom||!legacy.has(t.text))}
function isPlanWorkday(date=new Date()){const days=state.improvementPlan.profile.workdays||[1,2,3,4,5];return days.includes(date.getDay())}
function cycleDayNumber(){if(!state.improvementPlan.cycleStart)return 1;return Math.max(1,Math.floor((new Date(todayKey()+'T12:00:00')-new Date(state.improvementPlan.cycleStart+'T12:00:00'))/86400000)+1)}
function chooseResponsibility(profile,k){const rs=profile.responsibilities||[];if(!rs.length)return profile.area==='finance'?'finance':profile.area==='sales'?'sales':profile.area==='education'?'study':['construction','industrial','fieldwork'].includes(profile.area)?'physical':profile.area==='warehouse'?'warehouse':profile.area==='transport'?'transport':profile.area==='maintenance'?'maintenance':'operations';return rs[seededHash(k)%rs.length]}
function seededHash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
const g30RolePhrases={
operations:{objects:['un proceso que se repite','una entrega o resultado operativo','un cuello de botella visible','un error que suele volver','una tarea que depende de varias personas'],actions:['revisá','simplificá','medí','documentá','ordená'],outcomes:['dejando un próximo paso explícito','reduciendo una fuente de demora','definiendo una señal para detectarlo antes','eliminando un paso innecesario','dejando responsable y momento de revisión']},
admin:{objects:['un registro importante','un pendiente administrativo repetitivo','una conciliación o control','un archivo o documento que otros necesitan','una tarea que suele quedar para último momento'],actions:['actualizá','ordená','cerrá','verificá','convertí en checklist'],outcomes:['sin dejar datos pendientes','marcando qué falta','dejando una versión fácil de repetir','detectando una inconsistencia','definiendo cuándo se vuelve a revisar']},
sales:{objects:['una oportunidad comercial real','un cliente sin próximo paso','una conversación de venta','una objeción frecuente','una propuesta pendiente'],actions:['hacé seguimiento sobre','analizá','cerrá el próximo paso de','mejorá','prepará'],outcomes:['confirmando necesidad y siguiente acción','registrando qué frenó el avance','haciendo una pregunta que aclare prioridad','reduciendo ambigüedad','dejando una fecha concreta de seguimiento']},
finance:{objects:['un movimiento relevante','un costo que cambió','una decisión de gasto','un dato de margen o caja','un presupuesto o previsión'],actions:['revisá','compará','explicá','actualizá','tomá una decisión usando'],outcomes:['anotando qué cambió','separando dato de suposición','definiendo un límite o próximo control','buscando la causa de la variación','conectándolo con una prioridad']},
clients:{objects:['un pedido de cliente','un reclamo o fricción','una conversación pendiente','una expectativa poco clara','un caso que necesita seguimiento'],actions:['resolvé','aclará','cerrá','hacé seguimiento de','revisá'],outcomes:['confirmando el resultado esperado','dejando el próximo paso explícito','evitando promesas ambiguas','registrando lo acordado','preguntando qué sería una buena resolución']},
people:{objects:['una tarea delegada','un bloqueo del equipo','un resultado que necesita feedback','una responsabilidad compartida','una coordinación que suele fallar'],actions:['hacé seguimiento de','aclará','delegá mejor','dá feedback sobre','ordená'],outcomes:['sin absorber la tarea','definiendo resultado y revisión','confirmando comprensión','separando hecho de juicio','dejando responsable claro']},
projects:{objects:['un proyecto activo','un hito cercano','una dependencia crítica','un pendiente que bloquea a otro','una decisión de proyecto'],actions:['revisá','destrabá','priorizá','actualizá','cerrá'],outcomes:['definiendo responsable y fecha','identificando el bloqueo real','dejando el siguiente hito visible','sacando una tarea de la incertidumbre','registrando la decisión y su motivo']},
analysis:{objects:['una decisión real','dos alternativas posibles','un dato que estás usando','una hipótesis de trabajo','un resultado inesperado'],actions:['compará','poné a prueba','analizá','buscá evidencia sobre','definí'],outcomes:['usando dos criterios explícitos','anotando qué dato podría cambiar tu opinión','separando correlación de causa','probando una variable por vez','cerrando con una acción concreta']},
technical:{objects:['una tarea técnica real','un error reproducible','un proceso manual','una parte del sistema que no entendés','una mejora pequeña'],actions:['avanzá','documentá','probá','automatizá o simplificá','aprendé y aplicá'],outcomes:['registrando la prueba realizada','dejando pasos reproducibles','comparando antes y después','reduciendo una fuente de error','explicando qué aprendiste']},
creative:{objects:['una pieza o solución actual','una idea bloqueada','un problema con restricciones','un mensaje o diseño','una tarea creativa real'],actions:['generá alternativas para','mejorá','replanteá','prototipá','compará versiones de'],outcomes:['antes de elegir una','usando una restricción distinta','pidiendo feedback concreto','definiendo qué criterio gana','cerrando una versión observable']},
study:{objects:['un tema prioritario','una habilidad que necesitás','un concepto difícil','un ejercicio o problema','una evaluación próxima'],actions:['estudiá activamente','practicá','explicá sin mirar','resolvé','repasá con recuperación activa'],outcomes:['cerrando con una prueba','anotando qué todavía no podés explicar','aplicándolo a un caso nuevo','sin releer antes de intentar','definiendo el siguiente bloque de estudio']},
physical:{objects:['una tarea física repetitiva','una maniobra de carga o traslado','un trabajo de obra o montaje','una postura que repetís durante horas','una tarea que combina fuerza y precisión'],actions:['revisá','organizá','mejorá la técnica de','prepará','medí'],outcomes:['reduciendo esfuerzo innecesario','priorizando seguridad y control','dejando herramientas y materiales listos','registrando fatiga y recuperación','buscando una forma más eficiente sin apurarte']},
warehouse:{objects:['una carga o descarga','un recorrido de materiales','una zona de depósito','un pedido que necesita preparación','una tarea de movimiento repetitivo'],actions:['ordená','prepará','revisá','simplificá','medí'],outcomes:['reduciendo viajes innecesarios','dejando el próximo movimiento claro','priorizando una manipulación segura','separando urgencia de prioridad','registrando un cuello de botella real']},
transport:{objects:['una ruta o reparto','una preparación previa al viaje','un control del vehículo o equipo','un bloque de conducción','una entrega con horario'],actions:['planificá','revisá','ordená','registrá','anticipá'],outcomes:['reduciendo improvisaciones','dejando márgenes realistas','priorizando seguridad y descanso','anotando una demora recurrente','confirmando el próximo paso antes de salir']},
maintenance:{objects:['una reparación pendiente','una falla que vuelve','una herramienta o equipo','una tarea preventiva','un procedimiento de mantenimiento'],actions:['diagnosticá','revisá','documentá','prepará','probá'],outcomes:['aislando una causa por vez','dejando materiales listos','registrando qué se hizo','evitando repetir el mismo error','cerrando con una prueba de funcionamiento']}
};
const g30SkillVariants={
'Organización':[['elegí','tres resultados del día','y definí qué queda afuera'],['ordená','un pendiente repetitivo','y dejá un sistema mínimo para repetirlo'],['cerrá','el día de trabajo','dejando escrito el primer paso de mañana']],
'Productividad':[['protegé','un bloque sin interrupciones','hasta producir un resultado observable'],['terminá','la parte de mayor impacto','antes de cambiar de contexto'],['reducí','una fuente concreta de interrupciones','durante al menos un bloque de foco']],
'Constancia':[['cumplí','la versión mínima de un hábito importante','aunque el día no sea ideal'],['repetí','una acción que querés volver automática','sin aumentar todavía la dificultad'],['reiniciá','una rutina que se cortó','con una versión deliberadamente pequeña']],
'Comunicación':[['confirmá','resultado esperado y próximo paso','en una conversación real'],['hacé','una pregunta de aclaración','antes de asumir lo que quiso decir la otra persona'],['resumí','un acuerdo importante','en una frase que ambas partes puedan verificar']],
'Liderazgo':[['delegá','una tarea real','definiendo resultado, autonomía y revisión'],['destrabá','un problema del equipo','sin quedarte con toda la ejecución'],['dá','feedback concreto','sobre conducta observable e impacto']],
'Resolución de problemas':[['definí','un problema real','con síntoma, hipótesis y una prueba pequeña'],['compará','qué cambió desde la última vez que funcionó','antes de tocar varias variables'],['probá','la hipótesis más informativa','y registrá qué aprendiste']],
'Aprendizaje':[['aplicá','algo aprendido','a un caso distinto'],['explicá','un concepto necesario','sin mirar el material'],['probate','con una pregunta o ejercicio nuevo','antes de releer']],
'Finanzas personales':[['revisá','un movimiento o decisión financiera','y conectalo con una prioridad'],['actualizá','un registro financiero','y sacá una conclusión accionable'],['compará','dos opciones de gasto o inversión','con criterios explícitos']],
'Control emocional':[['separá','hecho observable de interpretación','antes de responder a una fricción'],['pedí','un ejemplo concreto','antes de defenderte frente a una crítica'],['esperá','unos minutos antes de una respuesta impulsiva','y reformulá el objetivo de la conversación']],
'Inteligencia aplicada':[['tomá','una decisión real usando un dato','y anotá qué alternativa descartaste'],['estimá','un resultado antes de calcularlo','y compará luego con el dato real'],['convertí','una idea abstracta','en una prueba pequeña y medible']],
'Habilidades sociales':[['iniciá','una conversación útil que postergabas','con una pregunta abierta'],['escuchá','una conversación sin preparar tu respuesta','y resumí lo que entendiste'],['pedí','feedback específico','sobre cómo fue una interacción real']],
'Creatividad':[['generá','tres soluciones con restricciones distintas','antes de elegir una'],['cambiá','una restricción del problema','y buscá una alternativa nueva'],['combiná','dos ideas existentes','en una solución que puedas probar']],
'Disciplina':[['hacé','primero una tarea importante sin presión externa','antes de una recompensa fácil'],['cumplí','una regla que definiste previamente','sin renegociarla en el momento'],['empezá','una tarea incómoda','durante sólo diez minutos y decidí después si continuás']],
'Conocimiento':[['contrastá','una afirmación útil','con al menos dos fuentes o datos'],['anotá','qué sabés y qué estás suponiendo','sobre una decisión actual'],['enseñá','un concepto que conocés','con un ejemplo práctico']],
'Fuerza':[['registrá','un ejercicio de fuerza','con carga, repeticiones y esfuerzo'],['mejorá','técnica o control en un ejercicio','sin perseguir un récord'],['compará','tu sesión actual con una anterior','usando datos y no sensación sola']],
'Resistencia':[['completá','un bloque de trabajo aeróbico adecuado a tu nivel','manteniendo un ritmo controlado'],['registrá','duración y percepción de esfuerzo','de una sesión de resistencia'],['sumá','movimiento de baja intensidad','sin interferir con tu recuperación']],
'Velocidad / Potencia':[['practicá','una acción explosiva apropiada a tu actividad','con pocas repeticiones de calidad'],['registrá','una referencia de velocidad o potencia','sin entrenar fatigado'],['priorizá','calidad y descanso','en un bloque breve de potencia']],
'Movilidad':[['trabajá','un rango de movimiento que necesitás','sin dolor y con control'],['evaluá','una limitación de movilidad','antes y después de un bloque breve'],['practicá','control activo en un rango cómodo','en vez de forzar amplitud']],
'Salud física':[['protegé','una decisión de recuperación','según sueño, fatiga y actividad'],['sumá','una acción básica de salud','que puedas repetir mañana'],['registrá','sueño, energía y entrenamiento','para detectar tendencias']],
'Integridad / valores':[['cumplí','un compromiso pequeño aunque nadie lo controle','y registrá el resultado'],['corregí','una información o error que podría beneficiarte injustamente','antes de que se convierta en problema'],['tomá','una decisión coherente con una regla que decís valorar','aunque sea menos cómoda']]
};
function g30PlanStage(day){return day<=7?'Diagnóstico y orden':day<=15?'Construcción':day<=23?'Intensificación':'Consolidación'}
function g30Pick(arr,key,offset=0){return arr[(seededHash(key)+offset)%arr.length]}
function g30ContextMission(p,key){
  const rs=(p.responsibilities||[]);const fallback=p.area==='finance'?'finance':p.area==='sales'?'sales':p.area==='education'?'study':p.area==='tech'?'technical':['construction','industrial','fieldwork'].includes(p.area)?'physical':p.area==='warehouse'?'warehouse':p.area==='transport'?'transport':p.area==='maintenance'?'maintenance':'operations';const r=rs.length?rs[seededHash(key)%rs.length]:fallback;const fam=g30RolePhrases[r]||g30RolePhrases.operations;
  const recurring=(p.recurringTasks||[]).filter(Boolean);if(recurring.length&&seededHash(key+'real')%3===0){const task=recurring[seededHash(key+'rt')%recurring.length];return{r,text:`Misión principal G30: avanzá “${task}” hasta dejar un resultado observable y el próximo paso claro.`}}
  return{r,text:`Misión principal G30: ${g30Pick(fam.actions,key+'a')} ${g30Pick(fam.objects,key+'o')} ${g30Pick(fam.outcomes,key+'r')}.`}
}
function g30SkillMission(skill,key,prefix='Desarrollo G30'){const variants=g30SkillVariants[skill]||g30SkillVariants.Productividad;const v=g30Pick(variants,key);return`${prefix}: ${v[0]} ${v[1]} ${v[2]}.`}
function makePlanTasks(dateKeyValue){
  const p=state.improvementPlan.profile,focus=state.improvementPlan.focusSkills.length?state.improvementPlan.focusSkills:relevantSkills(p).slice(0,3),day=Math.min(cycleDayNumber(),30),stage=g30PlanStage(day),context=g30ContextMission(p,dateKeyValue+stage),respSkill=(responsibilitySkills[context.r]||['Productividad'])[seededHash(dateKeyValue+'rs')%(responsibilitySkills[context.r]||['Productividad']).length],focusSkill=focus[(day-1)%focus.length]||'Productividad',weak=[...allSkills].sort((a,b)=>effectiveSkillData()[a].score-effectiveSkillData()[b].score)[(day+1)%Math.min(5,allSkills.length)]||focusSkill;
  const tasks=[
    {text:context.text,skill:respSkill,category:attrForSkillV7(respSkill),xp:5},
    {text:g30SkillMission(focusSkill,dateKeyValue+'focus',`${stage}`),skill:focusSkill,category:attrForSkillV7(focusSkill),xp:4},
    {text:g30SkillMission(weak,dateKeyValue+'weak','Desafío complementario'),skill:weak,category:attrForSkillV7(weak),xp:3},
    {text:'Cierre G30: registrá qué avanzó, qué te frenó y cuál es el primer paso concreto de mañana.',skill:'Organización',category:'Rendimiento',xp:2}
  ];
  return tasks.map((t,i)=>({id:crypto.randomUUID(),...t,done:false,custom:false,source:'plan',planCycle:state.improvementPlan.cycleStart,planIndex:i,g30Stage:stage}));
}
function attrForSkillV7(skill){return Object.keys(skillMap).find(a=>skillMap[a].includes(skill))||'Rendimiento'}
function ensurePlanTasksForToday(accept=false){if(!state.improvementPlan.questionnaireComplete||!isPlanWorkday())return;const d=getDay();if(!(d.tasks||[]).some(t=>t.source==='plan')){d.tasks=[...(d.tasks||[]),...makePlanTasks(todayKey())];d.planGeneratedV7=true}if(accept&&!state.improvementPlan.protectedDays[todayKey()])state.improvementPlan.acceptedDays[todayKey()]=state.improvementPlan.acceptedDays[todayKey()]||new Date().toISOString();localStorage.setItem(storeKey,JSON.stringify(state))}
function planCompletion(date){const d=state.days[date],tasks=(d?.tasks||[]).filter(t=>t.source==='plan');if(!tasks.length)return null;return tasks.filter(t=>t.done).length/tasks.length}
function protectDate(date=todayKey()){if(!state.improvementPlan.questionnaireComplete)return toast('Primero configurá tu Plan G30.','warn');const reason=prompt('Motivo del día protegido (descanso, enfermedad, viaje, feriado, etc.):','Descanso planificado');if(reason===null)return;state.improvementPlan.protectedDays[date]={reason:reason.trim()||'Día protegido',at:new Date().toISOString()};localStorage.setItem(storeKey,JSON.stringify(state));toast('Día protegido: no genera castigo.','good');if(page==='tasks')renderTasks();if(page==='plan')renderPlanPage()}
function settleCompletedPlanDays(){Object.entries(state.days||{}).forEach(([date,d])=>{const tasks=(d.tasks||[]).filter(t=>t.source==='plan');if(tasks.length&&tasks.every(t=>t.done))ledgerChange(8,'Plan diario completado',`plan-complete:${date}`,false)});localStorage.setItem(storeKey,JSON.stringify(state))}

// ---------- Penalties ----------
function processPenalties(){if(!state.improvementPlan.questionnaireComplete||!state.penalties.settings.enabled)return;const today=todayKey();Object.keys(state.improvementPlan.acceptedDays||{}).sort().forEach(date=>{if(date>=today||state.penalties.processed[date])return;if(state.improvementPlan.protectedDays[date]){state.penalties.processed[date]={protected:true,at:new Date().toISOString()};return}const ratio=planCompletion(date);if(ratio==null){state.penalties.processed[date]={ignored:true,at:new Date().toISOString()};return}if(ratio>=1){state.penalties.processed[date]={completion:1,coinsLost:0,at:new Date().toISOString()};return}let requested=ratio<.34?10:ratio<.67?5:0,shieldUsed=false,lost=0;if(requested>0&&state.penalties.settings.mode==='normal'){if(state.penalties.shields>0){state.penalties.shields--;shieldUsed=true}else lost=Math.abs(ledgerChange(-requested,`Castigo del Sistema · plan ${date}`,`penalty:${date}`,false)||0)}const reward=Math.max(3,Math.ceil(lost/2));state.penalties.active[today]={id:`recovery:${date}`,sourceDate:date,completion:ratio,coinsLost:lost,shieldUsed,reward,done:false,text:ratio<.34?'El plan quedó casi sin completar. Reordená lo pendiente y completá hoy una prioridad real antes de tareas menores.':'El plan quedó incompleto. Elegí el pendiente de mayor impacto, definí el próximo paso y completá una parte observable hoy.'};state.penalties.processed[date]={completion:ratio,coinsLost:lost,shieldUsed,recoveryDay:today,at:new Date().toISOString()}});localStorage.setItem(storeKey,JSON.stringify(state))}
function currentPenalty(){return Object.values(state.penalties.active||{}).filter(x=>!x.done).sort((a,b)=>String(b.sourceDate).localeCompare(String(a.sourceDate)))[0]||null}
function completePenalty(){const p=currentPenalty();if(!p)return;p.done=true;p.doneAt=new Date().toISOString();ledgerChange(p.reward,'Penalty Quest completada',`penalty-recovery:${p.id}`,false);getDay().events.push({id:`penalty:${p.id}`,type:'penalty-recovery',text:'Penalty Quest completada',xp:3,skill:'Disciplina'});localStorage.setItem(storeKey,JSON.stringify(state));window.VIDA_SOUND.play('reward');toast(`Recuperación completada · +${p.reward} monedas`,'good');renderPenaltyCard();syncHeaderStatus()}
function renderPenaltyCard(){const card=$('#penaltyDungeonCard');if(!card)return;const p=currentPenalty();card.classList.toggle('hidden',!p);if(!p)return;$('#penaltyQuestText').textContent=`Por el plan del ${p.sourceDate}: ${Math.round(p.completion*100)}% completado${p.shieldUsed?' · un escudo evitó la pérdida de monedas':p.coinsLost?` · -${p.coinsLost} monedas`:''}.`;$('#penaltyQuestAction').textContent=p.text;$('#penaltyReward').textContent=`+${p.reward} 🪙`;$('#completePenaltyQuest').checked=false}
function maybeShowPenaltyOverlay(){const p=currentPenalty();if(!p||state.penalties.lastShown===p.id)return;state.penalties.lastShown=p.id;localStorage.setItem(storeKey,JSON.stringify(state));const ov=document.createElement('div');ov.className='overlay penalty-overlay';ov.innerHTML=`<section class="modal penalty-modal"><div class="penalty-glyph">!</div><div class="eyebrow">PENALTY QUEST</div><h1>El Sistema registró un incumplimiento</h1><p class="muted">${escapeHtml(p.text)}</p><div class="penalty-loss">${p.shieldUsed?'🛡️ Escudo consumido':p.coinsLost?`-${p.coinsLost} 🪙`:'Sin pérdida de monedas'}</div><button class="primary wide big">Aceptar recuperación</button><p class="note">Los castigos son sólo de juego. Días protegidos no generan penalización.</p></section>`;document.body.appendChild(ov);ov.querySelector('button').addEventListener('click',()=>ov.remove());window.VIDA_SOUND.play('penalty')}

// ---------- Task page override ----------
const renderTasksBeforeV7=renderTasks;
renderTasks=function(){ensurePlanTasksForToday(page==='tasks');const d=getDay();const planReady=state.improvementPlan.questionnaireComplete;const workday=planReady&&isPlanWorkday();const tasks=d.tasks||[];$('#dailyTasks').innerHTML=tasks.length?tasks.map(t=>`<div class="task ${t.done?'done':''} ${t.source==='plan'?'plan-task':''}"><input type="checkbox" data-id="${t.id}" ${t.done?'checked':''}><div><div class="task-title">${escapeHtml(t.text)}</div><div class="task-meta">${escapeHtml(t.skill)}${t.source==='plan'?' · Plan G30':''}</div></div><span class="tag">${t.category}</span><span class="task-xp">+${t.xp} XP</span>${t.custom?`<button class="delete-task" data-del="${t.id}">×</button>`:''}</div>`).join(''):'<div class="empty">No hay tareas cargadas para hoy.</div>';$('#todayXp').textContent=dayXp(d);$('#sleepHours').value=d.checkin.sleepHours??'';$('#energy').value=d.checkin.energy??'';$('#mood').value=d.checkin.mood??'';$('#dayNote').value=d.checkin.note??'';$('#reminderTime').value=state.reminderTime||'21:00';$('#reminderText').value=state.reminderText||freshDefaults.reminderText;updateSkillSelect();if($('#dailyPlanTitle'))$('#dailyPlanTitle').textContent=!planReady?'Configurá tu Plan G30':!workday?'Día fuera del plan':`Día ${cycleDayNumber()} · ${state.improvementPlan.focusSkills.join(' · ')}`;if($('#dailyPlanStatus'))$('#dailyPlanStatus').innerHTML=!planReady?'Las tareas automáticas quedan en pausa hasta conocer tu trabajo o estudio. <a href="plan.html">Completar cuestionario →</a>':state.improvementPlan.protectedDays[todayKey()]?`🛡️ Día protegido · ${escapeHtml(state.improvementPlan.protectedDays[todayKey()].reason)}`:workday?'Hoy forma parte del ciclo. Al abrir esta pantalla el plan queda aceptado y puede generar una Penalty Quest si queda incompleto.':'Podés usar tareas personales sin que hoy genere castigo.';settleCompletedPlanDays();syncEconomyRewards();syncHeaderStatus()}

// ---------- Plan page ----------
function fillPlanForm(){if(page!=='plan')return;const p=state.improvementPlan.profile;$('#workType').value=p.workType||'employee';$('#workArea').value=p.area||'operations';$('#workRole').value=p.role||'individual';$('#workTeamSize').value=p.teamSize||0;$('#workBottleneck').value=p.bottleneck||'organization';$('#workMinutes').value=String(p.minutes||30);$$('#responsibilityChecks input').forEach(x=>x.checked=(p.responsibilities||[]).includes(x.value));$$('#workdayChecks input').forEach(x=>x.checked=(p.workdays||[1,2,3,4,5]).includes(+x.value));$('#workRecurringTasks').value=(p.recurringTasks||[]).join('\n');$('#workGoalText').value=p.goalText||'';if($('#workCustomContext'))$('#workCustomContext').value=p.customContext||'';$('#penaltiesEnabled').checked=state.penalties.settings.enabled!==false;$('#penaltyMode').value=state.penalties.settings.mode||'normal'}
function renderPlanPage(){if(page!=='plan')return;fillPlanForm();const ready=state.improvementPlan.questionnaireComplete,p=state.improvementPlan.profile;$('#planCurrentTitle').textContent=ready?`Plan G30 activo · día ${Math.min(cycleDayNumber(),30)}/30`:'Todavía no hay un plan';$('#planSummary').innerHTML=ready?`<div class="plan-stat"><span>Contexto</span><strong>${escapeHtml(p.workType)} · ${escapeHtml(p.area)}</strong></div><div class="plan-stat"><span>Objetivo</span><strong>${escapeHtml(p.goalText||'Mejorar desempeño general')}</strong></div><div class="plan-stat"><span>Tiempo</span><strong>${p.minutes||30} min/día</strong></div><div class="plan-stat"><span>Escudos</span><strong>${state.penalties.shields} 🛡️</strong></div>`:'<p class="muted">El cuestionario convierte responsabilidades reales y puntos débiles en tareas del día.</p>';$('#planFocusSkills').innerHTML=ready?state.improvementPlan.focusSkills.map((s,i)=>`<div class="focus-card"><span>FOCO ${i+1}</span><strong>${escapeHtml(s)}</strong><small>Nivel actual ${effectiveSkillData()[s]?.score??'—'}</small></div>`).join(''):'';const weeks=[['Días 1–7 · Diagnóstico y orden','Entender el sistema actual y ordenar lo que más fricción genera.'],['Días 8–15 · Construcción','Instalar acciones repetibles y ejecutar con menos fricción.'],['Días 16–23 · Intensificación','Subir el nivel de exigencia sin perder consistencia.'],['Días 24–30 · Consolidación','Medir, ajustar y dejar un sistema que pueda repetirse.']];$('#planWeeks').innerHTML=ready?weeks.map((w,i)=>`<article class="week-card ${(cycleDayNumber()<=7?0:cycleDayNumber()<=15?1:cycleDayNumber()<=23?2:3)===i?'active':''}"><strong>${w[0]}</strong><span>${w[1]}</span></article>`).join(''):'';$('#resetPlanBtn').disabled=!ready;$('#protectTodayBtn').disabled=!ready||!isPlanWorkday()}
function savePlanForm(e){e.preventDefault();const profile={workType:$('#workType').value,area:$('#workArea').value,role:$('#workRole').value,teamSize:+$('#workTeamSize').value||0,bottleneck:$('#workBottleneck').value,minutes:+$('#workMinutes').value||30,responsibilities:$$('#responsibilityChecks input:checked').map(x=>x.value),workdays:$$('#workdayChecks input:checked').map(x=>+x.value),recurringTasks:$('#workRecurringTasks').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,12),goalText:$('#workGoalText').value.trim(),customContext:$('#workCustomContext')?.value.trim()||''};if(!profile.workdays.length)return toast('Elegí al menos un día del plan.','warn');generatePlan(profile);const msg=$('#planFormMessage');msg.className='quiz-feedback good';msg.textContent=`Plan G30 creado. Focos: ${state.improvementPlan.focusSkills.join(', ')}.`;renderPlanPage();window.VIDA_SOUND.play('reward');toast('Plan G30 creado.','good')}

// ---------- Economy / store ----------
function syncEconomyRewards(){ensureEconomyBare();Object.entries(state.missions?.daily||{}).forEach(([date,d])=>(d.items||[]).forEach(m=>{if(m.done)ledgerChange(2,`Misión del Sistema · ${m.skill}`,`coin-mission:${m.id}`,false)}));Object.entries(state.missions?.chests||{}).forEach(([date,c])=>{if(c.claimed)ledgerChange(10,'Cofre diario',`coin-chest:${date}`,false)});Object.entries(state.missions?.weekly||{}).forEach(([wk,b])=>{if(b.claimed)ledgerChange(25,`Boss semanal · ${b.attr||''}`,`coin-boss:${wk}`,false)});Object.entries(state.academyCertifications||{}).forEach(([cat,c])=>{if(c.passed)ledgerChange(20,`Certificación · ${cat}`,`coin-cert:${cat}`,false)});settleCompletedPlanDaysNoLoop();localStorage.setItem(storeKey,JSON.stringify(state))}
function settleCompletedPlanDaysNoLoop(){Object.entries(state.days||{}).forEach(([date,d])=>{const tasks=(d.tasks||[]).filter(t=>t.source==='plan');if(tasks.length&&tasks.every(t=>t.done)&&!hasLedgerKey(`plan-complete:${date}`))ledgerChange(8,'Plan diario completado',`plan-complete:${date}`,false)})}
function buyExtraLesson(){if(!spendCoins(25,'Llave de Academia'))return false;state.monetization.bonusLessons[todayKey()]=(state.monetization.bonusLessons[todayKey()]||0)+1;localStorage.setItem(storeKey,JSON.stringify(state));toast('Llave comprada · +1 lección hoy','good');return true}
function buyShopItem(item){if(item==='lesson'){if(buyExtraLesson())renderStorePage();return}if(item==='shield'){if(!spendCoins(45,'Escudo de penalización'))return;state.penalties.shields++;localStorage.setItem(storeKey,JSON.stringify(state));toast('Escudo añadido al inventario.','good')}else if(item==='reroll'){const daily=state.missions?.daily?.[todayKey()];if(daily?.items?.some(x=>x.done))return toast('No podés recalibrar después de completar una misión hoy.','warn');if(!spendCoins(20,'Recalibrar misiones'))return;delete state.missions.daily[todayKey()];localStorage.setItem(storeKey,JSON.stringify(state));toast('Las Misiones del Sistema fueron recalibradas.','good')}else if(item.startsWith('theme:')){const id=item.split(':')[1],def=themeDefs[id];if(themeOwned(id)){state.rpg.theme=id;localStorage.setItem(storeKey,JSON.stringify(state));applyTheme();toast(`Tema ${def.name} equipado.`,'good')}else{if(!spendCoins(def.price,`Tema ${def.name}`))return;state.economy.ownedThemes.push(id);state.rpg.theme=id;localStorage.setItem(storeKey,JSON.stringify(state));applyTheme();toast(`Tema ${def.name} desbloqueado.`,'good')}}renderStorePage();syncHeaderStatus()}
async function buyCoinPack(packId){const m=$('#coinPurchaseMessage');try{if(!window.VIDA_RPG_COIN_PURCHASE?.buy)throw new Error('Todavía no hay un proveedor de pago seguro conectado.');m.className='quiz-feedback';m.textContent='Esperando confirmación del proveedor...';const r=await window.VIDA_RPG_COIN_PURCHASE.buy(packId);if(!r?.verified||!r.transactionId||!Number(r.coins))throw new Error('El servidor no confirmó la compra.');ledgerChange(Number(r.coins),'Compra de monedas',`real-money:${r.transactionId}`);m.className='quiz-feedback good';m.textContent=`Compra verificada · +${r.coins} monedas.`;renderStorePage()}catch(e){m.className='quiz-feedback bad';m.textContent=e.message}}
function renderStorePage(){if(page!=='store')return;syncEconomyRewards();$('#storeCoins').textContent=state.economy.coins;$$('[data-shop-item]').forEach(b=>{const item=b.dataset.shopItem;if(item.startsWith('theme:')){const id=item.split(':')[1];b.textContent=themeOwned(id)?(state.rpg.theme===id?'Equipado':'Equipar'):'Desbloquear'}});$('#coinLedger').innerHTML=state.economy.ledger.slice(0,16).map(x=>`<div class="ledger-row"><div><strong>${escapeHtml(x.reason)}</strong><small>${new Date(x.at).toLocaleString('es-AR')}</small></div><span class="${x.delta>=0?'coin-plus':'coin-minus'}">${x.delta>=0?'+':''}${x.delta} 🪙</span></div>`).join('')||'<div class="empty">Sin movimientos.</div>'}

// Academy coin button
function bindAcademyCoin(){if(page!=='academy')return;$('#coinUnlockBtn')?.addEventListener('click',()=>{if(buyExtraLesson()){closePaywall();renderAcademy();syncHeaderStatus()}})}

// ---------- Profile theme ----------
const renderProfileBeforeV7=renderProfile;
renderProfile=function(){renderProfileBeforeV7();if($('#profileThemeSelect')){$('#profileThemeSelect').innerHTML=Object.entries(themeDefs).filter(([id])=>themeOwned(id)).map(([id,d])=>`<option value="${id}" ${state.rpg.theme===id?'selected':''}>${d.name}</option>`).join('')}}

// ---------- Combat ----------
const combatQuestions=[
{id:'q1',cat:'Lógica',text:'Un producto vale $80.000 y baja 15%. ¿Cuál es el nuevo precio?',options:['$68.000','$72.000','$65.000','$74.000'],correct:0},
{id:'q2',cat:'Lógica',text:'La serie es 4, 7, 13, 25, 49. ¿Qué sigue?',options:['97','96','99','101'],correct:0},
{id:'q3',cat:'Decisiones',text:'Una métrica empeora justo después de un cambio. ¿Qué prueba aísla mejor la causa?',options:['Revertir temporalmente sólo ese cambio y comparar','Cambiar dos variables más','Esperar un mes sin medir','Preguntar qué piensa la mayoría'],correct:0},
{id:'q4',cat:'Nutrición',text:'Para perder grasa a lo largo del tiempo, ¿qué condición es necesaria?',options:['Déficit calórico sostenible','Eliminar carbohidratos','Entrenar en ayunas','No cenar'],correct:0},
{id:'q5',cat:'Nutrición',text:'Una etiqueta marca 210 kcal por porción y hay 2,5 porciones. ¿Cuántas kcal indica el paquete completo?',options:['525','420','510','610'],correct:0},
{id:'q6',cat:'Trabajo',text:'Una tarea importante está trabada porque falta información. ¿Qué suele ser mejor primero?',options:['Definir exactamente qué dato falta y quién puede aportarlo','Empezar otra tarea y olvidarla','Agregar más personas al chat','Cambiar el objetivo sin avisar'],correct:0},
{id:'q7',cat:'Comunicación',text:'Para reducir un malentendido en una tarea crítica, ¿qué ayuda más?',options:['Confirmar resultado esperado y próximo paso','Mandar más mensajes sin estructura','Hablar más rápido','Evitar preguntas'],correct:0},
{id:'q8',cat:'Aprendizaje',text:'¿Qué prueba mejor que entendiste una idea?',options:['Resolver un caso nuevo sin mirar el material','Releerla varias veces','Subrayarla','Guardar un resumen'],correct:0},
{id:'q9',cat:'Finanzas',text:'Ingresos $150.000, costos $90.000. ¿Cuál es el resultado antes de otros gastos?',options:['$60.000','$40.000','$90.000','$240.000'],correct:0},
{id:'q10',cat:'Lógica',text:'Si 5 personas hacen 5 unidades en 5 minutos al mismo ritmo, ¿cuántas hacen 10 personas en 10 minutos?',options:['20','10','25','15'],correct:0},
{id:'q11',cat:'Entrenamiento',text:'¿Cuál puede ser sobrecarga progresiva sin subir peso?',options:['Más repeticiones con buena técnica','Menos sueño','Peor rango de movimiento','Cambiar todo cada sesión'],correct:0},
{id:'q12',cat:'Trabajo',text:'Hay 12 tareas y poco tiempo. ¿Qué criterio ayuda más a priorizar?',options:['Impacto, urgencia real y dependencias','Orden alfabético','La más entretenida','La más nueva'],correct:0},
{id:'q13',cat:'Lógica',text:'Un valor aumenta de 50 a 60. ¿Qué aumento porcentual representa?',options:['20%','10%','16%','25%'],correct:0},
{id:'q14',cat:'Problemas',text:'Dos variables se mueven juntas. ¿Qué podés afirmar sólo por eso?',options:['Hay asociación; no demuestra causalidad','Una causa a la otra','Siempre habrá una tercera causa','Seguirán juntas para siempre'],correct:0},
{id:'q15',cat:'Nutrición',text:'El peso sube 0,8 kg de un día a otro. ¿Qué interpretación es más prudente?',options:['Puede ser agua y contenido digestivo; un día no define grasa','Es exactamente 0,8 kg de grasa','La dieta dejó de funcionar','Es seguro que ganó músculo'],correct:0},
{id:'q16',cat:'Organización',text:'¿Qué sistema reduce más la dependencia de memoria en una tarea semanal?',options:['Checklist o recordatorio recurrente','Intentar acordarse más fuerte','Esperar a que alguien pregunte','Cambiar el horario cada semana'],correct:0},
{id:'q17',cat:'Finanzas',text:'Comprás a $800 y vendés a $1.000. ¿Cuál es la ganancia bruta por unidad?',options:['$200','$125','$800','$1.800'],correct:0},
{id:'q18',cat:'Lógica',text:'Todas las A son B. Ninguna B es C. ¿Puede alguna A ser C?',options:['No','Sí, siempre','Sólo si es urgente','No se puede saber'],correct:0},
{id:'q19',cat:'Comunicación',text:'Recibís una crítica que parece injusta. ¿Qué respuesta da más información?',options:['Pedir un ejemplo concreto y escuchar antes de responder','Interrumpir para explicar tu intención','Aceptar sin preguntar','Cerrar la conversación'],correct:0},
{id:'q20',cat:'Entrenamiento',text:'¿Qué describe mejor la recuperación?',options:['Parte del proceso de adaptación','Tiempo perdido','Sólo importa en profesionales','Se reemplaza con cafeína'],correct:0},
{id:'q21',cat:'Lógica',text:'Si el 30% de 200 es X, ¿cuánto vale X?',options:['60','30','70','90'],correct:0},
{id:'q22',cat:'Trabajo',text:'Un proyecto se atrasa. ¿Cuál es un buen primer diagnóstico?',options:['Bloqueos, responsables y próximos pasos','Culpar al último que entregó','Sumar tareas al equipo','Cambiar la fecha sin revisar causas'],correct:0},
{id:'q23',cat:'Nutrición',text:'Para comparar dos etiquetas con porciones distintas, ¿qué es más limpio?',options:['Llevar ambas a la misma cantidad','Elegir la porción más pequeña','Mirar sólo la proteína del paquete','Usar el número más grande impreso'],correct:0},
{id:'q24',cat:'Aprendizaje',text:'Después de cometer un error, ¿qué mejora más el aprendizaje?',options:['Identificar por qué ocurrió y probar un cambio concreto','Ocultarlo','Cambiar de tema','Repetir exactamente lo mismo'],correct:0}
].map(q=>({...q,options:q.options.map((label,i)=>({label,correct:i===q.correct}))}));
const abilityDefs=[
{id:'time',level:1,name:'Análisis temporal',cost:1,desc:'+5 segundos en la pregunta actual.'},
{id:'crit',level:3,name:'Golpe crítico',cost:2,desc:'La próxima respuesta correcta hace daño x2.'},
{id:'shield',level:5,name:'Escudo mental',cost:2,desc:'Bloquea el próximo golpe recibido.'},
{id:'burst',level:8,name:'Ráfaga de foco',cost:3,desc:'La próxima correcta suma +6 daño y +2 Foco.'},
{id:'eliminate',level:12,name:'Lectura del patrón',cost:3,desc:'Elimina una respuesta incorrecta.'},
{id:'dominion',level:16,name:'Dominio',cost:4,desc:'La próxima correcta suma +15 daño y recupera 5 HP.'}
];
let battle=null;
function unlockedAbilities(){const lvl=typeof characterLevelData==='function'?characterLevelData().level:1;return abilityDefs.filter(a=>lvl>=a.level)}
function renderCombatPage(){if(page!=='combat')return;const lvl=characterLevelData().level;$('#arenaRating').textContent=state.combat.rating||1000;$('#arenaRecord').textContent=`${state.combat.wins||0}V · ${state.combat.losses||0}D`;$('#combatLevelPill').textContent=`Nivel RPG ${lvl}`;$('#combatAbilityList').innerHTML=abilityDefs.map(a=>`<article class="ability-card ${lvl<a.level?'locked':''}"><div class="ability-level">NV ${a.level}</div><strong>${a.name}</strong><p>${a.desc}</p><span>${lvl>=a.level?`${a.cost} Foco`:'Bloqueada'}</span></article>`).join('')}
function shuffledQuestion(seed){const q=combatQuestions[seededHash(seed)%combatQuestions.length],opts=shuffleV7(q.options);return{...q,options:opts}}
function shuffleV7(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function fighter(name){return{name,hp:100,focus:0,score:0,shield:false,crit:false,burst:false,dominion:false}}
function startBattle(mode){window.VIDA_SOUND.startAmbient();battle={mode,round:0,maxRounds:18,p1:fighter(state.player.name||'Jugador'),p2:fighter(mode==='bot'?'Sistema':'Jugador 2'),active:'p1',question:null,startedAt:0,remaining:12,timer:null,ended:false,used:new Set()};$('#battleOverlay').classList.remove('hidden');$('#battleResultPanel').classList.add('hidden');$('#passDevicePanel').classList.add('hidden');$('#battleP1Name').textContent=battle.p1.name;$('#battleP2Name').textContent=battle.p2.name;$('#battleLog').innerHTML='';nextBattleTurn(true)}
function currentFighter(){return battle[battle.active]}function enemyFighter(){return battle[battle.active==='p1'?'p2':'p1']}
function updateBattleHud(){for(const [key,prefix] of [['p1','P1'],['p2','P2']]){const f=battle[key];$(`#battle${prefix}Hp`).style.width=`${clamp(f.hp)}%`;$(`#battle${prefix}HpText`).textContent=Math.max(0,Math.round(f.hp));$(`#battle${prefix}Focus`).textContent=f.focus}$('#battleTurn').textContent=`TURNO · ${currentFighter().name}`;renderBattleAbilities()}
function renderBattleAbilities(){const f=currentFighter(),lvl=characterLevelData().level;$('#battleAbilities').innerHTML=abilityDefs.map(a=>`<button class="battle-ability ${lvl<a.level||f.focus<a.cost?'locked':''}" data-battle-ability="${a.id}" ${lvl<a.level||f.focus<a.cost?'disabled':''}><strong>${a.name}</strong><span>${lvl<a.level?`NV ${a.level}`:`${a.cost} Foco`}</span></button>`).join('')}
function logBattle(text){const el=$('#battleLog');el.innerHTML=`<div>${escapeHtml(text)}</div>`+el.innerHTML}
function nextBattleTurn(first=false){if(!battle||battle.ended)return;if(battle.p1.hp<=0||battle.p2.hp<=0||battle.round>=battle.maxRounds)return endBattle();battle.round++;if(battle.mode==='local'&&!first){battle.active=battle.active==='p1'?'p2':'p1';showPassDevice();return}showBattleQuestion()}
function showPassDevice(){clearBattleTimer();$('#passDevicePanel').classList.remove('hidden');$('#passDeviceTitle').textContent=`Turno de ${currentFighter().name}`;updateBattleHud()}
function showBattleQuestion(){$('#passDevicePanel').classList.add('hidden');battle.question=shuffledQuestion(`${Date.now()}:${battle.round}:${battle.active}`);battle.remaining=12;battle.startedAt=performance.now();$('#battleCategory').textContent=battle.question.cat;$('#battleQuestion').textContent=battle.question.text;$('#battleAnswers').innerHTML=battle.question.options.map((o,i)=>`<button class="answer-btn" data-battle-answer="${i}">${escapeHtml(o.label)}</button>`).join('');updateBattleHud();startBattleTimer()}
function startBattleTimer(){clearBattleTimer();battle.timer=setInterval(()=>{battle.remaining=Math.max(0,12-(performance.now()-battle.startedAt)/1000);$('#battleTimerText').textContent=battle.remaining.toFixed(1);$('#battleTimerBar').style.width=`${battle.remaining/12*100}%`;if(battle.remaining<=0){clearBattleTimer();resolveBattleAnswer(null)}},100)}function clearBattleTimer(){if(battle?.timer){clearInterval(battle.timer);battle.timer=null}}
function applyDamage(target,damage){if(target.shield){target.shield=false;logBattle(`${target.name} bloqueó el golpe con Escudo mental.`);return 0}target.hp=Math.max(0,target.hp-damage);return damage}
function resolveBattleAnswer(index){if(!battle||battle.ended||!battle.question)return;clearBattleTimer();const f=currentFighter(),enemy=enemyFighter(),answer=index==null?null:battle.question.options[index],correct=!!answer?.correct,remaining=battle.remaining;if(correct){let damage=10+Math.round((remaining/12)*6),focusGain=remaining>=8?2:1;if(f.crit){damage*=2;f.crit=false}if(f.burst){damage+=6;focusGain+=2;f.burst=false}if(f.dominion){damage+=15;f.hp=Math.min(100,f.hp+5);f.dominion=false}f.focus=Math.min(8,f.focus+focusGain);f.score++;const dealt=applyDamage(enemy,damage);logBattle(`${f.name} acertó · ${dealt} daño · +${focusGain} Foco.`);window.VIDA_SOUND.play('reward')}else logBattle(index==null?`${f.name} se quedó sin tiempo.`:`${f.name} falló la respuesta.`);updateBattleHud();battle.question=null;if(battle.p1.hp<=0||battle.p2.hp<=0)return setTimeout(endBattle,500);if(battle.mode==='bot')setTimeout(botTurn,550);else setTimeout(()=>nextBattleTurn(false),450)}
function botTurn(){if(!battle||battle.ended)return;const bot=battle.p2,player=battle.p1,lvl=characterLevelData().level,chance=Math.min(.78,.50+lvl*.012),correct=Math.random()<chance;if(correct){const damage=10+Math.floor(Math.random()*5);bot.score++;bot.focus=Math.min(8,bot.focus+1);const dealt=applyDamage(player,damage);logBattle(`Sistema respondió correctamente · ${dealt} daño.`)}else logBattle('Sistema falló su contraataque.');updateBattleHud();if(player.hp<=0)return setTimeout(endBattle,500);setTimeout(()=>{battle.active='p1';nextBattleTurn(true)},650)}
function useBattleAbility(id){if(!battle||battle.ended)return;const f=currentFighter(),a=abilityDefs.find(x=>x.id===id);if(!a||characterLevelData().level<a.level||f.focus<a.cost)return;f.focus-=a.cost;if(id==='time'){battle.startedAt+=5000;logBattle(`${f.name} activó Análisis temporal.`)}if(id==='crit'){f.crit=true;logBattle(`${f.name} cargó Golpe crítico.`)}if(id==='shield'){f.shield=true;logBattle(`${f.name} activó Escudo mental.`)}if(id==='burst'){f.burst=true;logBattle(`${f.name} activó Ráfaga de foco.`)}if(id==='dominion'){f.dominion=true;logBattle(`${f.name} activó Dominio.`)}if(id==='eliminate'&&battle.question){const wrong=[...$('#battleAnswers').querySelectorAll('[data-battle-answer]')].filter(b=>!battle.question.options[+b.dataset.battleAnswer].correct&&!b.disabled);if(wrong.length){wrong[Math.floor(Math.random()*wrong.length)].disabled=true;wrong[Math.floor(Math.random()*wrong.length)]?.classList.add('eliminated')}logBattle(`${f.name} eliminó una opción.`)}updateBattleHud();window.VIDA_SOUND.play('click')}
function endBattle(){if(!battle||battle.ended)return;clearBattleTimer();battle.ended=true;const winner=battle.p1.hp===battle.p2.hp?(battle.p1.score>=battle.p2.score?'p1':'p2'):(battle.p1.hp>battle.p2.hp?'p1':'p2'),wf=battle[winner];$('#battleResultPanel').classList.remove('hidden');$('#passDevicePanel').classList.add('hidden');$('#battleResultTitle').textContent=`${wf.name} gana`;$('#battleResultText').textContent=`Marcador ${battle.p1.score}-${battle.p2.score} · HP ${Math.round(battle.p1.hp)}-${Math.round(battle.p2.hp)}.`;if(battle.mode==='bot'){const win=winner==='p1';if(win){state.combat.wins++;state.combat.rating=(state.combat.rating||1000)+15;ledgerChange(8,'Victoria de entrenamiento',`combat-training:${todayKey()}`,false);window.VIDA_SOUND.play('level')}else{state.combat.losses++;state.combat.rating=Math.max(800,(state.combat.rating||1000)-8)}state.combat.history.unshift({date:new Date().toISOString(),mode:'bot',win,score:[battle.p1.score,battle.p2.score]});state.combat.history=state.combat.history.slice(0,50);localStorage.setItem(storeKey,JSON.stringify(state));syncHeaderStatus();renderCombatPage()}}
function closeBattle(){clearBattleTimer();battle=null;$('#battleOverlay').classList.add('hidden');window.VIDA_SOUND.stopAmbient()}
async function checkOnlineBattle(){const m=$('#onlineBattleMessage');if(window.VIDA_RPG_PVP?.open){m.className='quiz-feedback good';m.textContent='Adaptador PvP conectado. Abriendo lobby...';try{await window.VIDA_RPG_PVP.open()}catch(e){m.className='quiz-feedback bad';m.textContent=e.message}}else{m.className='quiz-feedback bad';m.textContent='El motor de combate ya funciona en Entrenamiento y Versus local. Para dos teléfonos falta conectar el backend PvP autenticado; PVP_SETUP.sql deja preparada la base.'}}

// ---------- render wrappers ----------
const renderHomeBeforeV7=renderHome;
renderHome=function(){ensurePlanTasksForToday(false);renderHomeBeforeV7();syncEconomyRewards();syncHeaderStatus();if($('#systemBriefText')&&state.improvementPlan.questionnaireComplete){const p=state.improvementPlan;$('#systemBriefText').textContent=`Plan G30 · día ${Math.min(cycleDayNumber(),30)}: foco actual ${p.focusSkills.join(', ')}. Tus tareas de Hoy salen de este ciclo y de tu contexto real.`}}
const renderPageBeforeV7=renderPage;
renderPage=function(){renderPageBeforeV7();if(page==='plan')renderPlanPage();if(page==='store')renderStorePage();if(page==='combat')renderCombatPage();renderPenaltyCard();syncHeaderStatus()}

// ---------- bindings ----------
function bindV7(){
  if(page==='tasks'){$('#protectDayFromTasksBtn')?.addEventListener('click',()=>protectDate())}
  if(page==='plan'){$('#workPlanForm')?.addEventListener('submit',savePlanForm);$('#protectTodayBtn')?.addEventListener('click',()=>protectDate());$('#resetPlanBtn')?.addEventListener('click',()=>{if(!confirm('¿Rehacer el Plan G30? Tu historial anterior se conserva.'))return;state.improvementPlan.questionnaireComplete=false;localStorage.setItem(storeKey,JSON.stringify(state));renderPlanPage()});$('#penaltiesEnabled')?.addEventListener('change',e=>{state.penalties.settings.enabled=e.target.checked;localStorage.setItem(storeKey,JSON.stringify(state))});$('#penaltyMode')?.addEventListener('change',e=>{state.penalties.settings.mode=e.target.value;localStorage.setItem(storeKey,JSON.stringify(state))})}
  if(page==='missions'){$('#completePenaltyQuest')?.addEventListener('change',e=>{if(e.target.checked)completePenalty()})}
  if(page==='academy')bindAcademyCoin();
  if(page==='store'){$$('.shop-grid [data-shop-item]').forEach(b=>b.addEventListener('click',()=>buyShopItem(b.dataset.shopItem)));$$('[data-coin-pack]').forEach(b=>b.addEventListener('click',()=>buyCoinPack(b.dataset.coinPack)))}
  if(page==='profile'){$('#profileThemeSelect')?.addEventListener('change',e=>{state.rpg.theme=e.target.value;localStorage.setItem(storeKey,JSON.stringify(state));applyTheme()})}
  if(page==='combat'){$('#startBotBattleBtn')?.addEventListener('click',()=>startBattle('bot'));$('#startLocalBattleBtn')?.addEventListener('click',()=>startBattle('local'));$('#onlineBattleBtn')?.addEventListener('click',checkOnlineBattle);$('#battleAnswers')?.addEventListener('click',e=>{const b=e.target.closest('[data-battle-answer]');if(b)resolveBattleAnswer(+b.dataset.battleAnswer)});$('#battleAbilities')?.addEventListener('click',e=>{const b=e.target.closest('[data-battle-ability]');if(b)useBattleAbility(b.dataset.battleAbility)});$('#continueLocalTurnBtn')?.addEventListener('click',showBattleQuestion);$('#closeBattleBtn')?.addEventListener('click',closeBattle);$('#battleResultCloseBtn')?.addEventListener('click',closeBattle)}
}

// ---------- lifecycle ----------
ensureV7State();injectHeaderStatus();applyTheme();processPenalties();syncEconomyRewards();
if(page==='tasks')ensurePlanTasksForToday(true);else if(page==='home')ensurePlanTasksForToday(false);
renderPage();bindV7();syncHeaderStatus();setTimeout(maybeShowPenaltyOverlay,300);
if(page==='assessment'){window.VIDA_SOUND.update();}
})();
