(()=>{
const V8_TARGET_QUESTIONS=35;
function ensureV8State(){
  state.version=8;
  state.ui=state.ui||{};
  state.ui.homePanels=state.ui.homePanels||{diet:false,training:false,modules:false,achievements:false};
  state.trainingProfile=state.trainingProfile||{goal:'general',level:'intermediate',location:'gym',minutes:60,weekdays:[1,3,5],cardio:true,notes:''};
  state.trainingPlan=state.trainingPlan||null;
  state.trainingLogs=state.trainingLogs||{};
  localStorage.setItem(storeKey,JSON.stringify(state));
}
ensureV8State();

// ---------------- Epic gate audio (original procedural sound, no external copyrighted track) ----------------
window.VIDA_EPIC=(()=>{let fanfareCtx=null;async function gate(){if(!window.VIDA_SOUND?.enabled?.())return;try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;fanfareCtx=fanfareCtx||new A();if(fanfareCtx.state==='suspended')await fanfareCtx.resume();const c=fanfareCtx,now=c.currentTime,master=c.createGain();master.gain.setValueAtTime(.0001,now);master.gain.exponentialRampToValueAtTime(.055,now+.05);master.gain.exponentialRampToValueAtTime(.0001,now+3.3);master.connect(c.destination);const progression=[[110,164.8,220],[130.8,196,261.6],[146.8,220,293.7],[164.8,246.9,329.6]];progression.forEach((ch,ci)=>ch.forEach((f,fi)=>{const o=c.createOscillator(),g=c.createGain();o.type=fi===0?'triangle':'sine';o.frequency.value=f;g.gain.value=fi===0?.34:.17;o.connect(g).connect(master);const st=now+ci*.62;o.start(st);o.stop(st+.92)}));[440,523.25,659.25,880].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,now+i*.34);g.gain.exponentialRampToValueAtTime(.11,now+i*.34+.03);g.gain.exponentialRampToValueAtTime(.0001,now+i*.34+.28);o.connect(g).connect(master);o.start(now+i*.34);o.stop(now+i*.34+.3)});}catch(e){}}return{gate}})();

// ---------------- Fixed 35-question assessment ----------------
const v8CalibrationQuestions=[
{id:'v8-finance-evidence',cat:'Rendimiento',title:'Decisión financiera',skill:'Finanzas personales',kind:'scenario',text:'Detectás que un gasto mensual subió bastante. Antes de recortarlo, ¿qué harías?',options:[choice('Reviso qué cambió, cuánto impacta y si el gasto sigue aportando valor antes de decidir',3),choice('Pongo un límite más bajo para el mes siguiente y después reviso si alcanzó',2),choice('Busco otro gasto similar para compensar la diferencia',1),choice('Lo recorto directamente porque una suba ya indica un problema',1)]},
{id:'v8-health-evidence',cat:'Físico',title:'Recuperación',skill:'Salud física',kind:'habit',text:'Pensando en las últimas dos semanas, ¿con qué frecuencia ajustaste descanso o entrenamiento cuando acumulabas cansancio claro?',options:[choice('Casi nunca; sigo igual aunque note fatiga',0),choice('A veces, sólo cuando el cansancio ya afecta mucho',1),choice('Varias veces, según cómo venía durmiendo y rindiendo',2),choice('Lo reviso de forma bastante sistemática y ajusto carga o descanso cuando corresponde',3)]},
{id:'v8-productivity-evidence',cat:'Rendimiento',title:'Trabajo profundo',skill:'Productividad',kind:'habit',text:'En una semana normal, ¿cuántos días conseguís terminar una parte importante de tu prioridad antes de quedar atrapado en tareas pequeñas?',options:[choice('0–1 día',0),choice('2–3 días',1),choice('4–5 días',2),choice('6–7 días',3)]},
{id:'v8-social-evidence',cat:'Carisma',title:'Tensión interpersonal',skill:'Habilidades sociales',kind:'scenario',text:'Una conversación empieza a ponerse tensa y todavía necesitás llegar a un acuerdo útil. ¿Cómo seguís?',options:[choice('Bajo la velocidad, confirmo qué entendí de su postura y vuelvo al punto concreto que hay que resolver',3),choice('Explico con más detalle mi posición para reducir el malentendido',2),choice('Propongo cortar y retomarlo cuando los dos estén más tranquilos',2),choice('Intento cerrar rápido con una solución intermedia para que no escale',1)]}
];
const v8FallbackQuestions=[
{id:'v8-fallback-1',cat:'Intelecto',title:'Transferencia',skill:'Aprendizaje',kind:'scenario',text:'Aprendiste un método nuevo y funcionó una vez. ¿Qué harías para saber si realmente lo dominás?',options:[choice('Lo pruebo en un caso distinto y comparo qué tuve que adaptar',3),choice('Repito el mismo caso hasta hacerlo más rápido',2),choice('Busco otro ejemplo resuelto y comparo pasos',2),choice('Lo doy por aprendido si puedo recordar los pasos',1)]},
{id:'v8-fallback-2',cat:'Carisma',title:'Responsabilidad',skill:'Integridad / valores',kind:'scenario',text:'Un resultado salió bien, pero sabés que una parte importante fue suerte y el equipo cree que fue mérito del proceso. ¿Qué hacés?',options:[choice('Aclaro qué salió bien por proceso y qué no deberíamos asumir que se repetirá',3),choice('Espero al próximo resultado antes de sacar conclusiones',2),choice('Dejo que el equipo mantenga confianza y lo reviso por mi cuenta',1),choice('No lo menciono mientras el resultado sea positivo',0)]}
];
const buildAssessmentQueueV7=buildAssessmentQueue;
buildAssessmentQueue=function(){const fixed=fixedQuestions().map(prepareQuestion),obj=['logica','problemas','nutricion'].map(t=>makeObjectiveQuestion(t,2)),extra=v8CalibrationQuestions.map(prepareQuestion);return[fixed[0],obj[0],fixed[1],fixed[2],extra[0],fixed[3],fixed[4],obj[1],...fixed.slice(5,9),extra[1],fixed[9],obj[2],extra[2],...fixed.slice(10),extra[3]]}
scheduleAdaptive=function(track){const t=assessmentSession.adaptive[track];if(t.asked<4)assessmentSession.queue.push(makeObjectiveQuestion(track,clamp(Math.round(t.ability),1,5)))}
renderAssessmentQuestion=function(){const q=assessmentSession.current;if(!q)return;$('#assessmentCategory').textContent=`${q.cat.toUpperCase()} · ${q.kind==='adaptive-objective'?'PRUEBA ADAPTATIVA':'PERFIL'}`;$('#assessmentQuestionTitle').textContent=q.title;$('#assessmentQuestionText').textContent=q.text;$('#assessmentIndex').textContent=`${assessmentSession.answered+1}/${V8_TARGET_QUESTIONS}`;$('#assessmentProgress').style.width=`${Math.min(100,assessmentSession.answered/V8_TARGET_QUESTIONS*100)}%`;$('#assessmentOptions').innerHTML=q.options.map((o,i)=>`<button class="answer-btn" data-answer="${i}">${escapeHtml(o.label)}</button>`).join('')}
const finishAssessmentV7=finishAssessment;
finishAssessment=function(){finishAssessmentV7();state.version=8;state.assessmentEngineVersion=8;if(state.assessmentReport){state.assessmentReport.engine=8;state.assessmentReport.questionCount=assessmentSession.answered;}localStorage.setItem(storeKey,JSON.stringify(state));if($('#resultConfidence'))$('#resultConfidence').textContent=`Confianza inicial ${globalConfidence()} · ${assessmentSession.answered} preguntas · consistencia ${state.assessmentReport?.consistency??'—'}%`}
nextAssessment=function(){if(assessmentSession.answered>=V8_TARGET_QUESTIONS){assessmentSession.queue=[];return finishAssessment()}if(!assessmentSession.queue.length){const used=new Set(assessmentSession.responses.map(r=>r.id));const reserve=[...v8FallbackQuestions,...v8CalibrationQuestions].filter(q=>!used.has(q.id));while(assessmentSession.queue.length<V8_TARGET_QUESTIONS-assessmentSession.answered&&reserve.length)assessmentSession.queue.push(prepareQuestion(reserve.shift()));if(!assessmentSession.queue.length)return finishAssessment()}assessmentSession.current=assessmentSession.queue.shift();renderAssessmentQuestion()}

// ---------------- Collapsible Home ----------------
function setHomePanel(name,open,save=true){const sec=document.querySelector(`[data-home-panel="${name}"]`);if(!sec)return;sec.classList.toggle('is-open',!!open);sec.querySelector('[data-toggle-home-panel]')?.setAttribute('aria-expanded',String(!!open));state.ui.homePanels[name]=!!open;if(save)localStorage.setItem(storeKey,JSON.stringify(state))}
function bindHomePanels(){document.querySelectorAll('[data-toggle-home-panel]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.toggleHomePanel;setHomePanel(n,!state.ui.homePanels[n])}));Object.entries(state.ui.homePanels).forEach(([n,o])=>setHomePanel(n,o,false))}
function dayShort(i){return['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'][i]}
function renderHomeDiet(){const sum=$('#homeDietSummary'),today=$('#homeDietToday'),week=$('#homeDietWeek');if(!sum||!today||!week)return;const plan=state.dietPlan;if(!plan||plan.error){sum.textContent='Todavía no hay un plan semanal. Configuralo una vez y quedará resumido acá.';today.innerHTML='<div class="home-today-card"><h3>Tu dieta todavía no está configurada</h3><p class="note">El Dietario calcula una referencia diaria y arma 7 días de comidas.</p></div>';week.innerHTML='';return}const di=typeof planDayIndex==='function'?planDayIndex():0,d=plan.days[di],targets=plan.targets;sum.textContent=`${targets.calories} kcal · ${targets.protein} g proteína · hoy Día ${di+1}`;const log=state.dietLogs?.[todayKey()]||{meals:{}},done=d.meals.filter((m,i)=>log.meals?.[`${di}:${i}`]).length;today.innerHTML=`<div class="home-today-card"><div class="eyebrow">HOY · DÍA ${di+1}</div><h3>${d.totals.kcal} kcal · ${d.totals.p} g proteína</h3><div class="home-today-list">${d.meals.map((m,i)=>`<div class="home-today-item"><span>${log.meals?.[`${di}:${i}`]?'✓ ':''}${escapeHtml(m.name)}</span><strong>${m.kcal} kcal</strong></div>`).join('')}</div><p class="note">${done}/${d.meals.length} comidas marcadas hoy</p></div>`;week.innerHTML=plan.days.map((x,i)=>`<div class="home-day-mini ${i===di?'today':''}"><strong>Día ${i+1}</strong><span>${x.totals.kcal} kcal</span><span>${x.totals.p} g prot.</span></div>`).join('')}

// ---------------- Training plan ----------------
const gymExercises={
fullA:['Prensa o sentadilla','Press de pecho','Jalón al pecho','Peso muerto rumano','Press de hombros','Plancha'],
fullB:['Zancadas o prensa','Remo sentado','Press inclinado','Curl femoral','Elevaciones laterales','Core antirotación'],
fullC:['Sentadilla guiada','Press de pecho','Remo','Hip thrust','Jalón al pecho','Farmer carry o core'],
upper:['Press de pecho','Jalón al pecho','Remo sentado','Press de hombros','Curl de bíceps','Extensión de tríceps'],
lower:['Prensa o sentadilla','Peso muerto rumano','Zancadas','Curl femoral','Gemelos','Core'],
push:['Press de pecho','Press inclinado','Press de hombros','Elevaciones laterales','Extensión de tríceps'],
pull:['Jalón al pecho','Remo sentado','Remo unilateral','Face pull','Curl de bíceps'],
legs:['Prensa o sentadilla','Peso muerto rumano','Zancadas','Curl femoral','Gemelos','Core']};
const homeExercises={
fullA:['Sentadilla','Flexiones','Remo con mochila o banda','Puente de glúteos','Pike push-up','Plancha'],
fullB:['Zancadas','Flexiones inclinadas o declinadas','Remo unilateral con mochila','Peso muerto con mochila','Elevaciones laterales con banda','Dead bug'],
fullC:['Sentadilla pausada','Flexiones','Remo con banda','Hip thrust unilateral','Pike push-up','Plancha lateral'],
upper:['Flexiones','Remo con mochila o banda','Pike push-up','Remo unilateral','Curl con banda/mochila','Extensión de tríceps'],
lower:['Sentadilla','Zancadas','Peso muerto con mochila','Puente de glúteos','Gemelos','Core'],
push:['Flexiones','Pike push-up','Flexiones inclinadas/declinadas','Elevaciones laterales con banda','Extensión de tríceps'],
pull:['Remo con mochila','Remo con banda','Remo unilateral','Pájaros con banda','Curl con mochila/banda'],
legs:['Sentadilla','Zancadas','Peso muerto con mochila','Hip thrust','Gemelos','Core']};
function splitForCount(n){if(n<=2)return['fullA','fullB'];if(n===3)return['fullA','fullB','fullC'];if(n===4)return['upper','lower','upper','lower'];if(n===5)return['push','pull','legs','upper','lower'];return['push','pull','legs','push','pull','legs']}
function splitLabel(k,i){const map={fullA:'Cuerpo completo A',fullB:'Cuerpo completo B',fullC:'Cuerpo completo C',upper:i>=2?'Tren superior B':'Tren superior',lower:i>=3?'Tren inferior B':'Tren inferior',push:i>=3?'Empuje B':'Empuje',pull:i>=4?'Tirón B':'Tirón',legs:i>=5?'Piernas B':'Piernas'};return map[k]||k}
function prescription(profile,exerciseIndex){let sets=profile.level==='beginner'?2:profile.level==='advanced'?4:3,reps='8–12';if(profile.goal==='strength'){sets=Math.max(3,sets);reps=exerciseIndex<4?'4–7':'8–12'}if(profile.goal==='hypertrophy')reps=exerciseIndex<4?'6–12':'10–15';if(profile.goal==='performance')reps=exerciseIndex<3?'5–8':'8–12';return`${sets} × ${reps}`}
function buildTrainingPlan(profile){const days=[...profile.weekdays].sort((a,b)=>((a+6)%7)-((b+6)%7));const splits=splitForCount(days.length),lib=profile.location==='home'?homeExercises:gymExercises;const planDays=days.map((weekday,i)=>{const key=splits[i%splits.length],names=lib[key]||lib.fullA;return{weekday,focus:splitLabel(key,i),exercises:names.map((name,j)=>({id:crypto.randomUUID(),name,prescription:prescription(profile,j)})),cardio:profile.cardio?(profile.goal==='performance'?'10–20 min suave/moderado o técnica específica':'10–20 min suave opcional'):'',notes:'Dejá aproximadamente 2–3 repeticiones en reserva en la mayoría de las series y priorizá técnica.'}});return{createdAt:new Date().toISOString(),profile:{...profile,weekdays:days},days:planDays}}
function todayTrainingDay(){return state.trainingPlan?.days?.find(d=>d.weekday===new Date().getDay())||null}
function trainingLogForToday(){const k=todayKey();state.trainingLogs[k]=state.trainingLogs[k]||{done:{}};state.trainingLogs[k].done=state.trainingLogs[k].done||{};return state.trainingLogs[k]}
function renderHomeTraining(){const sum=$('#homeTrainingSummary'),today=$('#homeTrainingToday'),week=$('#homeTrainingWeek');if(!sum||!today||!week)return;const plan=state.trainingPlan;if(!plan){sum.textContent='Todavía no hay rutina. Podés crear una semanal según tu objetivo y días disponibles.';today.innerHTML='<div class="home-today-card"><h3>Sin rutina configurada</h3><p class="note">Creala una vez y el Inicio te mostrará automáticamente qué toca cada día.</p></div>';week.innerHTML='';return}const td=todayTrainingDay(),log=trainingLogForToday();sum.textContent=`${plan.days.length} días/semana · ${({general:'físico general',strength:'fuerza',hypertrophy:'hipertrofia',performance:'rendimiento'})[plan.profile.goal]}`;if(td){const done=td.exercises.filter(e=>log.done[e.id]).length;today.innerHTML=`<div class="home-today-card"><div class="eyebrow">ENTRENO DE HOY</div><h3>${escapeHtml(td.focus)} · ${done}/${td.exercises.length} ejercicios</h3><div class="home-today-list">${td.exercises.map(e=>`<div class="home-today-item"><span>${log.done[e.id]?'✓ ':''}${escapeHtml(e.name)}</span><strong>${escapeHtml(e.prescription)}</strong></div>`).join('')}</div></div>`}else today.innerHTML='<div class="home-today-card"><div class="eyebrow">HOY</div><h3>Día sin sesión programada</h3><p class="note">Recuperación o actividad libre según tu planificación.</p></div>';week.innerHTML=plan.days.map(d=>`<div class="home-day-mini ${d.weekday===new Date().getDay()?'today':''}"><strong>${dayShort(d.weekday)}</strong><span>${escapeHtml(d.focus)}</span><span>${d.exercises.length} ejercicios</span></div>`).join('')}
function renderTrainingPage(){if(page!=='training')return;const p=state.trainingProfile;$('#trainingGoal').value=p.goal;$('#trainingLevel').value=p.level;$('#trainingLocation').value=p.location;$('#trainingMinutes').value=p.minutes;$('#trainingCardio').checked=!!p.cardio;$('#trainingNotes').value=p.notes||'';$$('#trainingWeekdays input').forEach(x=>x.checked=(p.weekdays||[]).includes(+x.value));const plan=state.trainingPlan;$('#trainingDaysCount').textContent=plan?.days?.length||0;$('#trainingGoalPill').textContent=plan?({general:'GENERAL',strength:'FUERZA',hypertrophy:'HIPERTROFIA',performance:'RENDIMIENTO'})[plan.profile.goal]:'—';const td=todayTrainingDay(),log=trainingLogForToday();if(!plan){$('#trainingTodayTitle').textContent='Sin rutina todavía';$('#trainingTodaySummary').innerHTML='<div class="rest-card">Completá la configuración para generar tu semana.</div>';$('#trainingWeek').innerHTML='<div class="empty">No hay una rutina creada.</div>';return}if(td){$('#trainingTodayTitle').textContent=`${dayShort(td.weekday)} · ${td.focus}`;$('#trainingTodaySummary').innerHTML=`<div class="note">${td.exercises.filter(e=>log.done[e.id]).length}/${td.exercises.length} ejercicios marcados · ${plan.profile.minutes} min objetivo</div>`}else{$('#trainingTodayTitle').textContent='Día sin sesión programada';$('#trainingTodaySummary').innerHTML='<div class="rest-card">No hay entrenamiento estructurado hoy.</div>'}$('#trainingWeek').innerHTML=plan.days.map(d=>`<details class="training-day ${d.weekday===new Date().getDay()?'today':''}" ${d.weekday===new Date().getDay()?'open':''}><summary><div><strong>${dayShort(d.weekday)} · ${escapeHtml(d.focus)}</strong><div class="note">${d.exercises.length} ejercicios · ${plan.profile.minutes} min objetivo</div></div><span class="pill">${d.weekday===new Date().getDay()?'HOY':'RUTINA'}</span></summary><div class="training-day-body">${d.exercises.map(e=>{const checked=d.weekday===new Date().getDay()&&!!log.done[e.id];return`<label class="exercise-row ${checked?'done':''}"><input type="checkbox" data-training-exercise="${e.id}" ${checked?'checked':''} ${d.weekday!==new Date().getDay()?'disabled':''}><div><strong>${escapeHtml(e.name)}</strong><div class="exercise-prescription">${escapeHtml(e.prescription)}</div></div><span class="note">${d.weekday===new Date().getDay()?'marcar':'plan'}</span></label>`}).join('')}${d.cardio?`<div class="note section-space">Condicionamiento: ${escapeHtml(d.cardio)}</div>`:''}<div class="note">${escapeHtml(d.notes)}</div></div></details>`).join('')}
function saveTrainingForm(e){e.preventDefault();const weekdays=$$('#trainingWeekdays input:checked').map(x=>+x.value);if(weekdays.length<2)return toast('Elegí al menos 2 días para armar una rutina semanal.','warn');if(weekdays.length>6)return toast('Dejá al menos un día sin rutina estructurada.','warn');const profile={goal:$('#trainingGoal').value,level:$('#trainingLevel').value,location:$('#trainingLocation').value,minutes:+$('#trainingMinutes').value||60,weekdays,cardio:$('#trainingCardio').checked,notes:$('#trainingNotes').value.trim()};state.trainingProfile=profile;state.trainingPlan=buildTrainingPlan(profile);state.trainingLogs={};localStorage.setItem(storeKey,JSON.stringify(state));renderTrainingPage();window.VIDA_SOUND?.play?.('reward');const m=$('#trainingFormMessage');if(m){m.className='quiz-feedback good';m.textContent='Rutina semanal creada. El Inicio ya muestra el entrenamiento de cada día.'}}
function bindTrainingPage(){if(page!=='training')return;$('#trainingForm')?.addEventListener('submit',saveTrainingForm);$('#trainingWeek')?.addEventListener('change',e=>{const id=e.target.dataset.trainingExercise;if(!id)return;const td=todayTrainingDay();if(!td||!td.exercises.some(x=>x.id===id))return;const log=trainingLogForToday();log.done[id]=e.target.checked;localStorage.setItem(storeKey,JSON.stringify(state));window.VIDA_SOUND?.play?.(e.target.checked?'reward':'click');renderTrainingPage()})}

// ---------------- Render wrappers ----------------
const renderHomeBeforeV8=renderHome;
renderHome=function(){renderHomeBeforeV8();if($('#upgradeBanner'))$('#upgradeBanner').classList.toggle('hidden',!(state.assessmentComplete&&(state.assessmentEngineVersion||0)<8));renderHomeDiet();renderHomeTraining();Object.entries(state.ui.homePanels).forEach(([n,o])=>setHomePanel(n,o,false))}
const renderPageBeforeV8=renderPage;
renderPage=function(){renderPageBeforeV8();if(page==='training')renderTrainingPage()}

// page lifecycle: v7 already rendered once before this script; refresh V8 parts now
if(page==='home'){renderHome();bindHomePanels()}
if(page==='training'){renderTrainingPage();bindTrainingPage()}
if(page==='assessment'){window.VIDA_SOUND?.update?.()}
})();
